// packages/docs/angular-docs/src/routes/components+/combobox+/demos/combobox-items-demo.ts
import {Component} from "@angular/core"

import {ComboboxModule} from "@qualcomm-ui/angular/combobox"
import {comboboxCollection} from "@qualcomm-ui/core/combobox"

interface City {
  name: string
  value: string
}

@Component({
  imports: [ComboboxModule],
  selector: "combobox-items-demo",
  template: `
    <!-- preview -->
    <q-combobox
      class="w-48"
      label="City"
      placeholder="Select a city"
      [collection]="cityCollection"
    />
    <!-- preview -->
  `,
})
export class ComboboxItemsDemo {
  readonly cityCollection = comboboxCollection<City>({
    itemLabel: (item) => item.name,
    items: [
      {name: "San Diego", value: "SD"},
      {name: "Nashville", value: "NV"},
      {name: "Denver", value: "DV"},
      {name: "Miami", value: "MI"},
      {name: "Las Vegas", value: "LV"},
      {name: "New York City", value: "NYC"},
      {name: "San Francisco", value: "SF"},
    ],
    itemValue: (item) => item.value,
  })
}

// packages/docs/react-docs/src/routes/components+/combobox+/demos/combobox-items-demo.tsx
import type {ReactElement} from "react"

import {comboboxCollection} from "@qualcomm-ui/core/combobox"
import {Combobox} from "@qualcomm-ui/react/combobox"

// preview
const cityCollection = comboboxCollection({
  itemLabel: (item) => item.name,
  items: [
    {name: "San Diego", value: "SD"},
    {name: "Nashville", value: "NV"},
    {name: "Denver", value: "DV"},
    {name: "Miami", value: "MI"},
    {name: "Las Vegas", value: "LV"},
    {name: "New York City", value: "NYC"},
    {name: "San Francisco", value: "SF"},
  ],
  itemValue: (item) => item.value,
})
// preview

export function ComboboxItemsDemo(): ReactElement {
  return (
    <Combobox
      className="w-48"
      collection={cityCollection}
      label="City"
      placeholder="Select a city"
    />
  )
}
