// packages/frameworks/angular/src/checkbox-group/checkbox-group.component.ts
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import {Component, input} from "@angular/core"

import {
  FieldGroupRootDirective,
  provideQdsFieldGroupContext,
} from "@qualcomm-ui/angular/field-group"

/**
 * Groups multiple checkboxes with a label, hint, and error text.
 */
@Component({
  providers: [provideQdsFieldGroupContext()],
  selector: "[q-checkbox-group]",
  standalone: false,
  template: `
    @if (label()) {
      <legend q-field-group-label>{{ label() }}</legend>
    }
    <div q-field-group-items>
      <ng-content />
    </div>
    @if (hint() && !invalid()) {
      <div q-field-group-hint>{{ hint() }}</div>
    }
    @if (errorText() && invalid()) {
      <q-field-group-error-text>{{ errorText() }}</q-field-group-error-text>
    }
  `,
})
export class CheckboxGroupComponent extends FieldGroupRootDirective {
  /**
   * Error message displayed when invalid.
   */
  readonly errorText = input<string>()

  /**
   * Helper text displayed below items. Hidden when invalid.
   */
  readonly hint = input<string>()

  /**
   * Group label text.
   */
  readonly label = input<string>()
}

// packages/frameworks/react/src/checkbox-group/checkbox-group.tsx
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import type {ReactElement, ReactNode} from "react"

import {
  FieldGroupErrorText,
  FieldGroupHint,
  FieldGroupItems,
  FieldGroupLabel,
  FieldGroupRoot,
  type FieldGroupRootProps,
} from "@qualcomm-ui/react/field-group"

export interface CheckboxGroupProps extends FieldGroupRootProps {
  /**
   * React {@link https://react.dev/learn/passing-props-to-a-component#passing-jsx-as-children children} prop.
   */
  children: ReactNode

  /**
   * Error message displayed when invalid.
   */
  errorText?: string

  /**
   * Helper text displayed below items.
   */
  hint?: string

  /**
   * Group label text.
   */
  label?: string
}

/**
 * Groups multiple checkboxes with a label, hint, and error text.
 */
export function CheckboxGroup({
  children,
  errorText,
  hint,
  label,
  ...props
}: CheckboxGroupProps): ReactElement {
  const showHint = Boolean(hint) && !props.invalid
  const showError = Boolean(errorText) && props.invalid

  return (
    <FieldGroupRoot {...props}>
      {label && <FieldGroupLabel>{label}</FieldGroupLabel>}
      <FieldGroupItems>{children}</FieldGroupItems>
      {showHint && <FieldGroupHint>{hint}</FieldGroupHint>}
      {showError && <FieldGroupErrorText>{errorText}</FieldGroupErrorText>}
    </FieldGroupRoot>
  )
}

CheckboxGroup.Root = FieldGroupRoot
CheckboxGroup.Label = FieldGroupLabel
CheckboxGroup.Items = FieldGroupItems
CheckboxGroup.Hint = FieldGroupHint
CheckboxGroup.ErrorText = FieldGroupErrorText
