// packages/debug-apps/angular-csr/src/app/components/divider.ts
import {Component} from "@angular/core"

import {DividerFocusableDemo} from "@qualcomm-ui/angular-docs/components+/divider+/demos/divider-focusable-demo"
import {DividerOrientationDemo} from "@qualcomm-ui/angular-docs/components+/divider+/demos/divider-orientation-demo"
import {DividerShowcaseDemo} from "@qualcomm-ui/angular-docs/components+/divider+/demos/divider-showcase-demo"
import {DividerValueTextDemo} from "@qualcomm-ui/angular-docs/components+/divider+/demos/divider-value-text-demo"
import {DividerVariantsDemo} from "@qualcomm-ui/angular-docs/components+/divider+/demos/divider-variants-demo"

@Component({
  imports: [
    DividerFocusableDemo,
    DividerOrientationDemo,
    DividerShowcaseDemo,
    DividerValueTextDemo,
    DividerVariantsDemo,
  ],
  selector: "app-divider",
  template: `
    <div class="container">
      <div class="section">
        <h2 class="section-title">Focusable</h2>
        <div class="demo-container">
          <divider-focusable />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Orientation</h2>
        <div class="demo-container">
          <divider-orientation />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Showcase</h2>
        <div class="demo-container">
          <divider-showcase />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Value Text</h2>
        <div class="demo-container">
          <divider-value-text />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Variants</h2>
        <div class="demo-container">
          <divider-variants />
        </div>
      </div>
    </div>
  `,
})
export class DividerPage {}

// packages/debug-apps/react-ssr/src/routes/components+/divider+/_divider.tsx
import FocusableDemo from "@qualcomm-ui/react-docs/components+/divider+/demos/divider-focusable-demo"
import OrientationDemo from "@qualcomm-ui/react-docs/components+/divider+/demos/divider-orientation-demo"
import ShowcaseDemo from "@qualcomm-ui/react-docs/components+/divider+/demos/divider-showcase-demo"
import ValueTextDemo from "@qualcomm-ui/react-docs/components+/divider+/demos/divider-value-text-demo"
import VariantsDemo from "@qualcomm-ui/react-docs/components+/divider+/demos/divider-variants-demo"

const demos = [
  {component: FocusableDemo, title: "Focusable"},
  {component: OrientationDemo, title: "Orientation"},
  {component: ShowcaseDemo, title: "Showcase"},
  {component: ValueTextDemo, title: "Value Text"},
  {component: VariantsDemo, title: "Variants"},
]

export default function DividerDemos() {
  return (
    <div className="page">
      {demos.map(({component: Demo, title}) => (
        <div className="section" key={title}>
          <h2 className="section-title">{title}</h2>
          <div className="demo-container">
            <Demo />
          </div>
        </div>
      ))}
    </div>
  )
}
