// packages/docs/angular-docs/src/routes/components+/tag+/demos/tag-controlled-demo.ts
import {Component, signal} from "@angular/core"
import {Check, Plus} from "lucide-angular"

import {provideIcons} from "@qualcomm-ui/angular-core/lucide"
import {TagDirective} from "@qualcomm-ui/angular/tag"

@Component({
  imports: [TagDirective],
  providers: [provideIcons({Check, Plus})],
  selector: "tag-controlled-demo",
  template: `
    <div class="flex flex-col items-start gap-2">
      <!-- preview -->
      <button
        q-tag
        variant="selectable"
        [startIcon]="selected() ? 'Check' : 'Plus'"
        [(selected)]="selected"
      >
        {{ selected() ? "Subscribed" : "Subscribe" }}
      </button>
      <!-- preview -->
    </div>
  `,
})
export class TagControlledDemo {
  readonly selected = signal<boolean>(false)
}

// packages/docs/react-docs/src/routes/components+/tag+/demos/tag-controlled-demo.tsx
import {type ReactElement, useState} from "react"

import {Check, Plus, Star} from "lucide-react"

import {Tag} from "@qualcomm-ui/react/tag"

export function TagControlledDemo(): ReactElement {
  const [selected, setSelected] = useState<boolean>(false)

  return (
    <div className="flex flex-col items-start gap-2">
      {/* preview */}
      <Tag
        endIcon={<Star />}
        onSelectedChange={setSelected}
        selected={selected}
        size="lg"
        startIcon={selected ? Check : Plus}
        variant="selectable"
      >
        {selected ? "Subscribed" : "Subscribe"}
      </Tag>
      {/* preview */}
    </div>
  )
}
