// packages/docs/angular-docs/src/routes/components+/tag+/demos/tag-shape-demo.ts
import {Component} from "@angular/core"

import {TagDirective} from "@qualcomm-ui/angular/tag"

@Component({
  imports: [TagDirective],
  selector: "tag-shape-demo",

  template: `
    <div class="flex flex-col gap-2">
      <!-- preview -->
      <span q-tag shape="square">Label</span>
      <span q-tag shape="rounded">Label</span>
      <!-- preview -->
    </div>
  `,
})
export class TagShapeDemo {}

// packages/docs/react-docs/src/routes/components+/tag+/demos/tag-shape-demo.tsx
import type {ReactElement} from "react"

import {Tag} from "@qualcomm-ui/react/tag"

export function TagShapeDemo(): ReactElement {
  return (
    <div className="flex flex-col gap-2">
      {/* preview */}
      <Tag shape="square">Label</Tag>
      <Tag shape="rounded">Label</Tag>
      {/* preview */}
    </div>
  )
}
