// packages/docs/angular-docs/src/routes/components+/combobox+/demos/combobox-states-demo.ts
import {Component} from "@angular/core"

import {ComboboxModule} from "@qualcomm-ui/angular/combobox"
import {useListCollection} from "@qualcomm-ui/angular-core/collection"

import {countries} from "./country-list"

@Component({
  imports: [ComboboxModule],
  selector: "combobox-states-demo",
  template: `
    <div class="flex flex-col items-start gap-4">
      <q-combobox
        class="w-48"
        disabled
        label="Disabled"
        placeholder="Select a country"
        [collection]="listCollection.collection()"
      />
      <q-combobox
        class="w-48"
        label="Read Only"
        placeholder="Select a country"
        readOnly
        [collection]="listCollection.collection()"
      />
      <q-combobox
        class="w-48"
        invalid
        label="Invalid"
        placeholder="Select a country"
        [collection]="listCollection.collection()"
      />
    </div>
  `,
})
export class ComboboxStatesDemo {
  readonly listCollection = useListCollection<string>({
    filter: "contains",
    items: countries,
  })
}

// packages/debug-apps/react-ssr/src/routes/components+/combobox+/demos/combobox-states-demo.tsx
import type {ComboboxInputValueChangeDetails} from "@qualcomm-ui/core/combobox"
import {Combobox} from "@qualcomm-ui/react/combobox"
import {useListCollection} from "@qualcomm-ui/react-core/collection"
import {useFilter} from "@qualcomm-ui/react-core/locale"

import {countries} from "./country-list"

export default function Demo() {
  const {contains} = useFilter({sensitivity: "base"})

  const {collection, filter} = useListCollection({
    filter: contains,
    initialItems: countries,
  })

  function handleInputChange(details: ComboboxInputValueChangeDetails) {
    filter(details.inputValue)
  }

  return (
    <div className="flex w-60 flex-col gap-4">
      {/* preview */}
      <Combobox
        className="w-48"
        collection={collection}
        defaultValue={[countries[0]]}
        disabled
        label="Disabled"
        onInputValueChange={handleInputChange}
      />
      <Combobox
        className="w-48"
        collection={collection}
        defaultValue={[countries[0]]}
        label="Read only"
        onInputValueChange={handleInputChange}
        readOnly
      />
      <Combobox
        className="w-48"
        collection={collection}
        defaultValue={[countries[0]]}
        errorText="Invalid"
        invalid
        label="Invalid"
        onInputValueChange={handleInputChange}
      />
      {/* preview */}
    </div>
  )
}
