// packages/frameworks/angular/src/drawer/drawer-close-button.component.ts
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import {Component} from "@angular/core"
import {X} from "lucide-angular"

import {provideIcons} from "@qualcomm-ui/angular-core/lucide"
import {DialogCloseButtonComponent} from "@qualcomm-ui/angular/dialog"

/**
 * A button that closes the drawer.
 */
@Component({
  providers: [provideIcons({X})],
  selector: "[q-drawer-close-button]",
  standalone: false,
  template: `
    <svg qIcon="X" [q-bind]="buttonApi().getIconBindings()"></svg>
  `,
})
export class DrawerCloseButtonComponent extends DialogCloseButtonComponent {}

// packages/frameworks/react/src/drawer/drawer-close-button.tsx
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import type {ReactElement} from "react"

import {Dialog, type DialogCloseButtonProps} from "@qualcomm-ui/react/dialog"

export interface DrawerCloseButtonProps extends DialogCloseButtonProps {}

/**
 * A button that closes the drawer. Renders a `<button>` element by default.
 */
export function DrawerCloseButton(props: DrawerCloseButtonProps): ReactElement {
  return <Dialog.CloseButton {...props} />
}
