// packages/frameworks/angular/src/drawer/drawer-positioner.component.ts
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import {computed, Directive} from "@angular/core"

import {CoreDialogPositionerDirective} from "@qualcomm-ui/angular-core/dialog"

import {useQdsDrawerContext} from "./qds-drawer-context.service"

/**
 * A container for the drawer content that handles positioning.
 */
@Directive({
  selector: "[q-drawer-positioner]",
  standalone: false,
})
export class DrawerPositionerComponent extends CoreDialogPositionerDirective {
  protected readonly qdsContext = useQdsDrawerContext()

  constructor() {
    super()
    this.trackBindings.extendWith(
      computed(() => this.qdsContext().getPositionerBindings()),
    )
  }
}

// packages/frameworks/react/src/drawer/drawer-positioner.tsx
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import type {ReactNode} from "react"

import {CoreDialog} from "@qualcomm-ui/react-core/dialog"
import type {DialogPositionerProps} from "@qualcomm-ui/react/dialog"
import {mergeProps} from "@qualcomm-ui/utils/merge-props"

import {useQdsDrawerContext} from "./qds-drawer-context.js"

export interface DrawerPositionerProps extends DialogPositionerProps {}

/**
 * A container that positions the drawer on the screen. Renders a `<div>` element by
 * default.
 */
export function DrawerPositioner(props: DrawerPositionerProps): ReactNode {
  const qdsContext = useQdsDrawerContext()
  const mergedProps = mergeProps(qdsContext.getPositionerBindings(), props)

  return <CoreDialog.Positioner {...mergedProps} />
}
