// packages/docs/react-docs/src/routes/components+/checkbox-group+/demos/checkbox-group-simple-demo.tsx
import type {ReactElement} from "react"

import {Checkbox} from "@qualcomm-ui/react/checkbox"
import {CheckboxGroup} from "@qualcomm-ui/react/checkbox-group"

export function CheckboxGroupSimpleDemo(): ReactElement {
  return (
    // preview
    <CheckboxGroup hint="Select at least one" label="Notifications">
      <Checkbox label="Email" />
      <Checkbox label="SMS" />
      <Checkbox label="Push" />
    </CheckboxGroup>
    // preview
  )
}

// packages/docs/angular-docs/src/routes/components+/checkbox-group+/demos/checkbox-group-simple-demo.ts
import {Component} from "@angular/core"

import {CheckboxModule} from "@qualcomm-ui/angular/checkbox"
import {CheckboxGroupModule} from "@qualcomm-ui/angular/checkbox-group"

@Component({
  imports: [CheckboxGroupModule, CheckboxModule],
  selector: "checkbox-group-simple-demo",
  template: `
    <!-- preview -->
    <fieldset hint="Select at least one" label="Notifications" q-checkbox-group>
      <label label="Email" q-checkbox></label>
      <label label="SMS" q-checkbox></label>
      <label label="Push" q-checkbox></label>
    </fieldset>
    <!-- preview -->
  `,
})
export class CheckboxGroupSimpleDemo {}
