// packages/docs/react-docs/src/routes/components+/checkbox-group+/demos/checkbox-group-size-demo.tsx
import type {ReactElement} from "react"

import {Checkbox} from "@qualcomm-ui/react/checkbox"
import {CheckboxGroup} from "@qualcomm-ui/react/checkbox-group"

export function CheckboxGroupSizeDemo(): ReactElement {
  return (
    <div className="flex flex-row gap-8">
      <CheckboxGroup label="Small" size="sm">
        <Checkbox label="Email" />
        <Checkbox label="SMS" />
      </CheckboxGroup>
      <CheckboxGroup label="Medium" size="md">
        <Checkbox label="Email" />
        <Checkbox label="SMS" />
      </CheckboxGroup>
      <CheckboxGroup label="Large" size="lg">
        <Checkbox label="Email" />
        <Checkbox label="SMS" />
      </CheckboxGroup>
    </div>
  )
}

// packages/docs/angular-docs/src/routes/components+/checkbox-group+/demos/checkbox-group-size-demo.ts
import {Component} from "@angular/core"

import {CheckboxModule} from "@qualcomm-ui/angular/checkbox"
import {CheckboxGroupModule} from "@qualcomm-ui/angular/checkbox-group"

@Component({
  imports: [CheckboxGroupModule, CheckboxModule],
  selector: "checkbox-group-size-demo",
  template: `
    <div class="flex flex-row gap-8">
      <fieldset label="Small" q-checkbox-group size="sm">
        <label label="Email" q-checkbox></label>
        <label label="SMS" q-checkbox></label>
      </fieldset>
      <fieldset label="Medium" q-checkbox-group size="md">
        <label label="Email" q-checkbox></label>
        <label label="SMS" q-checkbox></label>
      </fieldset>
      <fieldset label="Large" q-checkbox-group size="lg">
        <label label="Email" q-checkbox></label>
        <label label="SMS" q-checkbox></label>
      </fieldset>
    </div>
  `,
})
export class CheckboxGroupSizeDemo {}
