// packages/docs/angular-docs/src/routes/components+/inline-notification+/demos/inline-notification-simple-demo.ts
import {Component} from "@angular/core"

import {InlineNotificationModule} from "@qualcomm-ui/angular/inline-notification"

@Component({
  imports: [InlineNotificationModule],
  selector: "inline-notification-simple-demo",
  template: `
    <!-- preview -->
    <div
      class="w-96"
      description="Description"
      dismissable
      label="Label"
      q-inline-notification
    ></div>
    <!-- preview -->
  `,
})
export class InlineNotificationSimpleDemo {}

// packages/docs/react-docs/src/routes/components+/inline-notification+/demos/inline-notification-simple-demo.tsx
import type {ReactElement} from "react"

import {InlineNotification} from "@qualcomm-ui/react/inline-notification"

export default function InlineNotificationSimpleDemo(): ReactElement {
  return (
    // preview
    <InlineNotification
      className="w-96"
      description="Description"
      dismissable
      label="Label"
    />
    // preview
  )
}
