// packages/docs/angular-docs/src/routes/components+/inline-notification+/demos/inline-notification-explorer-demo.ts
import {Component} from "@angular/core"

import {InlineNotificationModule} from "@qualcomm-ui/angular/inline-notification"
import {LinkDirective} from "@qualcomm-ui/angular/link"

@Component({
  imports: [InlineNotificationModule, LinkDirective],
  selector: "inline-notification-explorer-demo",
  template: `
    <div
      class="w-96"
      description="Description"
      dismissable
      label="Label"
      q-inline-notification
    >
      <button q-inline-notification-action q-link>Text link</button>
    </div>
  `,
})
export class InlineNotificationExplorerDemo {}

// packages/docs/react-docs/src/routes/components+/inline-notification+/demos/inline-notification-explorer-demo.tsx
import type {ReactElement} from "react"

import {InlineNotification} from "@qualcomm-ui/react/inline-notification"
import {Link} from "@qualcomm-ui/react/link"

export function InlineNotificationExplorerDemo(): ReactElement {
  return (
    <InlineNotification
      action={<Link>Text link</Link>}
      className="w-96"
      description="Description"
      dismissable
      label="Label"
    />
  )
}
