// packages/docs/react-docs/src/routes/components+/date-picker+/demos/date-picker-explorer-demo.tsx
import type {ReactElement} from "react"

import {
  DatePicker,
  getLocalTimeZone,
  parseDate,
  today,
} from "@qualcomm-ui/react/date-picker"

export function DatePickerExplorerDemo(): ReactElement {
  return (
    <DatePicker
      className="w-64"
      defaultOpen
      defaultValue={[parseDate("2026-08-14")]}
      hint="Choose a date in mm/dd/yyyy format"
      label="Departure date"
      portalProps={{disabled: true}}
      presets={[
        {label: "Today", value: [today(getLocalTimeZone())]},
        {label: "Tomorrow", value: [today(getLocalTimeZone()).add({days: 1})]},
      ]}
    />
  )
}

// packages/docs/angular-docs/src/routes/components+/date-picker+/demos/date-picker-explorer-demo.ts
import {Component} from "@angular/core"

import {
  type DatePickerPreset,
  DatePickerModule,
  getLocalTimeZone,
  parseDate,
  today,
} from "@qualcomm-ui/angular/date-picker"

@Component({
  imports: [DatePickerModule],
  selector: "date-picker-explorer-demo",
  template: `
    <q-date-picker
      class="w-64"
      defaultOpen
      disablePortal
      hint="Choose a date in mm/dd/yyyy format"
      label="Departure date"
      [defaultValue]="defaultValue"
      [presets]="presets"
    />
  `,
})
export class DatePickerExplorerDemo {
  readonly defaultValue = [parseDate("2026-08-14")]

  readonly presets: DatePickerPreset[] = [
    {label: "Today", value: [today(getLocalTimeZone())]},
    {label: "Tomorrow", value: [today(getLocalTimeZone()).add({days: 1})]},
  ]
}
