// packages/docs/react-docs/src/routes/components+/date-picker+/demos/date-picker-sizes-demo.tsx
import type {ReactElement} from "react"

import {DatePicker} from "@qualcomm-ui/react/date-picker"

export function DatePickerSizesDemo(): ReactElement {
  return (
    <div className="flex flex-col items-start gap-4">
      {/* preview */}
      <DatePicker className="w-64" label="Small" size="sm" />
      <DatePicker className="w-64" label="Medium" size="md" />
      <DatePicker className="w-64" label="Large" size="lg" />
      {/* preview */}
    </div>
  )
}

// packages/docs/angular-docs/src/routes/components+/date-picker+/demos/date-picker-sizes-demo.ts
import {Component} from "@angular/core"

import {DatePickerModule} from "@qualcomm-ui/angular/date-picker"

@Component({
  imports: [DatePickerModule],
  selector: "date-picker-sizes-demo",
  template: `
    <div class="flex flex-col items-start gap-4">
      <!-- preview -->
      <q-date-picker class="w-64" label="Small" size="sm" />
      <q-date-picker class="w-64" label="Medium" size="md" />
      <q-date-picker class="w-64" label="Large" size="lg" />
      <!-- preview -->
    </div>
  `,
})
export class DatePickerSizesDemo {}
