// packages/docs/react-docs/src/routes/components+/date-picker+/demos/date-picker-states-demo.tsx
import type {ReactElement} from "react"

import {DatePicker, parseDate} from "@qualcomm-ui/react/date-picker"

const departureDate = [parseDate("2026-08-14")]

export function DatePickerStatesDemo(): ReactElement {
  return (
    <div className="flex flex-col gap-4">
      {/* preview */}
      <DatePicker
        className="w-64"
        defaultValue={departureDate}
        disabled
        label="Disabled"
      />
      <DatePicker
        className="w-64"
        defaultValue={departureDate}
        label="Read only"
        readOnly
      />
      <DatePicker
        className="w-64"
        defaultValue={departureDate}
        errorText="Choose a later date"
        invalid
        label="Invalid"
      />
      {/* preview */}
    </div>
  )
}

// packages/docs/angular-docs/src/routes/components+/date-picker+/demos/date-picker-states-demo.ts
import {Component} from "@angular/core"

import {DatePickerModule, parseDate} from "@qualcomm-ui/angular/date-picker"

@Component({
  imports: [DatePickerModule],
  selector: "date-picker-states-demo",
  template: `
    <div class="flex flex-col gap-4">
      <!-- preview -->
      <q-date-picker
        class="w-64"
        disabled
        label="Disabled"
        [defaultValue]="departureDate"
      />
      <q-date-picker
        class="w-64"
        label="Read only"
        readOnly
        [defaultValue]="departureDate"
      />
      <q-date-picker
        class="w-64"
        errorText="Choose a later date"
        invalid
        label="Invalid"
        [defaultValue]="departureDate"
      />
      <!-- preview -->
    </div>
  `,
})
export class DatePickerStatesDemo {
  readonly departureDate = [parseDate("2026-08-14")]
}
