// packages/docs/react-docs/src/routes/components+/badges+/text-badge+/demos/text-badge-disabled-demo.tsx
import type {ReactElement} from "react"

import {Badge} from "@qualcomm-ui/react/badge"

export function TextBadgeDisabledDemo(): ReactElement {
  return (
    <div className="flex flex-wrap items-center gap-4">
      {/* preview */}
      <Badge emphasis="brand">Enabled</Badge>
      <Badge disabled emphasis="brand">
        Disabled
      </Badge>
      {/* preview */}
    </div>
  )
}

// packages/docs/angular-docs/src/routes/components+/badges+/text-badge+/demos/text-badge-disabled-demo.ts
import {Component} from "@angular/core"

import {BadgeDirective} from "@qualcomm-ui/angular/badge"

@Component({
  imports: [BadgeDirective],
  selector: "text-badge-disabled-demo",
  template: `
    <div class="flex flex-wrap items-center gap-4">
      <!-- preview -->
      <span emphasis="brand" q-badge>Enabled</span>
      <span emphasis="brand" q-badge [disabled]="true">Disabled</span>
      <!-- preview -->
    </div>
  `,
})
export class TextBadgeDisabledDemo {}
