// packages/docs/angular-docs/src/routes/components+/card+/demos/card-showcase-demo.ts
import {Component} from "@angular/core"
import {User} from "lucide-angular"

import {AvatarModule} from "@qualcomm-ui/angular/avatar"
import {CardModule} from "@qualcomm-ui/angular/card"
import {IconDirective} from "@qualcomm-ui/angular/icon"
import {provideIcons} from "@qualcomm-ui/angular-core/lucide"

@Component({
  imports: [CardModule, AvatarModule, IconDirective],
  providers: [provideIcons({User})],
  selector: "card-showcase-demo",
  template: `
    <div class="flex flex-wrap gap-6">
      <!-- preview -->
      <div class="w-72" q-card variant="outline">
        <div q-card-media>
          <div q-card-avatar>
            <div q-avatar-content>
              <svg aria-label="User" qIcon="User"></svg>
            </div>
          </div>
        </div>
        <div q-card-content>
          <div q-card-heading>
            <div q-card-heading-text>Card Title</div>
            <div q-card-subheading-text>Subheading</div>
          </div>

          <div q-card-subheading-text>Paragraph Subheading</div>
          <p q-card-paragraph-text>
            This is a small card with media, header, body text, and a footer
            with actions.
          </p>
        </div>
        <div q-card-footer>
          <button q-card-button variant="secondary">Cancel</button>
          <button q-card-button variant="primary">Confirm</button>
        </div>
      </div>
      <!-- preview -->
    </div>
  `,
})
export class CardShowcaseDemo {}

// packages/docs/react-docs/src/routes/components+/card+/demos/card-showcase-demo.tsx
import type {ReactElement} from "react"

import {User} from "lucide-react"

import {Avatar} from "@qualcomm-ui/react/avatar"
import {Card} from "@qualcomm-ui/react/card"

export function CardShowcaseDemo(): ReactElement {
  return (
    <div className="flex flex-wrap gap-6">
      {/* preview */}
      <Card.Root className="w-72" variant="outline">
        <Card.Media>
          <Card.Avatar>
            <Avatar.Content icon={User} />
          </Card.Avatar>
        </Card.Media>
        <Card.Content>
          <Card.Heading>
            <Card.HeadingText>Card Title</Card.HeadingText>
            <Card.SubheadingText>Subheading</Card.SubheadingText>
          </Card.Heading>

          <Card.SubheadingText>Paragraph Subheading</Card.SubheadingText>
          <Card.ParagraphText>
            This is a small card with media, header, body text, and a footer
            with actions.
          </Card.ParagraphText>
        </Card.Content>
        <Card.Footer>
          <Card.Button variant="secondary">Cancel</Card.Button>
          <Card.Button variant="primary">Confirm</Card.Button>
        </Card.Footer>
      </Card.Root>
      {/* preview */}
    </div>
  )
}
