// packages/docs/angular-docs/src/routes/components+/avatar+/demos/avatar-emphasis-demo.ts
import {Component} from "@angular/core"

import {AvatarModule} from "@qualcomm-ui/angular/avatar"

@Component({
  imports: [AvatarModule],
  selector: "avatar-emphasis",
  template: `
    <div class="flex items-center gap-4">
      <!-- preview -->
      Neutral
      <div emphasis="neutral" q-avatar>
        <div q-avatar-content>O</div>
      </div>
      High Contrast
      <div emphasis="contrast" q-avatar>
        <div q-avatar-content>O</div>
      </div>
      Brand
      <div emphasis="brand" q-avatar>
        <div q-avatar-content>O</div>
      </div>
      <!-- preview -->
    </div>
  `,
})
export class AvatarEmphasisDemo {}

// packages/docs/react-docs/src/routes/components+/avatar+/demos/avatar-emphasis-demo.tsx
import type {ReactElement} from "react"

import {Avatar} from "@qualcomm-ui/react/avatar"

export function AvatarEmphasisDemo(): ReactElement {
  return (
    <div className="flex items-center gap-4">
      {/* preview */}
      Neutral
      <Avatar.Root emphasis="neutral">
        <Avatar.Content>O</Avatar.Content>
      </Avatar.Root>
      High Contrast
      <Avatar.Root emphasis="contrast">
        <Avatar.Content>O</Avatar.Content>
      </Avatar.Root>
      Brand
      <Avatar.Root emphasis="brand">
        <Avatar.Content>O</Avatar.Content>
      </Avatar.Root>
      {/* preview */}
    </div>
  )
}
