// packages/docs/angular-docs/src/routes/components+/avatar+/demos/avatar-size-demo.ts
import {Component} from "@angular/core"

import {AvatarModule} from "@qualcomm-ui/angular/avatar"

@Component({
  imports: [AvatarModule],
  selector: "avatar-size",
  template: `
    <div class="flex items-center gap-4">
      <!-- preview -->
      XSmall
      <div q-avatar size="xs">
        <img alt="Jane Doe" q-avatar-image src="/images/avatar-woman.png" />
        <div q-avatar-content>JD</div>
      </div>
      Small
      <div q-avatar size="sm">
        <img alt="Jane Doe" q-avatar-image src="/images/avatar-woman.png" />
        <div q-avatar-content>JD</div>
      </div>
      Medium
      <div q-avatar size="md">
        <img alt="Jane Doe" q-avatar-image src="/images/avatar-woman.png" />
        <div q-avatar-content>JD</div>
      </div>
      Large
      <div q-avatar size="lg">
        <img alt="Jane Doe" q-avatar-image src="/images/avatar-woman.png" />
        <div q-avatar-content>JD</div>
      </div>
      XLarge
      <div q-avatar size="xl">
        <img alt="Jane Doe" q-avatar-image src="/images/avatar-woman.png" />
        <div q-avatar-content>JD</div>
      </div>
      <!-- preview -->
    </div>
  `,
})
export class AvatarSizeDemo {}

// packages/docs/react-docs/src/routes/components+/avatar+/demos/avatar-size-demo.tsx
import type {ReactElement} from "react"

import type {QdsAvatarSize} from "@qualcomm-ui/qds-core/avatar"
import {Avatar} from "@qualcomm-ui/react/avatar"

const sizes: QdsAvatarSize[] = ["xs", "sm", "md", "lg", "xl"]

export function AvatarSizeDemo(): ReactElement {
  return (
    <div className="flex items-center gap-4">
      {/* preview */}

      {sizes.map((size) => (
        <div key={size} className="flex flex-col items-center gap-2">
          <Avatar.Root size={size}>
            <Avatar.Image alt="Jane Doe" src="/images/avatar-woman.png" />
            <Avatar.Content>JD</Avatar.Content>
          </Avatar.Root>
          {size}
        </div>
      ))}
      {/* preview */}
    </div>
  )
}
