// packages/frameworks/angular-core/src/common/use-on-destroy.ts
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import {DestroyRef, inject} from "@angular/core"

/**
 * Creates a utility that provides component cleanup functionality
 * using Angular's DestroyRef.
 *
 * @returns A single method for registering a cleanup callback.
 */
export function useOnDestroy() {
  const destroyRef = inject(DestroyRef)

  return (callback: () => void): void => {
    destroyRef.onDestroy(callback)
  }
}

// packages/frameworks/react-core/src/effects/use-on-destroy.ts
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import {useRef} from "react"

import {useSafeLayoutEffect} from "./use-safe-layout-effect.js"

interface OnDestroyOptions {
  debugName?: string
}

/**
 * Hook that provides a function to register cleanup callbacks for when
 * the component unmounts.
 *
 * @returns A function to register cleanup callbacks
 */
export function useOnDestroy(
  opts?: OnDestroyOptions,
): (callback: () => void) => void {
  const cleanupCallbacks = useRef<Array<() => void>>([])

  const debugOpts = useRef(opts)
  debugOpts.current = opts

  useSafeLayoutEffect(() => {
    return () => {
      if (debugOpts.current?.debugName) {
        console.debug("onDestroy", debugOpts.current.debugName)
      }
      for (const callback of cleanupCallbacks.current) {
        callback()
      }
      cleanupCallbacks.current = []
    }
  }, [])

  return (callback: () => void): void => {
    cleanupCallbacks.current.push(callback)
  }
}
