// packages/debug-apps/angular-ssr/src/app/components/pagination.ts
import {Component} from "@angular/core"

import {PaginationPageMetadataDemo} from "@qualcomm-ui/angular-docs/components+/pagination+/demos/pagination-page-metadata-demo"
import {PaginationPageSizeDemo} from "@qualcomm-ui/angular-docs/components+/pagination+/demos/pagination-page-size-demo"
import {PaginationRangesDemo} from "@qualcomm-ui/angular-docs/components+/pagination+/demos/pagination-ranges-demo"
import {PaginationShowcaseDemo} from "@qualcomm-ui/angular-docs/components+/pagination+/demos/pagination-showcase-demo"

@Component({
  imports: [
    PaginationPageMetadataDemo,
    PaginationPageSizeDemo,
    PaginationRangesDemo,
    PaginationShowcaseDemo,
  ],
  template: `
    <div
      class="container"
      style="max-width: 1200px; margin: 0 auto; padding: 2rem;"
    >
      <div class="section">
        <h2 class="section-title">Page Metadata</h2>
        <div class="demo-container">
          <pagination-page-metadata-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Page Size</h2>
        <div class="demo-container">
          <pagination-page-size-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Ranges</h2>
        <div class="demo-container">
          <pagination-directive-ranges-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Showcase</h2>
        <div class="demo-container">
          <pagination-directive-showcase-demo />
        </div>
      </div>
    </div>
  `,
})
export class PaginationPage {}

// packages/debug-apps/react-ssr/src/routes/components+/pagination+/_pagination.tsx
import ControlledStateDemo from "@qualcomm-ui/react-docs/components+/pagination+/demos/pagination-controlled-state-demo"
import MetadataDemo from "@qualcomm-ui/react-docs/components+/pagination+/demos/pagination-metadata-demo"
import PageSizeDemo from "@qualcomm-ui/react-docs/components+/pagination+/demos/pagination-page-size-demo"
import RangesDemo from "@qualcomm-ui/react-docs/components+/pagination+/demos/pagination-ranges-demo"
import ShowcaseDemo from "@qualcomm-ui/react-docs/components+/pagination+/demos/pagination-showcase-demo"
import SizesDemo from "@qualcomm-ui/react-docs/components+/pagination+/demos/pagination-sizes-demo"

const demos = [
  {component: ControlledStateDemo, title: "Controlled State"},
  {component: MetadataDemo, title: "Metadata"},
  {component: PageSizeDemo, title: "Page Size"},
  {component: RangesDemo, title: "Ranges"},
  {component: ShowcaseDemo, title: "Showcase"},
  {component: SizesDemo, title: "Sizes"},
]

export default function PaginationDemos() {
  return (
    <div className="page">
      {demos.map(({component: Demo, title}) => (
        <div className="section" key={title}>
          <h2 className="section-title">{title}</h2>
          <div className="demo-container">
            <Demo />
          </div>
        </div>
      ))}
    </div>
  )
}
