// packages/docs/angular-docs/src/routes/components+/segmented-control+/demos/segmented-control-multiple-demo.ts
import {Component} from "@angular/core"

import {SegmentedControlModule} from "@qualcomm-ui/angular/segmented-control"

@Component({
  imports: [SegmentedControlModule],
  selector: "segmented-control-multiple-demo",
  template: `
    <!-- preview -->
    <fieldset multiple q-segmented-control>
      <label q-segmented-control-item text="Production" value="prod"></label>
      <label q-segmented-control-item text="Staging" value="stag"></label>
      <label q-segmented-control-item text="Development" value="dev"></label>
      <label q-segmented-control-item text="QA" value="qa"></label>
    </fieldset>
    <!-- preview -->
  `,
})
export class SegmentedControlMultipleDemo {}

// packages/docs/react-docs/src/routes/components+/segmented-control+/demos/segmented-control-multiple-demo.tsx
import {SegmentedControl} from "@qualcomm-ui/react/segmented-control"

export default function SegmentedControlMultipleDemo() {
  return (
    // preview
    <SegmentedControl.Root multiple>
      <SegmentedControl.Item text="Production" value="prod" />
      <SegmentedControl.Item text="Staging" value="staging" />
      <SegmentedControl.Item text="Development" value="dev" />
      <SegmentedControl.Item text="QA" value="qa" />
    </SegmentedControl.Root>
    // preview
  )
}
