// packages/debug-apps/react-ssr/src/routes/components+/text-input+/demos/text-input-simple-demo.tsx
import type {ReactElement} from "react"

import {TextInput} from "@qualcomm-ui/react/text-input"

export default function TextInputSimpleDemo(): ReactElement {
  return (
    // preview
    <TextInput
      className="w-72"
      hint="Optional hint"
      label="Label"
      placeholder="Placeholder text"
    />
    // preview
  )
}

// packages/docs/angular-docs/src/routes/components+/text-input+/demos/text-input-simple-demo.ts
import {Component} from "@angular/core"

import {TextInputModule} from "@qualcomm-ui/angular/text-input"

@Component({
  imports: [TextInputModule],
  selector: "text-input-simple-demo",
  template: `
    <!-- preview -->
    <q-text-input
      class="w-72"
      hint="Optional hint"
      label="Label"
      placeholder="Placeholder text"
    />
    <!-- preview -->
  `,
})
export class TextInputSimpleDemo {}
