// packages/frameworks/react/src/accordion/accordion-item-text.tsx
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import type {ComponentPropsWithRef, ReactElement, ReactNode} from "react"

import {accordionClasses} from "@qualcomm-ui/qds-core/accordion"
import {useAccordionItemText} from "@qualcomm-ui/react-core/accordion"
import {PolymorphicElement} from "@qualcomm-ui/react-core/system"
import {mergeProps} from "@qualcomm-ui/utils/merge-props"

export interface AccordionItemTextProps extends ComponentPropsWithRef<"span"> {
  /**
   * React {@link https://react.dev/learn/passing-props-to-a-component#passing-jsx-as-children children} prop.
   */
  children?: ReactNode
}

/**
 * A heading that labels the accordion item. Renders a `<span>` element by default.
 */
export function AccordionItemText(props: AccordionItemTextProps): ReactElement {
  const contextProps = useAccordionItemText()
  const mergedProps = mergeProps(
    contextProps,
    {className: accordionClasses.itemText},
    props,
  )
  return <PolymorphicElement as="span" {...mergedProps} />
}

// packages/frameworks/angular/src/accordion/accordion-item-text.component.ts
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import {Directive} from "@angular/core"

import {CoreAccordionItemTriggerTitleDirective} from "@qualcomm-ui/angular-core/accordion"
import {accordionClasses} from "@qualcomm-ui/qds-core/accordion"

@Directive({
  host: {
    "[class]": "accordionClasses.itemText",
  },
  selector: "[q-accordion-item-text]",
  standalone: false,
})
export class AccordionItemTextComponent extends CoreAccordionItemTriggerTitleDirective {
  protected readonly accordionClasses = accordionClasses
}
