// packages/docs/angular-docs/src/routes/components+/date-picker+/demos/date-picker-within-dialog-demo.ts
import {Component} from "@angular/core"

import {ButtonModule} from "@qualcomm-ui/angular/button"
import {DatePickerModule} from "@qualcomm-ui/angular/date-picker"
import {DialogModule} from "@qualcomm-ui/angular/dialog"

@Component({
  imports: [DatePickerModule, ButtonModule, DialogModule],
  selector: "date-picker-within-dialog-demo",
  template: `
    <div q-dialog-root>
      <button emphasis="primary" q-button q-dialog-trigger variant="fill">
        Open Dialog
      </button>
      <q-dialog-floating-portal>
        <div q-dialog-body>
          <div q-dialog-heading>Book a Flight</div>
          <button q-dialog-close-button></button>
          <!-- preview -->
          <q-date-picker class="w-64" disablePortal label="Departure date" />
          <!-- preview -->
        </div>

        <div q-dialog-footer>
          <button
            emphasis="primary"
            q-button
            q-dialog-close-trigger
            size="sm"
            variant="fill"
          >
            Confirm
          </button>
        </div>
      </q-dialog-floating-portal>
    </div>
  `,
})
export class DatePickerWithinDialogDemo {}

// packages/docs/react-docs/src/routes/components+/date-picker+/demos/date-picker-within-dialog-demo.tsx
import type {ReactElement} from "react"

import {Button} from "@qualcomm-ui/react/button"
import {DatePicker} from "@qualcomm-ui/react/date-picker"
import {Dialog} from "@qualcomm-ui/react/dialog"

export function DatePickerWithinDialogDemo(): ReactElement {
  return (
    <Dialog.Root>
      <Dialog.Trigger>
        <Button emphasis="primary" variant="fill">
          Open Dialog
        </Button>
      </Dialog.Trigger>
      <Dialog.FloatingPortal>
        <Dialog.Body>
          <Dialog.Heading>Book a Flight</Dialog.Heading>
          <Dialog.CloseButton />
          <DatePicker
            className="w-64"
            label="Departure date"
            portalProps={{disabled: true}}
          />
        </Dialog.Body>

        <Dialog.Footer>
          <Dialog.CloseTrigger>
            <Button emphasis="primary" size="sm" variant="fill">
              Confirm
            </Button>
          </Dialog.CloseTrigger>
        </Dialog.Footer>
      </Dialog.FloatingPortal>
    </Dialog.Root>
  )
}
