// packages/docs/angular-docs/src/routes/components+/menu+/demos/menu-header-footer-demo.ts
import {Component, input, signal} from "@angular/core"

import {PortalDirective} from "@qualcomm-ui/angular-core/portal"
import {ButtonModule} from "@qualcomm-ui/angular/button"
import {MenuModule} from "@qualcomm-ui/angular/menu"

@Component({
  imports: [ButtonModule, MenuModule, PortalDirective],
  selector: "menu-header-footer-filter-menu",
  template: `
    <q-menu
      [closeOnSelect]="false"
      [open]="open()"
      [size]="size()"
      (openChanged)="open.set($event)"
    >
      <button emphasis="primary" q-menu-button>{{ label() }}</button>
      <ng-container *qPortal>
        <div q-menu-positioner>
          <!-- preview -->
          <div q-menu-header>
            <div q-menu-header-label>
              Applied filters: {{ selectedFilters().length }}
            </div>
            <button
              emphasis="primary"
              q-button
              type="button"
              (click)="selectedFilters.set([])"
            >
              Clear all
            </button>
          </div>
          <div q-menu-content [style.maxHeight.px]="200">
            @for (filter of filters; track filter.value) {
              <button
                q-menu-checkbox-item
                [checked]="selectedFilters().includes(filter.value)"
                [value]="filter.value"
                (checkedChanged)="onCheckedChange(filter.value, $event)"
              >
                <div q-menu-checkbox-item-control></div>
                <div q-menu-item-label>{{ filter.label }}</div>
              </button>
            }
          </div>
          <div q-menu-footer>
            <button
              emphasis="neutral"
              q-button
              type="button"
              variant="fill"
              (click)="open.set(false)"
            >
              Apply Filters
            </button>
          </div>
          <!-- preview -->
        </div>
      </ng-container>
    </q-menu>
  `,
})
export class FilterMenu {
  readonly label = input.required<string>()
  readonly size = input.required<"sm" | "md">()

  protected readonly filters = [
    {label: "Project name", value: "project"},
    {label: "Status", value: "status"},
    {label: "Owner", value: "owner"},
    {label: "Team", value: "team"},
    {label: "Region", value: "region"},
    {label: "Start date", value: "start-date"},
    {label: "Due date", value: "due-date"},
    {label: "Last updated", value: "updated"},
  ]
  protected readonly open = signal(false)
  protected readonly selectedFilters = signal(["project", "status", "owner"])

  protected onCheckedChange(value: string, checked: boolean | undefined) {
    this.selectedFilters.update((previous) =>
      checked
        ? [...previous, value]
        : previous.filter((item) => item !== value),
    )
  }
}

@Component({
  imports: [FilterMenu],
  selector: "menu-header-footer-demo",
  template: `
    <div class="flex items-center gap-4">
      <menu-header-footer-filter-menu label="Small menu" size="sm" />
      <menu-header-footer-filter-menu label="Medium menu" size="md" />
    </div>
  `,
})
export class MenuHeaderFooterDemo {}

// packages/docs/react-docs/src/routes/components+/menu+/demos/menu-header-footer-demo.tsx
import {type ReactElement, useState} from "react"

import {Portal} from "@qualcomm-ui/react-core/portal"
import {Button} from "@qualcomm-ui/react/button"
import {Menu} from "@qualcomm-ui/react/menu"

const filters = [
  {label: "Project name", value: "project"},
  {label: "Status", value: "status"},
  {label: "Owner", value: "owner"},
  {label: "Team", value: "team"},
  {label: "Region", value: "region"},
  {label: "Start date", value: "start-date"},
  {label: "Due date", value: "due-date"},
  {label: "Last updated", value: "updated"},
]

interface FilterMenuProps {
  label: string
  size: "sm" | "md"
}

function FilterMenu({label, size}: FilterMenuProps): ReactElement {
  const [open, setOpen] = useState(false)
  const [selectedFilters, setSelectedFilters] = useState([
    "project",
    "status",
    "owner",
  ])

  const onCheckedChange = (value: string, checked: boolean) => {
    setSelectedFilters((previous) =>
      checked
        ? [...previous, value]
        : previous.filter((item) => item !== value),
    )
  }

  return (
    <Menu.Root
      closeOnSelect={false}
      onOpenChange={setOpen}
      open={open}
      size={size}
    >
      <Menu.Trigger>
        <Menu.Button emphasis="primary">{label}</Menu.Button>
      </Menu.Trigger>
      <Portal>
        <Menu.Positioner>
          {/* preview */}
          <Menu.Header>
            <Menu.HeaderLabel>
              Applied filters: {selectedFilters.length}
            </Menu.HeaderLabel>
            <Button
              emphasis="primary"
              onClick={() => setSelectedFilters([])}
              type="button"
            >
              Clear all
            </Button>
          </Menu.Header>
          <Menu.Content style={{maxHeight: 200}}>
            {filters.map(({label, value}) => (
              <Menu.CheckboxItem
                key={value}
                checked={selectedFilters.includes(value)}
                onCheckedChange={(checked) => onCheckedChange(value, checked)}
                value={value}
              >
                <Menu.CheckboxItemControl />
                <Menu.ItemLabel>{label}</Menu.ItemLabel>
              </Menu.CheckboxItem>
            ))}
          </Menu.Content>
          <Menu.Footer>
            <Button
              emphasis="neutral"
              onClick={() => setOpen(false)}
              type="button"
              variant="fill"
            >
              Apply Filters
            </Button>
          </Menu.Footer>
          {/* preview */}
        </Menu.Positioner>
      </Portal>
    </Menu.Root>
  )
}

export function MenuHeaderFooterDemo(): ReactElement {
  return (
    <div className="flex items-center gap-4">
      <FilterMenu label="Small menu" size="sm" />
      <FilterMenu label="Medium menu" size="md" />
    </div>
  )
}
