// packages/docs/angular-docs/src/routes/components+/menu+/demos/menu-split-button-demo.ts
import {Component} from "@angular/core"
import {Download, FileArchive, FileJson, FileText} from "lucide-angular"

import {provideIcons} from "@qualcomm-ui/angular-core/lucide"
import {PortalDirective} from "@qualcomm-ui/angular-core/portal"
import {MenuModule} from "@qualcomm-ui/angular/menu"

@Component({
  imports: [MenuModule, PortalDirective],
  providers: [provideIcons({Download, FileArchive, FileJson, FileText})],
  selector: "menu-split-button-demo",
  template: `
    <q-menu [positioning]="{placement: 'bottom-end'}">
      <div
        aria-label="Download"
        emphasis="primary"
        q-menu-split-button
        startIcon="Download"
        (actionClicked)="onDownload()"
      >
        Download
      </div>
      <ng-container *qPortal>
        <div q-menu-positioner>
          <div q-menu-content>
            <button q-menu-item value="pdf">
              <div icon="FileText" q-menu-item-start-icon></div>
              Download as PDF
            </button>
            <button q-menu-item value="json">
              <div icon="FileJson" q-menu-item-start-icon></div>
              Download as JSON
            </button>
            <button q-menu-item value="zip">
              <div icon="FileArchive" q-menu-item-start-icon></div>
              Download as ZIP
            </button>
          </div>
        </div>
      </ng-container>
    </q-menu>
  `,
})
export class MenuSplitButtonDemo {
  onDownload() {
    console.log("Download")
  }
}

// packages/docs/react-docs/src/routes/components+/menu+/demos/menu-split-button-demo.tsx
import type {ReactElement} from "react"

import {Download, FileArchive, FileJson, FileText} from "lucide-react"

import {Portal} from "@qualcomm-ui/react-core/portal"
import {Menu} from "@qualcomm-ui/react/menu"

export function MenuSplitButtonDemo(): ReactElement {
  return (
    <Menu.Root positioning={{placement: "bottom-end"}}>
      <Menu.SplitButton
        aria-label="Download"
        emphasis="primary"
        onClick={() => console.log("Download")}
        startIcon={Download}
        triggerProps={{"aria-label": "More download options"}}
      >
        Download
      </Menu.SplitButton>
      <Portal>
        <Menu.Positioner>
          <Menu.Content>
            <Menu.Item value="pdf">
              <Menu.ItemStartIcon icon={FileText} />
              Download as PDF
            </Menu.Item>
            <Menu.Item value="json">
              <Menu.ItemStartIcon icon={FileJson} />
              Download as JSON
            </Menu.Item>
            <Menu.Item value="zip">
              <Menu.ItemStartIcon icon={FileArchive} />
              Download as ZIP
            </Menu.Item>
          </Menu.Content>
        </Menu.Positioner>
      </Portal>
    </Menu.Root>
  )
}
