// packages/frameworks/react/src/number-input/number-input-unit-select.tsx
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import type {ReactElement} from "react"

import {ChevronDown, ChevronUp} from "lucide-react"

import {Icon} from "@qualcomm-ui/react/icon"
import {Menu} from "@qualcomm-ui/react/menu"
import {useMenuContext} from "@qualcomm-ui/react-core/menu"
import {useNumberInputContext} from "@qualcomm-ui/react-core/number-input"
import {Portal} from "@qualcomm-ui/react-core/portal"
import type {IdProp} from "@qualcomm-ui/react-core/system"
import {mergeProps} from "@qualcomm-ui/utils/merge-props"

import {useQdsNumberInputContext} from "./qds-number-input-context"

export interface NumberInputUnitSelectProps extends IdProp {}

function NumberInputUnitSelectTriggerContent(): ReactElement {
  const menuContext = useMenuContext()

  return (
    <Icon
      data-number-input-part="chevron"
      icon={menuContext.open ? ChevronUp : ChevronDown}
      size="sm"
    />
  )
}

export function NumberInputUnitSelect({
  id,
}: NumberInputUnitSelectProps): ReactElement {
  const numberInputContext = useNumberInputContext()
  const qdsNumberInputContext = useQdsNumberInputContext()

  const unitOptions = numberInputContext.unitOptions ?? []
  const selectedValue = numberInputContext.unit

  const menuSize =
    qdsNumberInputContext.size === "lg" ? "md" : qdsNumberInputContext.size
  const selectedOption = unitOptions.find((opt) => opt.value === selectedValue)
  const displayLabel = selectedOption?.label ?? ""

  const buttonBindings = mergeProps(
    numberInputContext.getUnitSelectBindings(),
    qdsNumberInputContext.getUnitSelectBindings(),
  )

  const handleValueChange = (newValue: string) => {
    numberInputContext.setUnit(newValue)
  }

  return (
    <Menu.Root size={menuSize}>
      <Menu.Trigger>
        <button id={id} {...buttonBindings}>
          <span>{displayLabel}</span>
          <NumberInputUnitSelectTriggerContent />
        </button>
      </Menu.Trigger>
      <Portal>
        <Menu.Positioner>
          <Menu.Content>
            <Menu.RadioItemGroup
              onValueChange={handleValueChange}
              value={selectedValue}
            >
              {unitOptions.map((option) => (
                <Menu.RadioItem key={option.value} value={option.value}>
                  <Menu.ItemLabel>
                    {option.displayText ?? option.label}
                  </Menu.ItemLabel>
                  <Menu.ItemIndicator />
                </Menu.RadioItem>
              ))}
            </Menu.RadioItemGroup>
          </Menu.Content>
        </Menu.Positioner>
      </Portal>
    </Menu.Root>
  )
}

// packages/frameworks/angular/src/number-input/number-input-unit-select.component.ts
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import {Component, computed, inject, type OnInit} from "@angular/core"
import {ChevronDown, ChevronUp} from "lucide-angular"

import {provideIcons} from "@qualcomm-ui/angular-core/lucide"
import {normalizeProps} from "@qualcomm-ui/angular-core/machine"
import {
  CoreMenuRootDirective,
  provideMenuContext,
  provideMenuMachineContext,
  provideMenuTriggerContext,
  useMenuContext,
} from "@qualcomm-ui/angular-core/menu"
import {useNumberInputContext} from "@qualcomm-ui/angular-core/number-input"
import {providePresenceContext} from "@qualcomm-ui/angular-core/presence"
import {
  provideQdsMenuContext,
  QdsMenuContextService,
} from "@qualcomm-ui/angular/menu"
import {createQdsMenuApi} from "@qualcomm-ui/qds-core/menu"

import {useQdsNumberInputContext} from "./qds-number-input-context.service"

@Component({
  providers: [
    provideMenuContext(),
    provideMenuTriggerContext(),
    provideMenuMachineContext(),
    providePresenceContext(),
    provideQdsMenuContext(),
    provideIcons({ChevronDown, ChevronUp}),
  ],
  selector: "q-number-input-unit-select",
  standalone: false,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  template: `
    <button q-menu-trigger [q-bind]="unitSelectBindings()">
      <span>{{ selectedLabel() }}</span>
      <svg
        data-number-input-part="chevron"
        size="sm"
        [qIcon]="menuContext().open ? 'ChevronUp' : 'ChevronDown'"
      ></svg>
    </button>
    <ng-template qPortal>
      <div q-menu-positioner>
        <div q-menu-content>
          <div
            q-menu-radio-item-group
            [value]="numberInputContext().unit"
            (valueChange)="onUnitChange($event)"
          >
            @for (
              option of numberInputContext().unitOptions ?? [];
              track option.value
            ) {
              <button q-menu-radio-item [value]="option.value">
                <span q-menu-item-label>
                  {{ option.displayText ?? option.label }}
                </span>
                <span q-menu-item-indicator></span>
              </button>
            }
          </div>
        </div>
      </div>
    </ng-template>
  `,
})
export class NumberInputUnitSelectComponent
  extends CoreMenuRootDirective
  implements OnInit
{
  protected readonly numberInputContext = useNumberInputContext()
  protected readonly qdsNumberInputContext = useQdsNumberInputContext()
  protected readonly qdsMenuService = inject(QdsMenuContextService)
  protected readonly menuContext = useMenuContext()

  protected readonly unitSelectBindings = computed(() => ({
    ...this.numberInputContext().getUnitSelectBindings(),
    ...this.qdsNumberInputContext().getUnitSelectBindings(),
  }))

  protected readonly selectedLabel = computed(() => {
    const currentValue = this.numberInputContext().unit
    const opts = this.numberInputContext().unitOptions
    const selected = opts?.find((opt) => opt.value === currentValue)
    return selected?.label ?? ""
  })

  protected onUnitChange(value: string | undefined): void {
    if (value) {
      this.numberInputContext().setUnit(value)
    }
  }

  override ngOnInit() {
    super.ngOnInit()

    const qdsMenuApi = computed(() => {
      const inputSize = this.qdsNumberInputContext().size
      const menuSize = inputSize === "lg" ? "md" : inputSize
      return createQdsMenuApi({size: menuSize}, normalizeProps)
    })

    this.qdsMenuService.init(qdsMenuApi)
  }
}
