// packages/docs/react-docs/src/routes/components+/avatar+/demos/avatar-explorer-demo.tsx
import type {ReactElement} from "react"

import {Avatar} from "@qualcomm-ui/react/avatar"

export function AvatarExplorerDemo(): ReactElement {
  return (
    <Avatar.Root status="active">
      <Avatar.Image alt="John Doe" src="/images/avatar-man.png" />
      <Avatar.Status />
    </Avatar.Root>
  )
}

// packages/docs/angular-docs/src/routes/components+/avatar+/demos/avatar-explorer-demo.ts
import {Component} from "@angular/core"

import {AvatarModule} from "@qualcomm-ui/angular/avatar"

@Component({
  imports: [AvatarModule],
  selector: "avatar-explorer-demo",
  template: `
    <!-- preview -->
    <div q-avatar status="active">
      <img alt="John Doe" q-avatar-image src="/images/avatar-man.png" />
      <div q-avatar-status></div>
    </div>
    <!-- preview -->
  `,
})
export class AvatarExplorerDemo {}
