// packages/frameworks/react/src/switch/switch.tsx
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import type {ReactElement, ReactNode} from "react"

import {useOptionalContentId} from "@qualcomm-ui/react-core/machine"
import {useControlledId} from "@qualcomm-ui/react-core/state"

import {SwitchControl, type SwitchControlProps} from "./switch-control"
import {SwitchErrorText, type SwitchErrorTextProps} from "./switch-error-text"
import {
  SwitchHiddenInput,
  type SwitchHiddenInputProps,
} from "./switch-hidden-input"
import {SwitchLabel, type SwitchLabelProps} from "./switch-label"
import {SwitchRoot, type SwitchRootProps} from "./switch-root"
import {SwitchThumb, type SwitchThumbProps} from "./switch-thumb"

export interface SwitchProps extends SwitchRootProps {
  /**
   * The simple Switch doesn't support children.
   */
  children?: never

  /**
   * Props applied to the control element.
   */
  controlProps?: SwitchControlProps

  /**
   * Optional error that describes the element when {@link invalid} is true.
   */
  errorText?: string

  /**
   * Props applied to the error text element.
   */
  errorTextProps?: SwitchErrorTextProps

  /**
   * Props applied to the hidden input element.
   */
  hiddenInputProps?: SwitchHiddenInputProps

  /**
   * Optional label describing the element. Recommended. This element is
   * automatically associated with the component's input element for
   * accessibility.
   */
  label?: ReactNode

  /**
   * Props applied to the label element.
   */
  labelProps?: SwitchLabelProps

  /**
   * Props applied to the thumb element.
   */
  thumbProps?: SwitchThumbProps
}

export function Switch({
  controlProps,
  errorText,
  errorTextProps,
  hiddenInputProps,
  label,
  labelProps,
  thumbProps,
  ...props
}: SwitchProps): ReactElement {
  const labelContent = label || labelProps?.children
  const errorTextContent = errorText || errorTextProps?.children

  const ids = {
    errorText: useOptionalContentId(errorTextContent, errorTextProps),
    hiddenInput: useControlledId(hiddenInputProps?.id),
    label: useOptionalContentId(labelContent, labelProps),
    root: useControlledId(props.id),
    ...props.ids,
  }

  return (
    <SwitchRoot {...props} ids={ids}>
      <SwitchHiddenInput {...hiddenInputProps} id={ids.hiddenInput} />
      <SwitchControl {...controlProps}>
        <SwitchThumb {...thumbProps} />
      </SwitchControl>
      {labelContent ? (
        <SwitchLabel {...labelProps} id={ids.label}>
          {labelContent}
        </SwitchLabel>
      ) : null}
      {errorTextContent ? (
        <SwitchErrorText {...errorTextProps} id={ids.errorText}>
          {errorTextContent}
        </SwitchErrorText>
      ) : null}
    </SwitchRoot>
  )
}

// packages/frameworks/angular/src/switch/switch.component.ts
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import {Component, input} from "@angular/core"

import {provideSwitchContext} from "@qualcomm-ui/angular-core/switch"

import {provideQdsSwitchContext} from "./qds-switch-context.service"
import {SwitchRootDirective} from "./switch-root.directive"

@Component({
  providers: [provideSwitchContext(), provideQdsSwitchContext()],
  selector: "[q-switch]",
  standalone: false,
  template: `
    <ng-content select="[q-switch-hidden-input]">
      <input q-switch-hidden-input />
    </ng-content>
    <ng-content select="[q-switch-control]">
      <div q-switch-control>
        <div q-switch-thumb></div>
      </div>
    </ng-content>
    <ng-content select="[q-switch-label]">
      @if (label()) {
        <span q-switch-label>
          {{ label() }}
        </span>
      }
    </ng-content>
    <ng-content select="[q-switch-error-text]">
      @if (errorText()) {
        <div q-switch-error-text>
          {{ errorText() }}
        </div>
      }
    </ng-content>
  `,
})
export class SwitchComponent extends SwitchRootDirective {
  /**
   * Optional error that describes the switch when the field is invalid. This
   * element is automatically associated with the switch for accessibility.
   *
   * @remarks
   * To customize the element, provide it using the directive instead:
   *
   * ```angular-html
   * <label q-switch>
   *   <div q-switch-error-text>...</div>
   * </label>
   * ```
   */
  readonly errorText = input<string>()

  /**
   * Optional label describing the element. Recommended. This element is
   * automatically associated with the component's input element for accessibility.
   *
   * @remarks
   * To customize the element, provide it using the directive instead:
   *
   * ```angular-html
   * <label q-switch>
   *   <div q-switch-label>...</div>
   * </label>
   * ```
   */
  readonly label = input<string>()
}
