// packages/docs/react-docs/src/routes/components+/slider+/demos/slider-markers-demo.tsx
import type {ReactElement} from "react"

import {Slider} from "@qualcomm-ui/react/slider"

export function SliderMarkersDemo(): ReactElement {
  return (
    // preview
    <Slider
      className="sm:w-80"
      defaultValue={[30]}
      marks={[20, 30, 40, 50, 60, 70]}
      max={70}
      min={20}
    />
    // preview
  )
}

// packages/docs/angular-docs/src/routes/components+/slider+/demos/slider-markers-demo.ts
import {Component} from "@angular/core"

import {SliderModule} from "@qualcomm-ui/angular/slider"

@Component({
  imports: [SliderModule],
  selector: "slider-markers-demo",
  template: `
    <!-- preview -->
    <q-slider
      class="sm:w-80"
      [defaultValue]="[30]"
      [marks]="[20, 30, 40, 50, 60, 70]"
      [max]="70"
      [min]="20"
    />
    <!-- preview -->
  `,
})
export class SliderMarkersDemo {}
