// packages/docs/react-docs/src/routes/components+/slider+/demos/slider-value-callback-demo.tsx
import {type ReactElement, useState} from "react"

import {Slider} from "@qualcomm-ui/react/slider"

export function SliderValueCallbackDemo(): ReactElement {
  const [value, setValue] = useState<number[]>([25, 75])
  const [finalValue, setFinalValue] = useState<number[]>(value)
  return (
    <div className="sm:w-[340px]">
      {/* preview */}
      <Slider
        onValueChange={(e) => {
          setValue(e.value)
        }}
        onValueChangeEnd={(e) => {
          setFinalValue(e.value)
        }}
        value={value}
      />
      {/* preview */}
      <output className="mt-4 block">
        live value: <strong>{value.join(", ")}</strong>
      </output>
      <output className="mt-4 block">
        final value: <strong>{finalValue.join(", ")}</strong>
      </output>
    </div>
  )
}

// packages/docs/angular-docs/src/routes/components+/slider+/demos/slider-value-callback-demo.ts
import {Component} from "@angular/core"

import {SliderModule} from "@qualcomm-ui/angular/slider"
import type {ValueChangeDetails} from "@qualcomm-ui/core/slider"

@Component({
  imports: [SliderModule],
  selector: "slider-value-callback-demo",
  template: `
    <!-- preview -->
    <div class="sm:w-80">
      <q-slider
        [defaultValue]="value"
        (valueChanged)="onValueChange($event)"
        (valueChangedEnd)="onValueChangeEnd($event)"
      />
      <output class="mt-4 block">
        live value:
        <strong>{{ value.join(", ") }}</strong>
      </output>
      <output class="mt-4 block">
        final value:
        <strong>{{ finalValue.join(", ") }}</strong>
      </output>
    </div>
    <!-- preview -->
  `,
})
export class SliderValueCallbackDemo {
  value = [25, 75]
  finalValue = [25, 75]

  onValueChange(details: ValueChangeDetails) {
    this.value = details.value
  }

  onValueChangeEnd(details: ValueChangeDetails) {
    this.finalValue = details.value
  }
}
