// packages/docs/react-docs/src/routes/components+/breadcrumbs+/demos/breadcrumbs-max-items-demo.tsx
import type {ReactElement} from "react"

import {Home} from "lucide-react"
import {Link} from "react-router"

import {
  Breadcrumbs,
  type BreadcrumbsItemData,
} from "@qualcomm-ui/react/breadcrumbs"

// preview
const items: BreadcrumbsItemData[] = [
  {icon: Home, label: "Home", link: <Link to="/" />},
  {label: "Settings", link: <Link to="/settings" />},
  {label: "Account", link: <Link to="/settings/account" />},
  {label: "Security", link: <Link to="/settings/account/security" />},
  {label: "Sessions"},
]

export function BreadcrumbsMaxItemsDemo(): ReactElement {
  return (
    <Breadcrumbs.Root aria-label="Breadcrumbs">
      <Breadcrumbs.List items={items} maxItems={3} />
    </Breadcrumbs.Root>
  )
}
// preview

// packages/docs/angular-docs/src/routes/components+/breadcrumbs+/demos/breadcrumbs-max-items-demo.ts
import {Component} from "@angular/core"
import {Home} from "lucide-angular"

import {
  type BreadcrumbsItemData,
  BreadcrumbsModule,
} from "@qualcomm-ui/angular/breadcrumbs"
import {provideIcons} from "@qualcomm-ui/angular-core/lucide"

// preview
@Component({
  imports: [BreadcrumbsModule],
  providers: [provideIcons({Home})],
  selector: "breadcrumbs-max-items-demo",
  template: `
    <nav aria-label="Breadcrumbs" q-breadcrumbs-root>
      <ol q-breadcrumbs-list [items]="items" [maxItems]="3"></ol>
    </nav>
  `,
})
export class BreadcrumbsMaxItemsDemo {
  readonly items: BreadcrumbsItemData[] = [
    {icon: "Home", label: "Home", link: "/"},
    {label: "Settings", link: "/settings"},
    {label: "Account", link: "/settings/account"},
    {label: "Security", link: "/settings/account/security"},
    {label: "Sessions"},
  ]
}
// preview
