// packages/docs/react-docs/src/routes/components+/breadcrumbs+/demos/breadcrumbs-tooltip-demo.tsx
import type {ReactElement} from "react"

import {Home} from "lucide-react"

import {Breadcrumbs} from "@qualcomm-ui/react/breadcrumbs"

export function BreadcrumbsTooltipDemo(): ReactElement {
  return (
    <Breadcrumbs.Root aria-label="Breadcrumbs" className="mt-4">
      <Breadcrumbs.List>
        <Breadcrumbs.Item icon={Home} tooltip="Navigate to home page">
          Home
        </Breadcrumbs.Item>
        {/* preview */}
        <Breadcrumbs.Item tooltip="View all components">
          Components
        </Breadcrumbs.Item>
        {/* preview */}
        <Breadcrumbs.Item aria-current="page">Breadcrumbs</Breadcrumbs.Item>
      </Breadcrumbs.List>
    </Breadcrumbs.Root>
  )
}

// packages/docs/angular-docs/src/routes/components+/breadcrumbs+/demos/breadcrumbs-tooltip-demo.ts
import {Component} from "@angular/core"

import {BreadcrumbsModule} from "@qualcomm-ui/angular/breadcrumbs"

@Component({
  imports: [BreadcrumbsModule],
  selector: "breadcrumbs-tooltip-demo",
  template: `
    <!-- preview -->
    <nav aria-label="Breadcrumbs" class="mt-4" q-breadcrumbs-root>
      <ol q-breadcrumbs-list>
        <li q-breadcrumb-item tooltip="Navigate to home page">Home</li>
        <li q-breadcrumb-item tooltip="View all components">Components</li>
        <li aria-current="page" q-breadcrumb-item>Breadcrumbs</li>
      </ol>
    </nav>
    <!-- preview -->
  `,
})
export class BreadcrumbsTooltipDemo {}
