// packages/docs/angular-docs/src/routes/components+/tabs+/demos/tabs-context-demo.ts
import {Component} from "@angular/core"
import {ChevronLeft, ChevronRight} from "lucide-angular"

import {ButtonModule} from "@qualcomm-ui/angular/button"
import {TabsModule} from "@qualcomm-ui/angular/tabs"
import {provideIcons} from "@qualcomm-ui/angular-core/lucide"

@Component({
  imports: [TabsModule, ButtonModule],
  providers: [provideIcons({ChevronLeft, ChevronRight})],
  selector: "tabs-context-demo",
  template: `
    <div class="w-full" defaultValue="tab-1" q-tabs-root>
      <div q-tabs-list>
        <div q-tabs-indicator></div>
        <div q-tab-root value="tab-1">
          <button q-tab-button>Tab 1</button>
        </div>
        <div q-tab-root value="tab-2">
          <button q-tab-button>Tab 2</button>
        </div>
        <div q-tab-root value="tab-3">
          <button q-tab-button>Tab 3</button>
        </div>
      </div>
      <!-- preview -->
      <ng-container *tabsContext="let tabsApi">
        <div q-tabs-panel value="tab-1">
          <button
            endIcon="ChevronRight"
            q-button
            size="sm"
            variant="outline"
            (click)="tabsApi.setValue('tab-2')"
          >
            Go to next tab
          </button>
        </div>
        <div class="flex items-center gap-2" q-tabs-panel value="tab-2">
          <button
            q-button
            size="sm"
            startIcon="ChevronLeft"
            variant="outline"
            (click)="tabsApi.setValue('tab-1')"
          >
            Go to prev tab
          </button>
          <button
            endIcon="ChevronRight"
            q-button
            size="sm"
            variant="outline"
            (click)="tabsApi.setValue('tab-3')"
          >
            Go to next tab
          </button>
        </div>
        <div q-tabs-panel value="tab-3">
          <button
            q-button
            size="sm"
            startIcon="ChevronLeft"
            variant="outline"
            (click)="tabsApi.setValue('tab-2')"
          >
            Go to previous tab
          </button>
        </div>
      </ng-container>

      <!-- preview -->
    </div>
  `,
})
export class TabsContextDemo {}

// packages/docs/react-docs/src/routes/components+/tabs+/demos/tabs-context-demo.tsx
import type {ReactElement} from "react"

import {ChevronLeft, ChevronRight} from "lucide-react"

import {Button} from "@qualcomm-ui/react/button"
import {Tab, Tabs} from "@qualcomm-ui/react/tabs"

export default function TabsContextDemo(): ReactElement {
  return (
    <Tabs.Root className="w-full" defaultValue="tab-1">
      <Tabs.List>
        <Tabs.Indicator />
        <Tab.Root value="tab-1">
          <Tab.Button>Tab 1</Tab.Button>
        </Tab.Root>
        <Tab.Root value="tab-2">
          <Tab.Button>Tab 2</Tab.Button>
        </Tab.Root>
        <Tab.Root value="tab-3">
          <Tab.Button>Tab 3</Tab.Button>
        </Tab.Root>
      </Tabs.List>
      {/* preview */}
      <Tabs.Context>
        {(context) => (
          <>
            <Tabs.Panel value="tab-1">
              <Button
                endIcon={ChevronRight}
                onClick={() => context.setValue("tab-2")}
                size="sm"
                variant="outline"
              >
                Go to next tab
              </Button>
            </Tabs.Panel>
            <Tabs.Panel className="flex items-center gap-2" value="tab-2">
              <Button
                onClick={() => context.setValue("tab-1")}
                size="sm"
                startIcon={ChevronLeft}
                variant="outline"
              >
                Go to prev tab
              </Button>
              <Button
                endIcon={ChevronRight}
                onClick={() => context.setValue("tab-3")}
                size="sm"
                variant="outline"
              >
                Go to next tab
              </Button>
            </Tabs.Panel>
            <Tabs.Panel value="tab-3">
              <Button
                onClick={() => context.setValue("tab-2")}
                size="sm"
                startIcon={ChevronLeft}
                variant="outline"
              >
                Go to previous tab
              </Button>
            </Tabs.Panel>
          </>
        )}
      </Tabs.Context>
      {/* preview */}
    </Tabs.Root>
  )
}
