// packages/docs/angular-docs/src/routes/components+/radio+/demos/radio-simple-demo.ts
import {Component} from "@angular/core"

import {RadioModule} from "@qualcomm-ui/angular/radio"

@Component({
  imports: [RadioModule],
  selector: "radio-simple-demo",
  template: `
    <form>
      <!-- preview -->
      <fieldset defaultValue="html" name="language" q-radio-group>
        <div q-radio-group-label>Language</div>
        <div q-radio-group-items>
          <label label="HTML" q-radio value="html"></label>
          <label label="CSS" q-radio value="css"></label>
          <label label="TypeScript" q-radio value="ts"></label>
        </div>
      </fieldset>
      <!-- preview -->
    </form>
  `,
})
export class RadioSimpleDemo {}

// packages/docs/react-docs/src/routes/components+/radio+/demos/radio-simple-demo.tsx
import type {ReactElement} from "react"

import {Radio, RadioGroup} from "@qualcomm-ui/react/radio"

export default function RadioSimpleDemo(): ReactElement {
  return (
    <form>
      {/* preview */}
      <RadioGroup.Root defaultValue="html">
        <RadioGroup.Label>Language</RadioGroup.Label>
        <RadioGroup.Items>
          <Radio label="HTML" value="html" />
          <Radio label="CSS" value="css" />
          <Radio label="TypeScript" value="ts" />
        </RadioGroup.Items>
      </RadioGroup.Root>
      {/* preview */}
    </form>
  )
}
