// packages/docs/angular-docs/src/routes/components+/radio+/demos/radio-orientation-demo.ts
import {Component} from "@angular/core"
import {FormsModule} from "@angular/forms"

import {RadioModule} from "@qualcomm-ui/angular/radio"

@Component({
  imports: [RadioModule, FormsModule],
  selector: "radio-orientation-demo",
  template: `
    <form>
      <!-- preview -->
      <fieldset name="language" orientation="horizontal" q-radio-group>
        <div q-radio-group-label>Language</div>
        <div q-radio-group-items>
          <label label="HTML" q-radio value="html"></label>
          <label label="CSS" q-radio value="css"></label>
          <label label="TypeScript" q-radio value="ts"></label>
        </div>
        <div q-radio-group-error-text>You must select a value</div>
      </fieldset>
      <!-- preview -->
    </form>
  `,
})
export class RadioOrientationDemo {}

// packages/docs/react-docs/src/routes/components+/radio+/demos/radio-orientation-demo.tsx
import type {ReactElement} from "react"

import {Radio, RadioGroup} from "@qualcomm-ui/react/radio"

export default function RadioOrientationDemo(): ReactElement {
  return (
    <form>
      {/* preview */}
      <RadioGroup.Root
        defaultValue="html"
        name="language"
        orientation="horizontal"
      >
        <RadioGroup.Label>Language</RadioGroup.Label>
        <RadioGroup.Items>
          <Radio label="HTML" value="html" />
          <Radio label="CSS" value="css" />
          <Radio label="TypeScript" value="ts" />
        </RadioGroup.Items>
      </RadioGroup.Root>
      {/* preview */}
    </form>
  )
}
