// packages/debug-apps/angular-ssr/src/app/components/password-input.ts
import {Component} from "@angular/core"

import {PasswordInputChildDirectivesDemo} from "@qualcomm-ui/angular-docs/components+/password-input+/demos/password-input-child-directives-demo"
import {PasswordInputCompositeDemo} from "@qualcomm-ui/angular-docs/components+/password-input+/demos/password-input-composite-demo"
import {PasswordInputControlledVisibilityDemo} from "@qualcomm-ui/angular-docs/components+/password-input+/demos/password-input-controlled-visibility-demo"
import {PasswordInputErrorTextDemo} from "@qualcomm-ui/angular-docs/components+/password-input+/demos/password-input-error-text-demo"
import {PasswordInputReactiveFormStatesDemo} from "@qualcomm-ui/angular-docs/components+/password-input+/demos/password-input-reactive-form-states-demo"
import {PasswordInputReactiveFormsDemo} from "@qualcomm-ui/angular-docs/components+/password-input+/demos/password-input-reactive-forms-demo"
import {PasswordInputRequiredTemplateFormsDemo} from "@qualcomm-ui/angular-docs/components+/password-input+/demos/password-input-required-template-forms-demo"
import {PasswordInputSimpleDemo} from "@qualcomm-ui/angular-docs/components+/password-input+/demos/password-input-simple-demo"
import {PasswordInputSimpleIconsDemo} from "@qualcomm-ui/angular-docs/components+/password-input+/demos/password-input-simple-icons-demo"
import {PasswordInputTemplateFormsDemo} from "@qualcomm-ui/angular-docs/components+/password-input+/demos/password-input-template-forms-demo"

@Component({
  imports: [
    PasswordInputChildDirectivesDemo,
    PasswordInputCompositeDemo,
    PasswordInputControlledVisibilityDemo,
    PasswordInputErrorTextDemo,
    PasswordInputReactiveFormStatesDemo,
    PasswordInputReactiveFormsDemo,
    PasswordInputRequiredTemplateFormsDemo,
    PasswordInputSimpleDemo,
    PasswordInputSimpleIconsDemo,
    PasswordInputTemplateFormsDemo,
  ],
  template: `
    <div
      class="container"
      style="max-width: 1200px; margin: 0 auto; padding: 2rem;"
    >
      <div class="section">
        <h2 class="section-title">Child Directives</h2>
        <div class="demo-container">
          <password-input-child-directives-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Composite</h2>
        <div class="demo-container">
          <password-input-composite-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Controlled Visibility</h2>
        <div class="demo-container">
          <password-input-controlled-visibility-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Error Text</h2>
        <div class="demo-container">
          <password-input-error-text-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Reactive Form States</h2>
        <div class="demo-container">
          <password-input-reactive-form-states-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Reactive Forms</h2>
        <div class="demo-container">
          <password-input-reactive-forms-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Required Template Forms</h2>
        <div class="demo-container">
          <password-input-required-template-forms-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Simple</h2>
        <div class="demo-container">
          <password-input-simple-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Simple Icons</h2>
        <div class="demo-container">
          <password-input-simple-icons-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Template Forms</h2>
        <div class="demo-container">
          <password-input-template-forms-demo />
        </div>
      </div>
    </div>
  `,
})
export class PasswordInputPage {}

// packages/debug-apps/react-ssr/src/routes/components+/password-input+/_password-input.tsx
import CompositeDemo from "@qualcomm-ui/react-docs/components+/password-input+/demos/password-input-composite-demo"
import ControlledValueDemo from "@qualcomm-ui/react-docs/components+/password-input+/demos/password-input-controlled-value-demo"
import ControlledVisibilityDemo from "@qualcomm-ui/react-docs/components+/password-input+/demos/password-input-controlled-visibility-demo"
import IconsDemo from "@qualcomm-ui/react-docs/components+/password-input+/demos/password-input-icons-demo"
import ReactHookFormDemo from "@qualcomm-ui/react-docs/components+/password-input+/demos/password-input-react-hook-form-demo"
import SimpleDemo from "@qualcomm-ui/react-docs/components+/password-input+/demos/password-input-simple-demo"
import TanstackFormDemo from "@qualcomm-ui/react-docs/components+/password-input+/demos/password-input-tanstack-form-demo"

const demos = [
  {component: CompositeDemo, title: "Composite"},
  {component: ControlledValueDemo, title: "Controlled Value"},
  {component: ControlledVisibilityDemo, title: "Controlled Visibility"},
  {component: IconsDemo, title: "Icons"},
  {component: ReactHookFormDemo, title: "React Hook Form"},
  {component: SimpleDemo, title: "Simple"},
  {component: TanstackFormDemo, title: "Tanstack Form"},
]

export default function PasswordInputDemos() {
  return (
    <div className="page">
      {demos.map(({component: Demo, title}) => (
        <div className="section" key={title}>
          <h2 className="section-title">{title}</h2>
          <div className="demo-container">
            <Demo />
          </div>
        </div>
      ))}
    </div>
  )
}
