// packages/docs/angular-docs/src/routes/components+/alert-banner+/demos/alert-banner-variant-demo.ts
import {Component} from "@angular/core"

import {AlertBannerModule} from "@qualcomm-ui/angular/alert-banner"

@Component({
  imports: [AlertBannerModule],
  selector: "alert-banner-variant-demo",
  template: `
    <div class="grid w-full gap-4">
      <!-- preview -->
      <div emphasis="info" heading="info" q-alert-banner variant="subtle">
        <button q-alert-banner-button>Action</button>
      </div>
      <div emphasis="success" heading="success" q-alert-banner variant="subtle">
        <button q-alert-banner-button>Action</button>
      </div>
      <div emphasis="warning" heading="warning" q-alert-banner variant="subtle">
        <button q-alert-banner-button>Action</button>
      </div>
      <div emphasis="danger" heading="danger" q-alert-banner variant="subtle">
        <button q-alert-banner-button>Action</button>
      </div>
      <div emphasis="neutral" heading="neutral" q-alert-banner variant="subtle">
        <button q-alert-banner-button>Action</button>
      </div>
      <!-- preview -->
    </div>
  `,
})
export class AlertBannerVariantDemo {}

// packages/docs/react-docs/src/routes/components+/alert-banner+/demos/alert-banner-variant-demo.tsx
import type {ReactElement} from "react"

import {AlertBanner} from "@qualcomm-ui/react/alert-banner"

export function AlertBannerVariantDemo(): ReactElement {
  return (
    <div className="grid w-full gap-4">
      {/* preview */}
      <AlertBanner
        action={<AlertBanner.Button>Action</AlertBanner.Button>}
        description="Description"
        emphasis="info"
        heading="info"
        variant="subtle"
      />
      {/* preview */}
      <AlertBanner
        action={<AlertBanner.Button>Action</AlertBanner.Button>}
        description="Description"
        emphasis="success"
        heading="success"
        variant="subtle"
      />
      <AlertBanner
        action={<AlertBanner.Button>Action</AlertBanner.Button>}
        description="Description"
        emphasis="warning"
        heading="warning"
        variant="subtle"
      />
      <AlertBanner
        action={<AlertBanner.Button>Action</AlertBanner.Button>}
        description="Description"
        emphasis="danger"
        heading="danger"
        variant="subtle"
      />
      <AlertBanner
        action={<AlertBanner.Button>Action</AlertBanner.Button>}
        description="Description"
        emphasis="neutral"
        heading="neutral"
        variant="subtle"
      />
    </div>
  )
}
