// packages/docs/react-docs/src/routes/components+/badges+/number-badge+/demos/number-badge-size-demo.tsx
import type {ReactElement} from "react"

import {NumberBadge} from "@qualcomm-ui/react/badge"

export function NumberBadgeSizeDemo(): ReactElement {
  return (
    <div className="flex flex-wrap items-center gap-4">
      {/* preview */}
      <NumberBadge size="sm" value={5} />
      <NumberBadge size="md" value={5} />
      <NumberBadge size="lg" value={5} />
      {/* preview */}
    </div>
  )
}

// packages/docs/angular-docs/src/routes/components+/badges+/number-badge+/demos/number-badge-size-demo.ts
import {Component} from "@angular/core"

import {NumberBadgeDirective} from "@qualcomm-ui/angular/badge"

@Component({
  imports: [NumberBadgeDirective],
  selector: "number-badge-size-demo",
  template: `
    <div class="flex flex-wrap items-center gap-4">
      <!-- preview -->
      <span q-number-badge size="xs" [value]="5"></span>
      <span q-number-badge size="sm" [value]="5"></span>
      <span q-number-badge size="md" [value]="5"></span>
      <span q-number-badge size="lg" [value]="5"></span>
      <!-- preview -->
    </div>
  `,
})
export class NumberBadgeSizeDemo {}
