// packages/docs/react-docs/src/routes/components+/badges+/number-badge+/demos/number-badge-emphasis-demo.tsx
import type {ReactElement} from "react"

import {NumberBadge} from "@qualcomm-ui/react/badge"

export function NumberBadgeEmphasisDemo(): ReactElement {
  return (
    <div className="flex flex-wrap items-center gap-4">
      {/* preview */}
      <NumberBadge emphasis="neutral" value={5} />
      <NumberBadge emphasis="neutral-outline" value={5} />
      <NumberBadge emphasis="brand" value={5} />
      <NumberBadge emphasis="brand-outline" value={5} />
      <NumberBadge emphasis="info" value={5} />
      <NumberBadge emphasis="success" value={5} />
      <NumberBadge emphasis="warning" value={5} />
      <NumberBadge emphasis="danger" value={5} />
      <NumberBadge emphasis="persistent-black" value={5} />
      <NumberBadge emphasis="persistent-white" value={5} />
      {/* preview */}
    </div>
  )
}

// packages/docs/angular-docs/src/routes/components+/badges+/number-badge+/demos/number-badge-emphasis-demo.ts
import {Component} from "@angular/core"

import {NumberBadgeDirective} from "@qualcomm-ui/angular/badge"

@Component({
  imports: [NumberBadgeDirective],
  selector: "number-badge-variant-demo",
  template: `
    <div class="flex flex-wrap items-center gap-4">
      <!-- preview -->
      <span emphasis="neutral" q-number-badge [value]="5"></span>
      <span emphasis="neutral-outline" q-number-badge [value]="5"></span>
      <span emphasis="brand" q-number-badge [value]="5"></span>
      <span emphasis="brand-outline" q-number-badge [value]="5"></span>
      <span emphasis="info" q-number-badge [value]="5"></span>
      <span emphasis="success" q-number-badge [value]="5"></span>
      <span emphasis="warning" q-number-badge [value]="5"></span>
      <span emphasis="danger" q-number-badge [value]="5"></span>
      <span emphasis="persistent-black" q-number-badge [value]="5"></span>
      <span emphasis="persistent-white" q-number-badge [value]="5"></span>
      <!-- preview -->
    </div>
  `,
})
export class NumberBadgeEmphasisDemo {}
