// packages/docs/angular-docs/src/routes/components+/select+/demos/select-within-popover-demo.ts
import {Component} from "@angular/core"

import {ButtonModule} from "@qualcomm-ui/angular/button"
import {PopoverModule} from "@qualcomm-ui/angular/popover"
import {SelectModule} from "@qualcomm-ui/angular/select"
import {selectCollection} from "@qualcomm-ui/core/select"

@Component({
  imports: [SelectModule, PopoverModule, ButtonModule],
  selector: "select-within-popover-demo",
  template: `
    <!-- preview -->
    <div q-popover>
      <div q-popover-anchor>
        <button q-button q-popover-trigger variant="outline">Click Me</button>
      </div>
      <q-select
        disablePortal
        label="City"
        placeholder="Select a city"
        [collection]="cityCollection"
      />
    </div>
    <!-- preview -->
  `,
})
export class SelectWithinPopoverDemo {
  cityCollection = selectCollection({
    items: [
      "San Diego",
      "Nashville",
      "Denver",
      "Miami",
      "Las Vegas",
      "New York City",
      "San Francisco",
    ],
  })
}

// packages/docs/react-docs/src/routes/components+/select+/demos/select-within-popover-demo.tsx
import type {ReactElement} from "react"

import {selectCollection} from "@qualcomm-ui/core/select"
import {Button} from "@qualcomm-ui/react/button"
import {Popover} from "@qualcomm-ui/react/popover"
import {Select} from "@qualcomm-ui/react/select"

const cityCollection = selectCollection({
  items: [
    "San Diego",
    "Nashville",
    "Denver",
    "Miami",
    "Las Vegas",
    "New York City",
    "San Francisco",
  ],
})

export function SelectWithinPopoverDemo(): ReactElement {
  return (
    <Popover
      label="Select Example"
      trigger={<Button emphasis="primary">Show Popover</Button>}
    >
      <Select
        className="w-48"
        collection={cityCollection}
        label="City"
        placeholder="Select a city"
        portalProps={{disabled: true}}
      />
    </Popover>
  )
}
