// packages/debug-apps/react-ssr/src/routes/components+/button-group.tsx
import {ButtonGroupLayoutDemo as LayoutDemo} from "@qualcomm-ui/react-docs/components+/button-group+/demos/button-group-layout-demo"
import {ButtonGroupSharedPropsDemo as SharedPropsDemo} from "@qualcomm-ui/react-docs/components+/button-group+/demos/button-group-shared-props-demo"

import {DemoPageLayout} from "~/components/demo-page-layout"

const demos = [
  {component: LayoutDemo, title: "Layout"},
  {component: SharedPropsDemo, title: "Shared Props"},
]

export default function ButtonGroupDemos() {
  return <DemoPageLayout componentName="button-group" demos={demos} />
}

// packages/debug-apps/angular-ssr/src/app/components/button-group.ts
import {Component} from "@angular/core"

import {ButtonGroupLayoutDemo} from "@qualcomm-ui/angular-docs/components+/button-group+/demos/button-group-layout-demo"
import {ButtonGroupSharedPropsDemo} from "@qualcomm-ui/angular-docs/components+/button-group+/demos/button-group-shared-props-demo"

@Component({
  imports: [ButtonGroupLayoutDemo, ButtonGroupSharedPropsDemo],
  selector: "app-button-group",
  template: `
    <div class="container">
      <div class="section">
        <h2 class="section-title">Layout</h2>
        <div class="demo-container">
          <button-group-layout-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Shared Props</h2>
        <div class="demo-container">
          <button-group-shared-props-demo />
        </div>
      </div>
    </div>
  `,
})
export class ButtonGroupPage {}
