// packages/docs/angular-docs/src/routes/components+/popover+/demos/popover-explorer-demo.ts
import {Component} from "@angular/core"

import {ButtonModule} from "@qualcomm-ui/angular/button"
import {PopoverModule} from "@qualcomm-ui/angular/popover"

@Component({
  imports: [PopoverModule, ButtonModule],
  selector: "popover-explorer-demo",
  template: `
    <div
      defaultOpen
      description="Popover content with a description."
      disablePortal
      label="Label"
      q-popover
      [positioning]="{placement: 'bottom'}"
    >
      <div q-popover-anchor>
        <button emphasis="primary" q-button q-popover-trigger>
          Show Popover
        </button>
      </div>
    </div>
  `,
})
export class PopoverExplorerDemo {}

// packages/docs/react-docs/src/routes/components+/popover+/demos/popover-explorer-demo.tsx
import type {ReactElement} from "react"

import {Button} from "@qualcomm-ui/react/button"
import {Popover} from "@qualcomm-ui/react/popover"

export function PopoverExplorerDemo(): ReactElement {
  return (
    <Popover.Root
      defaultOpen
      portalled={false}
      positioning={{placement: "bottom"}}
    >
      <Popover.Anchor>
        <Popover.Trigger>
          <Button emphasis="primary">Show Popover</Button>
        </Popover.Trigger>
      </Popover.Anchor>
      <Popover.Positioner>
        <Popover.Content>
          <Popover.Arrow>
            <Popover.ArrowTip />
          </Popover.Arrow>
          <Popover.Label>Label</Popover.Label>
          <Popover.Description>
            Popover content with a description.
          </Popover.Description>
        </Popover.Content>
      </Popover.Positioner>
    </Popover.Root>
  )
}
