// packages/frameworks/react/src/date-picker/date-picker-headline-label.tsx
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import type {ReactElement} from "react"

import {useDatePickerContext} from "@qualcomm-ui/react-core/date-picker"
import {
  type ElementRenderProp,
  PolymorphicElement,
} from "@qualcomm-ui/react-core/system"
import {mergeProps} from "@qualcomm-ui/utils/merge-props"

import {useQdsDatePickerContext} from "./qds-date-picker-context.js"

export interface DatePickerHeadlineLabelProps extends ElementRenderProp<"span"> {}

/**
 * Caption above the headline value. Pass children to override. Renders a `<span>`
 * element by default.
 */
export function DatePickerHeadlineLabel({
  children,
  ...props
}: DatePickerHeadlineLabelProps): ReactElement {
  const qdsContext = useQdsDatePickerContext()
  const {selectionMode} = useDatePickerContext()
  const fallback = selectionMode === "range" ? "Date range" : "Date"
  const mergedProps = mergeProps(qdsContext.getHeadlineLabelBindings(), props)

  return (
    <PolymorphicElement as="span" {...mergedProps}>
      {children ?? fallback}
    </PolymorphicElement>
  )
}

// packages/frameworks/angular/src/date-picker/date-picker-headline-label.component.ts
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import {Component, computed, type OnInit} from "@angular/core"

import {useDatePickerContext} from "@qualcomm-ui/angular-core/date-picker"
import {useTrackBindings} from "@qualcomm-ui/angular-core/machine"

import {useQdsDatePickerContext} from "./qds-date-picker-context.service"

/**
 * Caption above the headline value. Project content to override the default.
 */
@Component({
  selector: "[q-date-picker-headline-label]",
  standalone: false,
  template: `
    <ng-content>{{ fallback() }}</ng-content>
  `,
})
export class DatePickerHeadlineLabelDirective implements OnInit {
  protected readonly api = useDatePickerContext()
  protected readonly qdsContext = useQdsDatePickerContext()

  protected readonly fallback = computed(() =>
    this.api().selectionMode === "range" ? "Date range" : "Date",
  )

  protected readonly trackBindings = useTrackBindings(() =>
    this.qdsContext().getHeadlineLabelBindings(),
  )

  ngOnInit() {
    this.trackBindings()
  }
}
