// packages/frameworks/react/src/date-picker/date-picker-cancel-trigger.tsx
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import type {ReactElement} from "react"

import {useDatePickerContext} from "@qualcomm-ui/react-core/date-picker"
import {Button, type ButtonProps} from "@qualcomm-ui/react/button"
import {mergeProps} from "@qualcomm-ui/utils/merge-props"

export interface DatePickerCancelTriggerProps extends ButtonProps {}

/**
 * Discards selection, restores previous value, and closes the calendar. Renders a
 * {@link Button} with the label "Cancel" by default.
 */
export function DatePickerCancelTrigger({
  children,
  ...props
}: DatePickerCancelTriggerProps): ReactElement {
  const api = useDatePickerContext()
  const mergedProps = mergeProps(
    {
      onClick() {
        api.cancel()
      },
      type: "button" as const,
    },
    props,
  )

  return (
    <Button
      density="compact"
      emphasis="primary"
      variant="ghost"
      {...mergedProps}
    >
      {children ?? "Cancel"}
    </Button>
  )
}

// packages/frameworks/angular/src/date-picker/date-picker-cancel-trigger.component.ts
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import {Component, type OnInit} from "@angular/core"

import {useDatePickerContext} from "@qualcomm-ui/angular-core/date-picker"
import {useTrackBindings} from "@qualcomm-ui/angular-core/machine"
import {useButtonApi} from "@qualcomm-ui/angular/button"
import {mergeProps} from "@qualcomm-ui/utils/merge-props"

/**
 * Discards selection, restores previous value, and closes the calendar. Styled
 * as a ghost button with the label "Cancel" by default.
 */
@Component({
  selector: "[q-date-picker-cancel-trigger]",
  standalone: false,
  template: `
    <ng-content>Cancel</ng-content>
  `,
})
export class DatePickerCancelTriggerDirective implements OnInit {
  protected readonly datePickerContext = useDatePickerContext()

  protected readonly buttonApi = useButtonApi({
    density: "compact",
    emphasis: "primary",
    variant: "ghost",
  })

  protected readonly trackBindings = useTrackBindings(() =>
    mergeProps(
      {onclick: () => this.datePickerContext().cancel(), type: "button"},
      this.buttonApi().getRootBindings(),
    ),
  )

  ngOnInit() {
    this.trackBindings()
  }
}
