// packages/frameworks/react/src/date-picker/date-picker-headline-value.tsx
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import type {ReactElement} from "react"

import {getDatePickerHeadlineValueText} from "@qualcomm-ui/qds-core/date-picker"
import {useDatePickerContext} from "@qualcomm-ui/react-core/date-picker"
import {
  type ElementRenderProp,
  PolymorphicElement,
} from "@qualcomm-ui/react-core/system"
import {mergeProps} from "@qualcomm-ui/utils/merge-props"

import {useQdsDatePickerContext} from "./qds-date-picker-context.js"

export interface DatePickerHeadlineValueProps extends ElementRenderProp<"span"> {
  /**
   * Format used to render the selected date(s).
   */
  format?: Intl.DateTimeFormatOptions

  /**
   * Suffix appended in `multiple` mode when more than two dates are selected.
   *
   * @default (count) => `+${count} more`
   */
  moreLabel?: (count: number) => string

  /**
   * Text shown when no date is selected.
   *
   * @default 'Select date'
   */
  placeholder?: string

  /**
   * Placeholders for the start and end of an incomplete range.
   *
   * @default ['Start', 'End']
   */
  rangePlaceholder?: [string, string]
}

/**
 * Renders the current selection as human readable text. Renders a `<span>` element
 * by default.
 */
export function DatePickerHeadlineValue({
  format,
  moreLabel,
  placeholder,
  rangePlaceholder,
  ...props
}: DatePickerHeadlineValueProps): ReactElement {
  const qdsContext = useQdsDatePickerContext()
  const {format: formatDate, selectionMode, value} = useDatePickerContext()

  const text = getDatePickerHeadlineValueText({
    format: formatDate,
    formatOptions: format,
    moreLabel,
    placeholder,
    rangePlaceholder,
    selectionMode,
    value,
  })

  const mergedProps = mergeProps(qdsContext.getHeadlineValueBindings(), props)

  return (
    <PolymorphicElement as="span" {...mergedProps}>
      {text}
    </PolymorphicElement>
  )
}

// packages/frameworks/angular/src/date-picker/date-picker-headline-value.component.ts
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import {Component, computed, input, type OnInit} from "@angular/core"

import {useDatePickerContext} from "@qualcomm-ui/angular-core/date-picker"
import {useTrackBindings} from "@qualcomm-ui/angular-core/machine"
import {getDatePickerHeadlineValueText} from "@qualcomm-ui/qds-core/date-picker"

import {useQdsDatePickerContext} from "./qds-date-picker-context.service"

/**
 * Renders the current selection as human readable text.
 */
@Component({
  selector: "[q-date-picker-headline-value]",
  standalone: false,
  template: `
    {{ text() }}
  `,
})
export class DatePickerHeadlineValueDirective implements OnInit {
  /**
   * Format used to render the selected date(s).
   */
  readonly format = input<Intl.DateTimeFormatOptions | undefined>()

  /**
   * Suffix appended in `multiple` mode when more than two dates are selected.
   *
   * @default (count) => `+${count} more`
   */
  readonly moreLabel = input<((count: number) => string) | undefined>()

  /**
   * Text shown when no date is selected.
   *
   * @default 'Select date'
   */
  readonly placeholder = input<string | undefined>()

  /**
   * Placeholders for the start and end of an incomplete range.
   *
   * @default ['Start', 'End']
   */
  readonly rangePlaceholder = input<[string, string] | undefined>()

  protected readonly api = useDatePickerContext()
  protected readonly qdsContext = useQdsDatePickerContext()

  protected readonly text = computed(() => {
    const api = this.api()
    return getDatePickerHeadlineValueText({
      format: api.format,
      formatOptions: this.format(),
      moreLabel: this.moreLabel(),
      placeholder: this.placeholder(),
      rangePlaceholder: this.rangePlaceholder(),
      selectionMode: api.selectionMode,
      value: api.value,
    })
  })

  protected readonly trackBindings = useTrackBindings(() =>
    this.qdsContext().getHeadlineValueBindings(),
  )

  ngOnInit() {
    this.trackBindings()
  }
}
