// packages/docs/react-docs/src/routes/components+/badge+/demos/badge-status-emphasis-demo.tsx
import type {ReactElement} from "react"

import {Badge} from "@qualcomm-ui/react/badge"

export default function BadgeStatusEmphasisDemo(): ReactElement {
  return (
    <div className="flex flex-wrap items-center gap-4">
      {/* preview */}
      <Badge emphasis="neutral" type="status" />
      <Badge emphasis="brand" type="status" />
      <Badge emphasis="info" type="status" />
      <Badge emphasis="success" type="status" />
      <Badge emphasis="warning" type="status" />
      <Badge emphasis="danger" type="status" />
      {/* preview */}
    </div>
  )
}

// packages/docs/angular-docs/src/routes/components+/badge+/demos/badge-status-emphasis-demo.ts
import {Component} from "@angular/core"

import {BadgeDirective} from "@qualcomm-ui/angular/badge"

@Component({
  imports: [BadgeDirective],
  selector: "badge-status-emphasis-demo",
  template: `
    <div class="flex flex-wrap items-center gap-4">
      <!-- preview -->
      <span emphasis="neutral" q-badge type="status"></span>
      <span emphasis="brand" q-badge type="status"></span>
      <span emphasis="info" q-badge type="status"></span>
      <span emphasis="success" q-badge type="status"></span>
      <span emphasis="warning" q-badge type="status"></span>
      <span emphasis="danger" q-badge type="status"></span>
      <!-- preview -->
    </div>
  `,
})
export class BadgeStatusEmphasisDemo {}
