// packages/docs/react-docs/src/routes/components+/badge+/demos/badge-text-demo.tsx
import type {ReactElement} from "react"

import {Badge} from "@qualcomm-ui/react/badge"

export default function BadgeTextDemo(): ReactElement {
  return (
    <div className="flex flex-wrap items-center gap-4">
      {/* preview */}
      <Badge>New</Badge>
      <Badge>Pro</Badge>
      <Badge>Beta</Badge>
      {/* preview */}
    </div>
  )
}

// packages/docs/angular-docs/src/routes/components+/badge+/demos/badge-text-demo.ts
import {Component} from "@angular/core"

import {BadgeDirective} from "@qualcomm-ui/angular/badge"

@Component({
  imports: [BadgeDirective],
  selector: "badge-text-demo",
  template: `
    <div class="flex flex-wrap items-center gap-4">
      <!-- preview -->
      <span q-badge>New</span>
      <span q-badge>Pro</span>
      <span q-badge>Beta</span>
      <!-- preview -->
    </div>
  `,
})
export class BadgeTextDemo {}
