// packages/docs/react-docs/src/routes/components+/badge+/demos/badge-count-variants-demo.tsx
import type {ReactElement} from "react"

import {Badge} from "@qualcomm-ui/react/badge"

export default function BadgeCountVariantsDemo(): ReactElement {
  return (
    <div className="flex flex-wrap items-center gap-4">
      {/* preview */}
      <Badge count={5} type="count" variant="neutral" />
      <Badge count={5} type="count" variant="neutral-outline" />
      <Badge count={5} type="count" variant="brand" />
      <Badge count={5} type="count" variant="brand-outline" />
      <Badge count={5} type="count" variant="info" />
      <Badge count={5} type="count" variant="success" />
      <Badge count={5} type="count" variant="warning" />
      <Badge count={5} type="count" variant="danger" />
      <Badge count={5} type="count" variant="persistent-black" />
      <Badge count={5} type="count" variant="persistent-white" />
      {/* preview */}
    </div>
  )
}

// packages/docs/angular-docs/src/routes/components+/badge+/demos/badge-count-variants-demo.ts
import {Component} from "@angular/core"

import {BadgeDirective} from "@qualcomm-ui/angular/badge"

@Component({
  imports: [BadgeDirective],
  selector: "badge-count-variants-demo",
  template: `
    <div class="flex flex-wrap items-center gap-4">
      <!-- preview -->
      <span q-badge type="count" variant="neutral" [count]="5"></span>
      <span q-badge type="count" variant="neutral-outline" [count]="5"></span>
      <span q-badge type="count" variant="brand" [count]="5"></span>
      <span q-badge type="count" variant="brand-outline" [count]="5"></span>
      <span q-badge type="count" variant="info" [count]="5"></span>
      <span q-badge type="count" variant="success" [count]="5"></span>
      <span q-badge type="count" variant="warning" [count]="5"></span>
      <span q-badge type="count" variant="danger" [count]="5"></span>
      <span q-badge type="count" variant="persistent-black" [count]="5"></span>
      <span q-badge type="count" variant="persistent-white" [count]="5"></span>
      <!-- preview -->
    </div>
  `,
})
export class BadgeCountVariantsDemo {}
