// packages/docs/react-docs/src/routes/components+/badge+/demos/badge-text-sizes-demo.tsx
import type {ReactElement} from "react"

import {Badge} from "@qualcomm-ui/react/badge"

export default function BadgeTextSizesDemo(): ReactElement {
  return (
    <div className="flex flex-wrap items-center gap-4">
      {/* preview */}
      <Badge size="sm">Small</Badge>
      <Badge size="md">Medium</Badge>
      <Badge size="lg">Large</Badge>
      {/* preview */}
    </div>
  )
}

// packages/docs/angular-docs/src/routes/components+/badge+/demos/badge-text-sizes-demo.ts
import {Component} from "@angular/core"

import {BadgeDirective} from "@qualcomm-ui/angular/badge"

@Component({
  imports: [BadgeDirective],
  selector: "badge-text-sizes-demo",
  template: `
    <div class="flex flex-wrap items-center gap-4">
      <!-- preview -->
      <span q-badge size="sm">Small</span>
      <span q-badge size="md">Medium</span>
      <span q-badge size="lg">Large</span>
      <!-- preview -->
    </div>
  `,
})
export class BadgeTextSizesDemo {}
