// packages/docs/react-docs/src/routes/components+/button+/demos/button-emphasis-demo.tsx
import type {ReactElement} from "react"

import {ExternalLink} from "lucide-react"

import {Button} from "@qualcomm-ui/react/button"

export function ButtonEmphasisDemo(): ReactElement {
  return (
    <div className="grid grid-cols-3 grid-rows-2 gap-x-8 gap-y-1">
      <div className="text-neutral-primary font-heading-xs">Neutral</div>
      <div className="text-neutral-primary font-heading-xs">Primary</div>
      <div className="text-neutral-primary font-heading-xs">Danger</div>

      {/* preview */}
      <Button emphasis="neutral" startIcon={ExternalLink} variant="fill">
        Action
      </Button>
      <Button emphasis="primary" startIcon={ExternalLink} variant="fill">
        Action
      </Button>
      <Button emphasis="danger" startIcon={ExternalLink} variant="fill">
        Action
      </Button>
      {/* preview */}
    </div>
  )
}

// packages/docs/angular-docs/src/routes/components+/button+/demos/button-emphasis-demo.ts
import {Component} from "@angular/core"
import {ExternalLink} from "lucide-angular"

import {provideIcons} from "@qualcomm-ui/angular-core/lucide"
import {ButtonModule} from "@qualcomm-ui/angular/button"

@Component({
  imports: [ButtonModule],
  providers: [provideIcons({ExternalLink})],
  selector: "button-emphasis-demo",
  template: `
    <div class="grid grid-cols-3 grid-rows-2 gap-x-8 gap-y-1">
      <div class="text-neutral-primary font-heading-xs">Neutral</div>
      <div class="text-neutral-primary font-heading-xs">Primary</div>
      <div class="text-neutral-primary font-heading-xs">Danger</div>

      <!-- preview -->
      <button
        emphasis="neutral"
        q-button
        startIcon="ExternalLink"
        variant="fill"
      >
        Action
      </button>
      <button
        emphasis="primary"
        q-button
        startIcon="ExternalLink"
        variant="fill"
      >
        Action
      </button>
      <button
        emphasis="danger"
        q-button
        startIcon="ExternalLink"
        variant="fill"
      >
        Action
      </button>
      <!-- preview -->
    </div>
  `,
})
export class ButtonEmphasisDemo {}
