// packages/docs/react-docs/src/routes/components+/number-input+/demos/number-input-explorer-demo.tsx
import type {ReactElement} from "react"

import {NumberInput} from "@qualcomm-ui/react/number-input"

export function NumberInputExplorerDemo(): ReactElement {
  return (
    <NumberInput
      className="w-72"
      hint="Some contextual help here"
      label="Quantity"
      placeholder="Enter a number"
    />
  )
}

// packages/docs/angular-docs/src/routes/components+/number-input+/demos/number-input-explorer-demo.ts
import {Component} from "@angular/core"

import {NumberInputModule} from "@qualcomm-ui/angular/number-input"

@Component({
  imports: [NumberInputModule],
  selector: "number-input-explorer-demo",
  template: `
    <q-number-input
      class="w-72"
      hint="Some contextual help here"
      label="Quantity"
      placeholder="Enter a number"
    />
  `,
})
export class NumberInputExplorerDemo {}
