// packages/debug-apps/react-ssr/src/routes/components+/tooltip+/demos/tooltip-close-events-demo.tsx
import type {ReactElement} from "react"

import {Button} from "@qualcomm-ui/react/button"
import {Tooltip} from "@qualcomm-ui/react/tooltip"

export default function TooltipCloseEventsDemo(): ReactElement {
  return (
    // preview
    <Tooltip
      closeOnClick={false}
      closeOnEscape={false}
      trigger={<Button emphasis="primary">Hover me</Button>}
    >
      Hello world!
    </Tooltip>
    // preview
  )
}

// packages/docs/angular-docs/src/routes/components+/tooltip+/demos/tooltip-close-events-demo.ts
import {Component} from "@angular/core"

import {ButtonModule} from "@qualcomm-ui/angular/button"
import {TooltipModule} from "@qualcomm-ui/angular/tooltip"

@Component({
  imports: [TooltipModule, ButtonModule],
  selector: "tooltip-close-events-demo",
  template: `
    <!-- preview -->
    <div closeOnClick="false" closeOnEscape="false" q-tooltip>
      <button emphasis="primary" q-button q-tooltip-trigger variant="fill">
        Hover me
      </button>
      Hello World!
    </div>
    <!-- preview -->
  `,
})
export class TooltipCloseEventsDemo {}
