// packages/docs/react-docs/src/routes/components+/tooltip+/demos/tooltip-disabled-demo.tsx
import {type ReactElement, useState} from "react"

import {Button} from "@qualcomm-ui/react/button"
import {Tooltip} from "@qualcomm-ui/react/tooltip"

export function TooltipDisabledDemo(): ReactElement {
  const [disabled, setDisabled] = useState(true)
  return (
    <div className="flex flex-col items-center gap-4">
      <Tooltip
        disabled={disabled}
        trigger={<Button emphasis="primary">Hover me</Button>}
      >
        Hello world!
      </Tooltip>

      <Button onClick={() => setDisabled(!disabled)} variant="outline">
        {disabled ? "Enable" : "Disable"} tooltip
      </Button>
    </div>
  )
}

// packages/docs/angular-docs/src/routes/components+/tooltip+/demos/tooltip-disabled-demo.ts
import {Component, signal} from "@angular/core"

import {ButtonModule} from "@qualcomm-ui/angular/button"
import {TooltipModule} from "@qualcomm-ui/angular/tooltip"

@Component({
  imports: [TooltipModule, ButtonModule],
  selector: "tooltip-disabled-demo",
  template: `
    <div class="flex flex-col items-center gap-4">
      <!-- preview -->
      <div q-tooltip [disabled]="disabled()">
        <button emphasis="primary" q-button q-tooltip-trigger variant="fill">
          Hover me
        </button>
        Hello World!
      </div>
      <!-- preview -->

      <button q-button variant="outline" (click)="disabled.set(!disabled())">
        {{ disabled() ? "Enable" : "Disable" }} tooltip
      </button>
    </div>
  `,
})
export class TooltipDisabledDemo {
  readonly disabled = signal(false)
}
