// packages/docs/react-docs/src/routes/components+/menu+/demos/menu-explorer-demo.tsx
import type {ReactElement} from "react"

import {Command, File, FolderOpen, Pencil} from "lucide-react"

import {Icon} from "@qualcomm-ui/react/icon"
import {Menu} from "@qualcomm-ui/react/menu"

export function MenuExplorerDemo(): ReactElement {
  return (
    <Menu.Root defaultOpen positioning={{placement: "bottom-start"}}>
      <Menu.Trigger>
        <Menu.Button emphasis="primary">Actions</Menu.Button>
      </Menu.Trigger>
      <Menu.Positioner>
        <Menu.Content>
          <Menu.ItemGroup>
            <Menu.ItemGroupLabel>File</Menu.ItemGroupLabel>
            <Menu.Item value="new">
              <Menu.ItemStartIcon icon={File} />
              <Menu.ItemLabel>New File</Menu.ItemLabel>
              <Menu.ItemCommand>
                <Icon icon={Command} size="xs" />N
              </Menu.ItemCommand>
            </Menu.Item>
            <Menu.Item value="open">
              <Menu.ItemStartIcon icon={FolderOpen} />
              <Menu.ItemLabel>Open File</Menu.ItemLabel>
              <Menu.ItemCommand>
                <Icon icon={Command} size="xs" />O
              </Menu.ItemCommand>
              <Menu.ItemDescription>Browse local files</Menu.ItemDescription>
            </Menu.Item>
            <Menu.Item value="rename">
              <Menu.ItemStartIcon icon={Pencil} />
              <Menu.ItemLabel>Rename</Menu.ItemLabel>
            </Menu.Item>
          </Menu.ItemGroup>
          <Menu.Separator />
          <Menu.ItemGroup>
            <Menu.ItemGroupLabel>Options</Menu.ItemGroupLabel>
            <Menu.CheckboxItem value="autosave">
              <Menu.CheckboxItemControl />
              <Menu.ItemLabel>Autosave</Menu.ItemLabel>
            </Menu.CheckboxItem>
            <Menu.CheckboxItem checked value="minimap">
              <Menu.ItemLabel>Minimap</Menu.ItemLabel>
              <Menu.ItemIndicator />
            </Menu.CheckboxItem>
          </Menu.ItemGroup>
        </Menu.Content>
      </Menu.Positioner>
    </Menu.Root>
  )
}

// packages/docs/angular-docs/src/routes/components+/menu+/demos/menu-explorer-demo.ts
import {Component} from "@angular/core"
import {Command, File, FolderOpen, Pencil} from "lucide-angular"

import {provideIcons} from "@qualcomm-ui/angular-core/lucide"
import {IconDirective} from "@qualcomm-ui/angular/icon"
import {MenuModule} from "@qualcomm-ui/angular/menu"

@Component({
  imports: [MenuModule, IconDirective],
  providers: [provideIcons({Command, File, FolderOpen, Pencil})],
  selector: "menu-explorer-demo",
  template: `
    <q-menu defaultOpen [positioning]="{placement: 'bottom-start'}">
      <button emphasis="primary" q-menu-button variant="fill">Actions</button>
      <div q-menu-positioner>
        <div q-menu-content>
          <div q-menu-item-group>
            <label q-menu-item-group-label>File</label>
            <button q-menu-item value="new">
              <div icon="File" q-menu-item-start-icon></div>
              <div q-menu-item-label>New File</div>
              <div q-menu-item-command>
                <svg qIcon="Command" size="xs"></svg>
                N
              </div>
            </button>
            <button q-menu-item value="open">
              <div icon="FolderOpen" q-menu-item-start-icon></div>
              <div q-menu-item-label>Open File</div>
              <div q-menu-item-command>
                <svg qIcon="Command" size="xs"></svg>
                O
              </div>
              <div q-menu-item-description>Browse local files</div>
            </button>
            <button q-menu-item value="rename">
              <div icon="Pencil" q-menu-item-start-icon></div>
              <div q-menu-item-label>Rename</div>
            </button>
          </div>
          <hr q-menu-separator />
          <div q-menu-item-group>
            <label q-menu-item-group-label>Options</label>
            <button q-menu-checkbox-item value="autosave">
              <div q-menu-checkbox-item-control></div>
              <div q-menu-item-label>Autosave</div>
            </button>
            <button defaultChecked q-menu-checkbox-item value="minimap">
              <div q-menu-item-label>Minimap</div>
              <div q-menu-item-indicator></div>
            </button>
          </div>
        </div>
      </div>
    </q-menu>
  `,
})
export class MenuExplorerDemo {}
