// packages/docs/react-docs/src/routes/components+/menu+/demos/menu-within-dialog-demo.tsx
import type {ReactElement} from "react"

import {Portal} from "@qualcomm-ui/react-core/portal"
import {Button} from "@qualcomm-ui/react/button"
import {Dialog} from "@qualcomm-ui/react/dialog"
import {Menu} from "@qualcomm-ui/react/menu"

export function MenuWithinDialogDemo(): ReactElement {
  return (
    <Dialog.Root>
      <Dialog.Trigger>
        <Button emphasis="primary" variant="fill">
          Show Dialog
        </Button>
      </Dialog.Trigger>

      <Portal>
        <Dialog.Backdrop />
        <Dialog.Positioner>
          <Dialog.Content className="w-72">
            <Dialog.Body>
              <Dialog.Heading>Dialog Title</Dialog.Heading>
              <Dialog.CloseButton />

              <Menu.Root>
                <Menu.Trigger>
                  <Menu.Button className="place-self-start" emphasis="primary">
                    Show Menu
                  </Menu.Button>
                </Menu.Trigger>
                <Menu.Positioner>
                  <Menu.Content>
                    <Menu.Item value="new-txt">New Text File</Menu.Item>
                    <Menu.Item value="new-file">New File...</Menu.Item>
                    <Menu.Item value="new-win">New Window</Menu.Item>
                    <Menu.Item value="open-file">Open File...</Menu.Item>
                    <Menu.Item value="export">Export</Menu.Item>
                  </Menu.Content>
                </Menu.Positioner>
              </Menu.Root>
            </Dialog.Body>
          </Dialog.Content>
        </Dialog.Positioner>
      </Portal>
    </Dialog.Root>
  )
}

// packages/docs/angular-docs/src/routes/components+/menu+/demos/menu-within-dialog-demo.ts
import {Component} from "@angular/core"

import {PortalDirective} from "@qualcomm-ui/angular-core/portal"
import {ButtonModule} from "@qualcomm-ui/angular/button"
import {DialogModule} from "@qualcomm-ui/angular/dialog"
import {MenuModule} from "@qualcomm-ui/angular/menu"

@Component({
  imports: [MenuModule, ButtonModule, DialogModule, PortalDirective],
  selector: "menu-within-dialog-demo",
  template: `
    <div q-dialog-root>
      <button emphasis="primary" q-button q-dialog-trigger variant="fill">
        Show Dialog
      </button>

      <ng-container *qPortal>
        <div q-dialog-backdrop></div>
        <div q-dialog-positioner>
          <section class="w-72" q-dialog-content>
            <div q-dialog-body>
              <button q-dialog-close-button></button>
              <h3 q-dialog-heading>Dialog Title</h3>
              <q-menu>
                <button
                  class="place-self-start"
                  emphasis="primary"
                  q-menu-button
                  variant="fill"
                >
                  Show Menu
                </button>

                <div q-menu-positioner>
                  <div q-menu-content>
                    <button q-menu-item value="new-text-file">
                      New Text File
                    </button>
                    <button q-menu-item value="new-file">New File...</button>
                    <button q-menu-item value="open-file">Open File...</button>
                    <button q-menu-item value="export">Export</button>
                  </div>
                </div>
              </q-menu>
            </div>
          </section>
        </div>
      </ng-container>
    </div>
  `,
})
export class MenuWithinDialogDemo {}
