// packages/docs/react-docs/src/routes/components+/menu+/demos/menu-checkbox-items-demo.tsx
import type {ReactElement} from "react"

import {Portal} from "@qualcomm-ui/react-core/portal"
import {Menu} from "@qualcomm-ui/react/menu"

export function MenuCheckboxItemsDemo(): ReactElement {
  return (
    <Menu.Root>
      <Menu.Trigger>
        <Menu.Button emphasis="primary">Show Menu</Menu.Button>
      </Menu.Trigger>
      <Portal>
        <Menu.Positioner>
          <Menu.Content>
            {/* preview */}
            <Menu.ItemGroup>
              <Menu.ItemGroupLabel>Choose an option</Menu.ItemGroupLabel>
              <Menu.CheckboxItem value="item-1-1">
                <Menu.CheckboxItemControl />
                <Menu.ItemLabel>Option 1</Menu.ItemLabel>
              </Menu.CheckboxItem>
              <Menu.CheckboxItem value="item-1-2">
                <Menu.CheckboxItemControl />
                <Menu.ItemLabel>Option 2</Menu.ItemLabel>
              </Menu.CheckboxItem>
            </Menu.ItemGroup>

            <Menu.ItemGroup>
              <Menu.ItemGroupLabel>Choose an option</Menu.ItemGroupLabel>
              <Menu.CheckboxItem value="item-2-1">
                <Menu.ItemLabel>Option 1</Menu.ItemLabel>
                <Menu.ItemIndicator />
              </Menu.CheckboxItem>
              <Menu.CheckboxItem value="item-2-2">
                <Menu.ItemLabel>Option 2</Menu.ItemLabel>
                <Menu.ItemIndicator />
              </Menu.CheckboxItem>
            </Menu.ItemGroup>
            {/* preview */}
          </Menu.Content>
        </Menu.Positioner>
      </Portal>
    </Menu.Root>
  )
}

// packages/docs/angular-docs/src/routes/components+/menu+/demos/menu-checkbox-items-demo.ts
import {Component} from "@angular/core"

import {MenuModule} from "@qualcomm-ui/angular/menu"
import {PortalComponent} from "@qualcomm-ui/angular-core/portal"

@Component({
  imports: [MenuModule, PortalComponent],
  selector: "menu-checkbox-items-demo",
  template: `
    <q-menu>
      <button emphasis="primary" q-menu-button variant="fill">Show Menu</button>
      <q-portal>
        <div q-menu-positioner>
          <div q-menu-content>
            <div q-menu-item-group>
              <label q-menu-item-group-label>Choose an option</label>
              <button q-menu-checkbox-item value="option-1">
                Option 1
                <div q-menu-item-indicator></div>
              </button>
              <button q-menu-checkbox-item value="option-2">
                Option 2
                <div q-menu-item-indicator></div>
              </button>
              <button q-menu-checkbox-item value="option-3">
                Option 3
                <div q-menu-item-indicator></div>
              </button>
            </div>
          </div>
        </div>
      </q-portal>
    </q-menu>
  `,
})
export class MenuCheckboxItemsDemo {}
