// packages/frameworks/angular/src/pagination/pagination-page-item.component.ts
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import {Component, computed} from "@angular/core"
import {Ellipsis} from "lucide-angular"

import {provideIcons} from "@qualcomm-ui/angular-core/lucide"
import {CorePaginationPageItemDirective} from "@qualcomm-ui/angular-core/pagination"
import {paginationClasses} from "@qualcomm-ui/qds-core/pagination"

@Component({
  host: {
    "[class]": "paginationClasses.pageItem",
  },
  providers: [provideIcons({Ellipsis})],
  selector: "[q-pagination-page-item]",
  standalone: false,
  template: `
    @if (pageItemType() === "page") {
      <ng-container>{{ page() }}</ng-container>
    } @else {
      <svg qIcon="Ellipsis" />
    }
  `,
})
export class PaginationPageItemComponent extends CorePaginationPageItemDirective {
  readonly pageItemType = computed(() => this.itemProps()["data-type"])

  readonly page = computed(() => {
    const props = this.itemProps()
    return props["data-type"] === "page" ? props["data-page"] : undefined
  })

  protected readonly paginationClasses = paginationClasses
}

// packages/frameworks/react/src/pagination/pagination-page-item.tsx
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import type {ReactElement} from "react"

import {Ellipsis} from "lucide-react"

import type {PaginationPageItemBindings} from "@qualcomm-ui/core/pagination"
import {Icon} from "@qualcomm-ui/react/icon"
import {
  type ElementRenderProp,
  PolymorphicElement,
} from "@qualcomm-ui/react-core/system"

/**
 * @interface
 */
export type PaginationPageItemProps = PaginationPageItemBindings &
  ElementRenderProp<"button">

export function PaginationPageItem({
  ...props
}: PaginationPageItemProps): ReactElement {
  const itemType = props["data-type"]

  return (
    <PolymorphicElement as="button" {...props}>
      {itemType === "page" ? props["data-page"] : <Icon icon={Ellipsis} />}
    </PolymorphicElement>
  )
}
