// packages/docs/angular-docs/src/routes/components+/link+/demos/link-colors-demo.ts
import {Component} from "@angular/core"

import {LinkDirective} from "@qualcomm-ui/angular/link"

@Component({
  imports: [LinkDirective],
  selector: "link-colors-demo",
  template: `
    <div class="flex flex-col gap-4">
      <!-- preview -->
      <a q-link>Default</a>
      <a emphasis="neutral" q-link>Neutral</a>
      <!-- preview -->
    </div>
  `,
})
export class LinkColorsDemo {}

// packages/debug-apps/react-ssr/src/routes/components+/link+/demos/link-colors-demo.tsx
import type {ReactElement} from "react"

import {Link} from "@qualcomm-ui/react/link"

export default function LinkColorsDemo(): ReactElement {
  return (
    <div className="flex flex-col gap-4">
      {/* preview */}
      <Link>Default</Link>
      <Link emphasis="neutral">Neutral</Link>
      {/* preview */}
    </div>
  )
}
