// packages/docs/react-docs/src/routes/components+/toast+/demos/toast-max-visible-demo.tsx
import type {ReactElement} from "react"

import {Button} from "@qualcomm-ui/react/button"
import {createToaster, Toaster} from "@qualcomm-ui/react/toast"

// preview
const toaster = createToaster({
  max: 3,
  placement: "bottom-end",
})
// preview

export function ToastMaxVisibleDemo(): ReactElement {
  return (
    <>
      <Toaster toaster={toaster} />

      <Button
        onClick={() =>
          toaster.create({
            description: "Toast Description",
            label: "Toast Label",
          })
        }
        type="button"
        variant="outline"
      >
        Show Toast
      </Button>
    </>
  )
}

// packages/docs/angular-docs/src/routes/components+/toast+/demos/toast-max-visible-demo.ts
import {Component, inject} from "@angular/core"

import {ButtonModule} from "@qualcomm-ui/angular/button"
import {provideToaster, ToasterService, ToastModule} from "@qualcomm-ui/angular/toast"

@Component({
  imports: [ToastModule, ButtonModule],
  providers: [
    provideToaster({
      max: 3,
      placement: "bottom-end",
    }),
  ],
  selector: "toast-max-visible-demo",
  template: `
    <div q-toaster [toaster]="toaster"></div>

    <button q-button variant="outline" (click)="createToast()">
      Show Toast
    </button>
  `,
})
export class ToastMaxVisibleDemo {
  toaster = inject(ToasterService).toaster

  createToast() {
    this.toaster.create({
      description: "Toast Description",
      label: "Toast Label",
    })
  }
}
