// packages/frameworks/angular/src/menu/menu-split-button.component.ts
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import {
  booleanAttribute,
  Component,
  computed,
  inject,
  input,
  type OnInit,
  output,
} from "@angular/core"

import type {LucideIconOrString} from "@qualcomm-ui/angular-core/lucide"
import {
  normalizeProps,
  useTrackBindings,
} from "@qualcomm-ui/angular-core/machine"
import {
  type ButtonGroupContextValue,
  provideQdsButtonGroupContext,
  QdsButtonGroupContextService,
} from "@qualcomm-ui/angular/button"
import type {
  QdsButtonDensity,
  QdsButtonEmphasis,
  QdsButtonSize,
  QdsButtonVariant,
} from "@qualcomm-ui/qds-core/button"
import {getQdsSplitButtonBindings} from "@qualcomm-ui/qds-core/menu"
import type {Booleanish} from "@qualcomm-ui/utils/coercion"

/**
 * @since 2.11.0
 */
@Component({
  providers: [provideQdsButtonGroupContext()],
  selector: "[q-menu-split-button]",
  standalone: false,
  template: `
    <ng-content select="[q-button]">
      <button
        q-button
        [endIcon]="endIcon()"
        [startIcon]="startIcon()"
        (click)="actionClicked.emit($event)"
      >
        <ng-content />
      </button>
    </ng-content>
    <ng-content select="button[q-menu-icon-button]">
      <button aria-label="More options" q-menu-icon-button></button>
    </ng-content>
  `,
})
export class MenuSplitButtonComponent implements OnInit {
  /**
   * {@link https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-label aria-label}
   * attribute.
   */
  readonly ariaLabel = input<string | undefined>(undefined, {
    alias: "aria-label",
  })

  /**
   * {@link https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-labelledby aria-labelledby}
   * attribute.
   */
  readonly ariaLabelledby = input<string | undefined>(undefined, {
    alias: "aria-labelledby",
  })

  /**
   * The density of both buttons.
   */
  readonly density = input<QdsButtonDensity>()

  /**
   * Disables both buttons.
   */
  readonly disabled = input<boolean | undefined, Booleanish>(undefined, {
    transform: booleanAttribute,
  })

  /**
   * The emphasis applied to both buttons.
   */
  readonly emphasis = input<QdsButtonEmphasis>()

  /**
   * Icon positioned after the primary action label.
   */
  readonly endIcon = input<LucideIconOrString>()

  /**
   * The size of both buttons.
   */
  readonly size = input<QdsButtonSize>()

  /**
   * Icon positioned before the primary action label.
   */
  readonly startIcon = input<LucideIconOrString>()

  /**
   * The variant applied to both buttons.
   */
  readonly variant = input<QdsButtonVariant>()

  /**
   * Emitted when the default action button is clicked.
   */
  readonly actionClicked = output<MouseEvent>()

  protected readonly buttonGroupService = inject(QdsButtonGroupContextService)

  protected readonly trackBindings = useTrackBindings(() =>
    getQdsSplitButtonBindings(
      {
        "aria-label": this.ariaLabel() || undefined,
        "aria-labelledby": this.ariaLabelledby() || undefined,
        density: this.density(),
        disabled: this.disabled(),
        emphasis: this.emphasis(),
        size: this.size(),
        variant: this.variant(),
      },
      normalizeProps,
    ),
  )

  ngOnInit() {
    this.buttonGroupService.init(
      computed<ButtonGroupContextValue>(() => ({
        density: this.density(),
        disabled: this.disabled(),
        emphasis: this.emphasis(),
        size: this.size(),
        variant: this.variant(),
      })),
    )
    this.trackBindings()
  }
}

// packages/frameworks/react/src/menu/menu-split-button.tsx
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import type {ReactElement, ReactNode} from "react"

import type {QdsButtonApiProps} from "@qualcomm-ui/qds-core/button"
import {
  getQdsSplitButtonBindings,
  type QdsSplitButtonApiProps,
} from "@qualcomm-ui/qds-core/menu"
import {normalizeProps} from "@qualcomm-ui/react-core/machine"
import {
  type ElementRenderProp,
  PolymorphicElement,
} from "@qualcomm-ui/react-core/system"
import {Button, type ButtonProps} from "@qualcomm-ui/react/button"
import {mergeProps} from "@qualcomm-ui/utils/merge-props"

import {MenuIconButton, type MenuIconButtonProps} from "./menu-icon-button.js"
import {MenuTrigger} from "./menu-trigger.js"

/**
 * @since 1.24.0
 */
export interface MenuSplitButtonProps
  extends Omit<ElementRenderProp<"div">, "onClick">, QdsSplitButtonApiProps {
  /**
   * Props applied to the primary action button.
   */
  actionProps?: Omit<ButtonProps, keyof QdsButtonApiProps | "children">

  /**
   * Content rendered inside the primary action button.
   */
  children?: ReactNode

  /**
   * Icon positioned after the primary action label.
   */
  endIcon?: ButtonProps["endIcon"]

  /**
   * Called when the primary action button is clicked.
   */
  onClick?: ButtonProps["onClick"]

  /**
   * Icon positioned before the primary action label.
   */
  startIcon?: ButtonProps["startIcon"]

  /**
   * Props applied to the chevron trigger button.
   */
  triggerProps?: Omit<MenuIconButtonProps, keyof QdsButtonApiProps>
}

/**
 * @since 1.24.0
 */
export function MenuSplitButton({
  actionProps,
  "aria-label": ariaLabel,
  "aria-labelledby": ariaLabelledBy,
  children,
  density,
  disabled,
  emphasis,
  endIcon,
  onClick,
  size,
  startIcon,
  triggerProps,
  variant,
  ...props
}: MenuSplitButtonProps): ReactElement {
  const buttonProps = {density, disabled, emphasis, size, variant}
  const mergedProps = mergeProps(
    getQdsSplitButtonBindings(
      {
        "aria-label": ariaLabel,
        "aria-labelledby": ariaLabelledBy,
        ...buttonProps,
      },
      normalizeProps,
    ),
    props,
  )
  return (
    <PolymorphicElement as="div" {...mergedProps}>
      <Button
        {...buttonProps}
        {...actionProps}
        endIcon={endIcon ?? actionProps?.endIcon}
        onClick={onClick ?? actionProps?.onClick}
        startIcon={startIcon ?? actionProps?.startIcon}
      >
        {children}
      </Button>
      <MenuTrigger>
        <MenuIconButton
          aria-label="More options"
          {...buttonProps}
          {...triggerProps}
        />
      </MenuTrigger>
    </PolymorphicElement>
  )
}
