// packages/frameworks/react/src/menu/menu-checkbox-item-control.tsx
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import type {ReactElement, ReactNode} from "react"

import {CheckmarkIcon} from "@qualcomm-ui/react/checkmark"
import {useMenuOptionItemControl} from "@qualcomm-ui/react-core/menu"
import {
  type ElementRenderProp,
  PolymorphicElement,
} from "@qualcomm-ui/react-core/system"
import {mergeProps} from "@qualcomm-ui/utils/merge-props"

import {useQdsMenuContext} from "./qds-menu-context"

export interface MenuCheckboxItemControlProps extends ElementRenderProp<"div"> {
  /**
   * React {@link https://react.dev/learn/passing-props-to-a-component#passing-jsx-as-children children} prop.
   *
   * @default `<Checkbox.IndicatorIcon />`
   */
  children?: ReactNode
}

export function MenuCheckboxItemControl({
  children = <CheckmarkIcon indeterminate={false} />,
  ...props
}: MenuCheckboxItemControlProps): ReactElement {
  const contextProps = useMenuOptionItemControl()
  const qdsContext = useQdsMenuContext()
  const mergedProps = mergeProps(
    contextProps,
    qdsContext.getCheckboxItemControlBindings(),
    props,
  )

  return (
    <PolymorphicElement as="div" {...mergedProps}>
      {children}
    </PolymorphicElement>
  )
}

// packages/frameworks/angular/src/menu/menu-checkbox-item-control.component.ts
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import {Component, computed} from "@angular/core"

import {CoreMenuOptionItemControlDirective} from "@qualcomm-ui/angular-core/menu"

import {useQdsMenuContext} from "./qds-menu-context.service"

/**
 * Visual control rendered within a checkbox menu item. Defaults to a checkmark
 * icon; project custom content to override.
 */
@Component({
  selector: "[q-menu-checkbox-item-control]",
  standalone: false,
  template: `
    <ng-content>
      <q-checkmark-icon [indeterminate]="false" />
    </ng-content>
  `,
})
export class MenuCheckboxItemControlComponent extends CoreMenuOptionItemControlDirective {
  protected readonly qdsMenuContext = useQdsMenuContext()

  constructor() {
    super()
    this.trackBindings.extendWith(
      computed(() => this.qdsMenuContext().getCheckboxItemControlBindings()),
    )
  }
}
