// packages/docs/react-docs/src/routes/components+/segmented-control+/demos/segmented-control-layout-demo.tsx
import type {QdsSegmentedControlLayout} from "@qualcomm-ui/qds-core/segmented-control"
import {SegmentedControl} from "@qualcomm-ui/react/segmented-control"

export default function SegmentedControlLayoutDemo() {
  return (
    <div className="flex w-full flex-col gap-4">
      {/* preview */}
      {(["hug", "fill"] as QdsSegmentedControlLayout[]).map((layout) => (
        <SegmentedControl.Root
          key={layout}
          defaultValue={["chart"]}
          layout={layout}
        >
          <SegmentedControl.Item text="Chart" value="chart" />
          <SegmentedControl.Item text="Table" value="table" />
          <SegmentedControl.Item text="Map" value="map" />
        </SegmentedControl.Root>
      ))}
      {/* preview */}
    </div>
  )
}

// packages/docs/angular-docs/src/routes/components+/segmented-control+/demos/segmented-control-layout-demo.ts
import {Component} from "@angular/core"

import {SegmentedControlModule} from "@qualcomm-ui/angular/segmented-control"
import type {QdsSegmentedControlLayout} from "@qualcomm-ui/qds-core/segmented-control"

@Component({
  imports: [SegmentedControlModule],
  selector: "segmented-control-layout-demo",
  template: `
    <div class="flex w-full flex-col gap-4">
      <!-- preview -->
      @for (layout of layouts; track layout) {
        <fieldset
          q-segmented-control
          [defaultValue]="['chart']"
          [layout]="layout"
        >
          <label q-segmented-control-item text="Chart" value="chart"></label>
          <label q-segmented-control-item text="Table" value="table"></label>
          <label q-segmented-control-item text="Map" value="map"></label>
        </fieldset>
      }
      <!-- preview -->
    </div>
  `,
})
export class SegmentedControlLayoutDemo {
  protected layouts: QdsSegmentedControlLayout[] = ["hug", "fill"]
}
