// packages/docs/react-docs/src/routes/components+/segmented-control+/demos/segmented-control-composite-demo.tsx
import {SegmentedControl} from "@qualcomm-ui/react/segmented-control"

export default function SegmentedControlCompositeDemo() {
  return (
    // preview
    <SegmentedControl.Root defaultValue={["chart"]}>
      <SegmentedControl.ItemRoot value="chart">
        <SegmentedControl.ItemText>Chart</SegmentedControl.ItemText>
        <SegmentedControl.HiddenInput />
      </SegmentedControl.ItemRoot>
      <SegmentedControl.ItemRoot value="table">
        <SegmentedControl.ItemText>Table</SegmentedControl.ItemText>
        <SegmentedControl.HiddenInput />
      </SegmentedControl.ItemRoot>
      <SegmentedControl.ItemRoot value="map">
        <SegmentedControl.ItemText>Map</SegmentedControl.ItemText>
        <SegmentedControl.HiddenInput />
      </SegmentedControl.ItemRoot>
    </SegmentedControl.Root>
    // preview
  )
}

// packages/docs/angular-docs/src/routes/components+/segmented-control+/demos/segmented-control-composite-demo.ts
import {Component} from "@angular/core"

import {SegmentedControlModule} from "@qualcomm-ui/angular/segmented-control"

@Component({
  imports: [SegmentedControlModule],
  selector: "segmented-control-composite-demo",
  template: `
    <!-- preview -->
    <fieldset q-segmented-control [defaultValue]="['chart']">
      <label q-segmented-control-item-root value="chart">
        <span q-segmented-control-item-text>Chart</span>
        <input q-segmented-control-hidden-input />
      </label>
      <label q-segmented-control-item-root value="table">
        <span q-segmented-control-item-text>Table</span>
        <input q-segmented-control-hidden-input />
      </label>
      <label q-segmented-control-item-root value="map">
        <span q-segmented-control-item-text>Map</span>
        <input q-segmented-control-hidden-input />
      </label>
    </fieldset>
    <!-- preview -->
  `,
})
export class SegmentedControlCompositeDemo {}
