// packages/docs/angular-docs/src/routes/components+/checkbox+/demos/checkbox-states-demo.ts
import {Component} from "@angular/core"

import {CheckboxModule} from "@qualcomm-ui/angular/checkbox"

@Component({
  imports: [CheckboxModule],
  selector: "checkbox-states",
  template: `
    <div class="grid grid-cols-3 grid-rows-2 gap-x-4 gap-y-2">
      <div class="text-neutral-primary font-heading-xxs">Checked</div>
      <div class="text-neutral-primary font-heading-xxs">Unchecked</div>
      <div class="text-neutral-primary font-heading-xxs">Indeterminate</div>

      <!-- preview -->
      <label defaultChecked label="Label" q-checkbox></label>
      <label label="Label" q-checkbox></label>
      <label indeterminate label="Label" q-checkbox></label>
      <!-- preview -->
    </div>
  `,
})
export class CheckboxStatesDemo {}

// packages/docs/react-docs/src/routes/components+/checkbox+/demos/checkbox-states-demo.tsx
import type {ReactElement} from "react"

import {Checkbox} from "@qualcomm-ui/react/checkbox"

export function CheckboxStatesDemo(): ReactElement {
  return (
    <div className="grid grid-cols-3 grid-rows-2 gap-x-4 gap-y-2">
      <div className="text-neutral-primary font-heading-xxs">Checked</div>
      <div className="text-neutral-primary font-heading-xxs">Unchecked</div>
      <div className="text-neutral-primary font-heading-xxs">Indeterminate</div>

      {/* preview */}
      <Checkbox defaultChecked label="Label" />
      <Checkbox label="Label" />
      <Checkbox indeterminate label="Label" />
      {/* preview */}
    </div>
  )
}
