// packages/docs/angular-docs/src/routes/components+/progress-ring+/demos/progress-ring-disabled-demo.ts
import {Component} from "@angular/core"

import {ProgressRingModule} from "@qualcomm-ui/angular/progress-ring"

@Component({
  imports: [ProgressRingModule],
  selector: "progress-ring-disabled-demo",
  template: `
    <div class="flex gap-8">
      <!-- preview -->
      <div disabled label="Indeterminate" q-progress-ring size="lg"></div>
      <div
        disabled
        label="Determinate"
        q-progress-ring
        size="lg"
        value="64"
        valueText="64%"
      ></div>
      <!-- preview -->
    </div>
  `,
})
export class ProgressRingDisabledDemo {}

// packages/docs/react-docs/src/routes/components+/progress-ring+/demos/progress-ring-disabled-demo.tsx
import type {ReactElement} from "react"

import {ProgressRing} from "@qualcomm-ui/react/progress-ring"

export function ProgressRingDisabledDemo(): ReactElement {
  return (
    <div className="flex gap-8">
      {/* preview */}
      <ProgressRing disabled label="Indeterminate" size="lg" />
      <ProgressRing
        disabled
        label="Determinate"
        size="lg"
        value={64}
        valueText="64%"
      />
      {/* preview */}
    </div>
  )
}
