// packages/docs/angular-docs/src/routes/components+/text-input+/demos/text-input-controlled-state-demo.ts
import {Component, signal} from "@angular/core"
import {FormsModule} from "@angular/forms"

import {ButtonModule} from "@qualcomm-ui/angular/button"
import {TextInputModule} from "@qualcomm-ui/angular/text-input"

@Component({
  imports: [TextInputModule, ButtonModule, FormsModule],
  selector: "text-input-controlled-state-demo",
  template: `
    <div class="flex items-end gap-4">
      <q-text-input
        aria-label="Controlled state"
        class="w-72"
        placeholder="Placeholder text"
        [(ngModel)]="value"
      />

      <button emphasis="primary" q-button variant="outline" (click)="reset()">
        Reset
      </button>
    </div>
  `,
})
export class TextInputControlledStateDemo {
  readonly value = signal("Controlled value")

  reset() {
    this.value.set("")
  }
}

// packages/docs/react-docs/src/routes/components+/text-input+/demos/text-input-controlled-state-demo.tsx
import {type ReactElement, useState} from "react"

import {Button} from "@qualcomm-ui/react/button"
import {TextInput} from "@qualcomm-ui/react/text-input"

export function TextInputControlledStateDemo(): ReactElement {
  const [value, setValue] = useState<string>("Controlled value")

  return (
    <div className="flex items-end gap-4">
      <TextInput.Root
        className="w-72"
        onValueChange={(updatedValue) => {
          console.debug("Value changed:", updatedValue)
          setValue(updatedValue)
        }}
        value={value}
      >
        <TextInput.Label>Label</TextInput.Label>
        <TextInput.InputGroup>
          <TextInput.Input placeholder="Placeholder text" />
        </TextInput.InputGroup>
      </TextInput.Root>

      <Button emphasis="primary" onClick={() => setValue("")} variant="outline">
        Reset
      </Button>
    </div>
  )
}
