// packages/docs/angular-docs/src/routes/components+/text-input+/demos/text-input-explorer-demo.ts
import {Component} from "@angular/core"

import {TextInputModule} from "@qualcomm-ui/angular/text-input"

@Component({
  imports: [TextInputModule],
  selector: "text-input-explorer-demo",
  template: `
    <q-text-input
      class="w-72"
      clearable
      hint="Some contextual help here"
      label="Username"
      placeholder="Enter username"
    />
  `,
})
export class TextInputExplorerDemo {}

// packages/docs/react-docs/src/routes/components+/text-input+/demos/text-input-explorer-demo.tsx
import type {ReactElement} from "react"

import {TextInput} from "@qualcomm-ui/react/text-input"

export function TextInputExplorerDemo(): ReactElement {
  return (
    <TextInput
      className="w-72"
      clearable
      hint="Some contextual help here"
      label="Username"
      placeholder="Enter username"
    />
  )
}
