// packages/docs/angular-docs/src/routes/components+/progress+/demos/progress-label-orientation-demo.ts
import {Component} from "@angular/core"

import {ProgressModule} from "@qualcomm-ui/angular/progress"

@Component({
  imports: [ProgressModule],
  selector: "progress-label-orientation-demo",
  template: `
    <!-- preview -->
    <div
      class="w-96"
      label="Label"
      labelOrientation="side"
      q-progress
      value="64"
      valueText="64%"
    ></div>
    <!-- preview -->
  `,
})
export class ProgressLabelOrientationDemo {}

// packages/docs/react-docs/src/routes/components+/progress+/demos/progress-label-orientation-demo.tsx
import type {ReactElement} from "react"

import {Progress} from "@qualcomm-ui/react/progress"

export default function ProgressLabelOrientationDemo(): ReactElement {
  return (
    <div className="flex flex-col gap-6">
      <Progress
        className="w-96"
        label="Determinate"
        labelOrientation="side"
        value={64}
        valueText="64%"
      />
    </div>
  )
}
