// packages/docs/react-docs/src/routes/components+/switch-group+/demos/switch-group-error-demo.tsx
import type {ReactElement} from "react"

import {Switch} from "@qualcomm-ui/react/switch"
import {SwitchGroup} from "@qualcomm-ui/react/switch-group"

export function SwitchGroupErrorDemo(): ReactElement {
  return (
    // preview
    <SwitchGroup
      errorText="Select at least one option"
      invalid
      label="Notifications"
    >
      <Switch label="Email" />
      <Switch label="SMS" />
    </SwitchGroup>
    // preview
  )
}

// packages/docs/angular-docs/src/routes/components+/switch-group+/demos/switch-group-error-demo.ts
import {Component} from "@angular/core"

import {SwitchModule} from "@qualcomm-ui/angular/switch"
import {SwitchGroupModule} from "@qualcomm-ui/angular/switch-group"

@Component({
  imports: [SwitchGroupModule, SwitchModule],
  selector: "switch-group-error-demo",
  template: `
    <!-- preview -->
    <fieldset
      errorText="Select at least one option"
      invalid
      label="Notifications"
      q-switch-group
    >
      <label label="Email" q-switch></label>
      <label label="SMS" q-switch></label>
    </fieldset>
    <!-- preview -->
  `,
})
export class SwitchGroupErrorDemo {}
