// packages/debug-apps/angular-ssr/src/app/components/popover.ts
import {Component} from "@angular/core"

import {PopoverCompositeDemo} from "@qualcomm-ui/angular-docs/components+/popover+/demos/popover-composite-demo"
import {PopoverSimpleDemo} from "@qualcomm-ui/angular-docs/components+/popover+/demos/popover-simple-demo"

@Component({
  imports: [PopoverCompositeDemo, PopoverSimpleDemo],
  template: `
    <div
      class="container"
      style="max-width: 1200px; margin: 0 auto; padding: 2rem;"
    >
      <div class="section">
        <h2 class="section-title">Composite</h2>
        <div class="demo-container">
          <popover-composite-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Simple</h2>
        <div class="demo-container">
          <popover-simple-demo />
        </div>
      </div>
    </div>
  `,
})
export class PopoverPage {}

// packages/debug-apps/react-ssr/src/routes/components+/popover+/_popover.tsx
import CompositeDemo from "@qualcomm-ui/react-docs/components+/popover+/demos/popover-composite-demo"
import SimpleDemo from "@qualcomm-ui/react-docs/components+/popover+/demos/popover-simple-demo"

const demos = [
  {component: CompositeDemo, title: "Composite"},
  {component: SimpleDemo, title: "Simple"},
]

export default function PopoverDemos() {
  return (
    <div className="page">
      {demos.map(({component: Demo, title}) => (
        <div className="section" key={title}>
          <h2 className="section-title">{title}</h2>
          <div className="demo-container">
            <Demo />
          </div>
        </div>
      ))}
    </div>
  )
}
