// packages/docs/angular-docs/src/routes/components+/password-input+/demos/password-input-controlled-visibility-demo.ts
import {Component, signal} from "@angular/core"

import {ButtonModule} from "@qualcomm-ui/angular/button"
import {PasswordInputModule} from "@qualcomm-ui/angular/password-input"

@Component({
  imports: [PasswordInputModule, ButtonModule],
  selector: "password-input-controlled-visibility-demo",
  template: `
    <div class="flex flex-col gap-4">
      <!-- preview -->
      <q-password-input
        class="w-72"
        defaultValue="passw0rd"
        label="Password"
        placeholder="Enter your password"
        [visible]="visible()"
        (visibleChanged)="setVisible($event)"
      />

      <button
        emphasis="primary"
        q-button
        variant="outline"
        (click)="toggleVisible()"
      >
        {{ visible() ? "Hide Password" : "Show Password" }}
      </button>
      <!-- preview -->
    </div>
  `,
})
export class PasswordInputControlledVisibilityDemo {
  protected readonly visible = signal(false)

  setVisible(visible: boolean) {
    this.visible.set(visible)
  }

  toggleVisible() {
    this.visible.update((visible) => !visible)
  }
}

// packages/docs/react-docs/src/routes/components+/password-input+/demos/password-input-controlled-visibility-demo.tsx
import {type ReactElement, useState} from "react"

import {Button} from "@qualcomm-ui/react/button"
import {PasswordInput} from "@qualcomm-ui/react/password-input"

export default function PasswordInputControlledVisibilityDemo(): ReactElement {
  const [visible, setVisible] = useState<boolean>(false)

  return (
    <div className="flex flex-col gap-4">
      <PasswordInput
        className="w-72"
        defaultValue="passw0rd"
        label="Password"
        onVisibleChange={setVisible}
        placeholder="Enter your password"
        visible={visible}
      />

      <Button
        emphasis="primary"
        onClick={() => setVisible(!visible)}
        variant="outline"
      >
        {visible ? "Hide Password" : "Show Password"}
      </Button>
    </div>
  )
}
