// packages/frameworks/angular/src/collapsible/collapsible-root.component.ts
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import {Directive} from "@angular/core"

import {
  CoreCollapsibleRootDirective,
  provideCollapsibleContext,
} from "@qualcomm-ui/angular-core/collapsible"

@Directive({
  providers: [provideCollapsibleContext()],
  selector: "[q-collapsible-root]",
  standalone: false,
})
export class CollapsibleRootComponent extends CoreCollapsibleRootDirective {}

// packages/frameworks/react/src/collapsible/collapsible-root.tsx
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import type {ReactElement} from "react"

import {
  CoreCollapsible,
  type CoreCollapsibleRootProps,
} from "@qualcomm-ui/react-core/collapsible"

export interface CollapsibleRootProps extends CoreCollapsibleRootProps {}

/**
 * Groups all parts of the collapsible. Renders a `<div>` element by default.
 */
export function CollapsibleRoot(props: CollapsibleRootProps): ReactElement {
  return <CoreCollapsible.Root {...props} />
}
