// packages/debug-apps/angular-ssr/src/app/components/breadcrumbs.ts
import {Component} from "@angular/core"

import {BreadcrumbsDisabledDemo} from "@qualcomm-ui/angular-docs/components+/breadcrumbs+/demos/breadcrumbs-disabled-demo"
import {BreadcrumbsEmphasisDemo} from "@qualcomm-ui/angular-docs/components+/breadcrumbs+/demos/breadcrumbs-emphasis-demo"
import {BreadcrumbsLinksDemo} from "@qualcomm-ui/angular-docs/components+/breadcrumbs+/demos/breadcrumbs-links-demo"
import {BreadcrumbsSizesDemo} from "@qualcomm-ui/angular-docs/components+/breadcrumbs+/demos/breadcrumbs-sizes-demo"

@Component({
  imports: [
    BreadcrumbsDisabledDemo,
    BreadcrumbsEmphasisDemo,
    BreadcrumbsLinksDemo,
    BreadcrumbsSizesDemo,
  ],
  template: `
    <div
      class="container"
      style="max-width: 1200px; margin: 0 auto; padding: 2rem;"
    >
      <div class="section">
        <h2 class="section-title">Disabled</h2>
        <div class="demo-container">
          <breadcrumbs-disabled-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Emphasis</h2>
        <div class="demo-container">
          <breadcrumbs-emphasis-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Links</h2>
        <div class="demo-container">
          <breadcrumbs-links-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Sizes</h2>
        <div class="demo-container">
          <breadcrumbs-sizes-demo />
        </div>
      </div>
    </div>
  `,
})
export class BreadcrumbsPage {}

// packages/debug-apps/react-ssr/src/routes/components+/breadcrumbs.tsx
import {BreadcrumbsDisabledDemo as DisabledDemo} from "@qualcomm-ui/react-docs/components+/breadcrumbs+/demos/breadcrumbs-disabled-demo"
import {BreadcrumbsEmphasisDemo as EmphasisDemo} from "@qualcomm-ui/react-docs/components+/breadcrumbs+/demos/breadcrumbs-emphasis-demo"
import {BreadcrumbsLinksDemo as LinksDemo} from "@qualcomm-ui/react-docs/components+/breadcrumbs+/demos/breadcrumbs-links-demo"
import {BreadcrumbsSizesDemo as SizesDemo} from "@qualcomm-ui/react-docs/components+/breadcrumbs+/demos/breadcrumbs-sizes-demo"

import {DemoPageLayout} from "~/components/demo-page-layout"

const demos = [
  {component: DisabledDemo, title: "Disabled"},
  {component: EmphasisDemo, title: "Emphasis"},
  {component: LinksDemo, title: "Links"},
  {component: SizesDemo, title: "Sizes"},
]

export default function BreadcrumbsDemos() {
  return <DemoPageLayout componentName="breadcrumbs" demos={demos} />
}
