// packages/debug-apps/angular-ssr/src/app/components/button.ts
import {Component, ViewEncapsulation} from "@angular/core"

import {ButtonContrastDemo} from "@qualcomm-ui/angular-docs/components+/button+/demos/button-contrast-demo"
import {ButtonDensityDemo} from "@qualcomm-ui/angular-docs/components+/button+/demos/button-density-demo"
import {ButtonEmphasisDemo} from "@qualcomm-ui/angular-docs/components+/button+/demos/button-emphasis-demo"
import {ButtonInverseDemo} from "@qualcomm-ui/angular-docs/components+/button+/demos/button-inverse-demo"
import {ButtonSizesDemo} from "@qualcomm-ui/angular-docs/components+/button+/demos/button-sizes-demo"
import {ButtonStylesDemo} from "@qualcomm-ui/angular-docs/components+/button+/demos/button-styles-demo"
import {ButtonVariantsDemo} from "@qualcomm-ui/angular-docs/components+/button+/demos/button-variants-demo"

@Component({
  encapsulation: ViewEncapsulation.None,
  imports: [
    ButtonContrastDemo,
    ButtonDensityDemo,
    ButtonEmphasisDemo,
    ButtonInverseDemo,
    ButtonSizesDemo,
    ButtonStylesDemo,
    ButtonVariantsDemo,
  ],
  selector: "app-button",
  template: `
    <div class="container">
      <div class="section">
        <h2 class="section-title">Contrast</h2>
        <div class="demo-container">
          <button-contrast-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Density</h2>
        <div class="demo-container">
          <button-density-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Emphasis</h2>
        <div class="demo-container">
          <button-emphasis-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Inverse</h2>
        <div class="demo-container">
          <button-inverse-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Sizes</h2>
        <div class="demo-container">
          <button-sizes-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Styles</h2>
        <div class="demo-container">
          <button-styles-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Variants</h2>
        <div class="demo-container">
          <button-variants-demo />
        </div>
      </div>
    </div>
  `,
})
export class ButtonPage {}

// packages/debug-apps/react-ssr/src/routes/components+/button.tsx
import {ButtonContrastDemo as ContrastDemo} from "@qualcomm-ui/react-docs/components+/button+/demos/button-contrast-demo"
import {ButtonDensityDemo as DensityDemo} from "@qualcomm-ui/react-docs/components+/button+/demos/button-density-demo"
import {ButtonEmphasisDemo as EmphasisDemo} from "@qualcomm-ui/react-docs/components+/button+/demos/button-emphasis-demo"
import {ButtonInverseDemo as InverseDemo} from "@qualcomm-ui/react-docs/components+/button+/demos/button-inverse-demo"
import {ButtonShowcaseDemo as ShowcaseDemo} from "@qualcomm-ui/react-docs/components+/button+/demos/button-showcase-demo"
import {ButtonSizesDemo as SizesDemo} from "@qualcomm-ui/react-docs/components+/button+/demos/button-sizes-demo"
import {ButtonVariantsDemo as VariantsDemo} from "@qualcomm-ui/react-docs/components+/button+/demos/button-variants-demo"

import {DemoPageLayout} from "~/components/demo-page-layout"

const demos = [
  {component: ContrastDemo, title: "Contrast"},
  {component: DensityDemo, title: "Density"},
  {component: EmphasisDemo, title: "Emphasis"},
  {component: InverseDemo, title: "Inverse"},
  {component: ShowcaseDemo, title: "Showcase"},
  {component: SizesDemo, title: "Sizes"},
  {component: VariantsDemo, title: "Variants"},
]

export default function ButtonDemos() {
  return <DemoPageLayout componentName="button" demos={demos} />
}
