// packages/debug-apps/angular-ssr/src/app/components/checkbox.ts
import {Component} from "@angular/core"

import {CheckboxAdvancedValidationDemo} from "@qualcomm-ui/angular-docs/components+/checkbox+/demos/checkbox-advanced-validation-demo"
import {CheckboxCompositeDemo} from "@qualcomm-ui/angular-docs/components+/checkbox+/demos/checkbox-composite-demo"
import {CheckboxDisabledDemo} from "@qualcomm-ui/angular-docs/components+/checkbox+/demos/checkbox-disabled-demo"
import {CheckboxReactiveFormsDemo} from "@qualcomm-ui/angular-docs/components+/checkbox+/demos/checkbox-reactive-forms-demo"
import {CheckboxSimpleDemo} from "@qualcomm-ui/angular-docs/components+/checkbox+/demos/checkbox-simple-demo"
import {CheckboxSizesDemo} from "@qualcomm-ui/angular-docs/components+/checkbox+/demos/checkbox-sizes-demo"
import {CheckboxStatesDemo} from "@qualcomm-ui/angular-docs/components+/checkbox+/demos/checkbox-states-demo"
import {CheckboxTemplateFormsDemo} from "@qualcomm-ui/angular-docs/components+/checkbox+/demos/checkbox-template-forms-demo"

@Component({
  imports: [
    CheckboxAdvancedValidationDemo,
    CheckboxCompositeDemo,
    CheckboxDisabledDemo,
    CheckboxReactiveFormsDemo,
    CheckboxSimpleDemo,
    CheckboxSizesDemo,
    CheckboxStatesDemo,
    CheckboxTemplateFormsDemo,
  ],
  selector: "app-checkbox",
  template: `
    <div class="container">
      <div class="section">
        <h2 class="section-title">Advanced Validation</h2>
        <div class="demo-container">
          <checkbox-reactive-forms-advanced-validation />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Composite</h2>
        <div class="demo-container">
          <checkbox-showcase />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Disabled</h2>
        <div class="demo-container">
          <checkbox-disabled />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Reactive Forms</h2>
        <div class="demo-container">
          <checkbox-reactive-forms />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Simple</h2>
        <div class="demo-container">
          <simple-checkbox-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Sizes</h2>
        <div class="demo-container">
          <checkbox-sizes-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">States</h2>
        <div class="demo-container">
          <checkbox-states />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Template Forms</h2>
        <div class="demo-container">
          <checkbox-template-forms />
        </div>
      </div>
    </div>
  `,
})
export class CheckboxPage {}

// packages/debug-apps/react-ssr/src/routes/components+/checkbox.tsx
import {CheckboxCompositeLayoutDemo as CompositeLayoutDemo} from "@qualcomm-ui/react-docs/components+/checkbox+/demos/checkbox-composite-layout-demo"
import {CheckboxControlledDemo as ControlledDemo} from "@qualcomm-ui/react-docs/components+/checkbox+/demos/checkbox-controlled-demo"
import {CheckboxDisabledDemo as DisabledDemo} from "@qualcomm-ui/react-docs/components+/checkbox+/demos/checkbox-disabled-demo"
import {CheckboxReactHookFormDemo as ReactHookFormDemo} from "@qualcomm-ui/react-docs/components+/checkbox+/demos/checkbox-react-hook-form-demo"
import {CheckboxSimpleDemo as SimpleDemo} from "@qualcomm-ui/react-docs/components+/checkbox+/demos/checkbox-simple-demo"
import {CheckboxSizesDemo as SizesDemo} from "@qualcomm-ui/react-docs/components+/checkbox+/demos/checkbox-sizes-demo"
import {CheckboxStatesDemo as StatesDemo} from "@qualcomm-ui/react-docs/components+/checkbox+/demos/checkbox-states-demo"
import {CheckboxTanstackFormDemo as TanstackFormDemo} from "@qualcomm-ui/react-docs/components+/checkbox+/demos/checkbox-tanstack-form-demo"

import {DemoPageLayout} from "~/components/demo-page-layout"

const demos = [
  {component: CompositeLayoutDemo, title: "Composite Layout"},
  {component: ControlledDemo, title: "Controlled"},
  {component: DisabledDemo, title: "Disabled"},
  {component: ReactHookFormDemo, title: "React Hook Form"},
  {component: SimpleDemo, title: "Simple"},
  {component: SizesDemo, title: "Sizes"},
  {component: StatesDemo, title: "States"},
  {component: TanstackFormDemo, title: "Tanstack Form"},
]

export default function CheckboxDemos() {
  return <DemoPageLayout componentName="checkbox" demos={demos} />
}
