// packages/debug-apps/angular-ssr/src/app/combobox.ts
import {Component} from "@angular/core"

import {ComboboxAriaLabelDemo} from "@qualcomm-ui/angular-docs/components+/combobox+/demos/combobox-aria-label-demo"
import {ComboboxAsyncDemo} from "@qualcomm-ui/angular-docs/components+/combobox+/demos/combobox-async-demo"
import {ComboboxCompositeDemo} from "@qualcomm-ui/angular-docs/components+/combobox+/demos/combobox-composite-demo"
import {ComboboxControlledStateDemo} from "@qualcomm-ui/angular-docs/components+/combobox+/demos/combobox-controlled-state-demo"
import {ComboboxErrorDemo} from "@qualcomm-ui/angular-docs/components+/combobox+/demos/combobox-error-demo"
import {ComboboxHighlightDemo} from "@qualcomm-ui/angular-docs/components+/combobox+/demos/combobox-highlight-demo"
import {ComboboxHintDemo} from "@qualcomm-ui/angular-docs/components+/combobox+/demos/combobox-hint-demo"
import {ComboboxIconCustomizationDemo} from "@qualcomm-ui/angular-docs/components+/combobox+/demos/combobox-icon-customization-demo"
import {ComboboxIconDemo} from "@qualcomm-ui/angular-docs/components+/combobox+/demos/combobox-icon-demo"
import {ComboboxInputBehaviorDemo} from "@qualcomm-ui/angular-docs/components+/combobox+/demos/combobox-input-behavior-demo"
import {ComboboxItemCustomizationDemo} from "@qualcomm-ui/angular-docs/components+/combobox+/demos/combobox-item-customization-demo"
import {ComboboxItemsDemo} from "@qualcomm-ui/angular-docs/components+/combobox+/demos/combobox-items-demo"
import {ComboboxMaxHeightDemo} from "@qualcomm-ui/angular-docs/components+/combobox+/demos/combobox-max-height-demo"
import {ComboboxMultipleDemo} from "@qualcomm-ui/angular-docs/components+/combobox+/demos/combobox-multiple-demo"
import {ComboboxObjectReactiveFormsDemo} from "@qualcomm-ui/angular-docs/components+/combobox+/demos/combobox-object-reactive-forms-demo"
import {ComboboxObjectTemplateFormsDemo} from "@qualcomm-ui/angular-docs/components+/combobox+/demos/combobox-object-template-forms-demo"
import {ComboboxOpenOnClickDemo} from "@qualcomm-ui/angular-docs/components+/combobox+/demos/combobox-open-on-click-demo"
import {ComboboxReactiveFormStatesDemo} from "@qualcomm-ui/angular-docs/components+/combobox+/demos/combobox-reactive-form-states-demo"
import {ComboboxRequiredTemplateFormsDemo} from "@qualcomm-ui/angular-docs/components+/combobox+/demos/combobox-required-template-forms-demo"
import {ComboboxSameWidthDemo} from "@qualcomm-ui/angular-docs/components+/combobox+/demos/combobox-same-width-demo"
import {ComboboxSimpleDemo} from "@qualcomm-ui/angular-docs/components+/combobox+/demos/combobox-simple-demo"
import {ComboboxSizesDemo} from "@qualcomm-ui/angular-docs/components+/combobox+/demos/combobox-sizes-demo"
import {ComboboxStatesDemo} from "@qualcomm-ui/angular-docs/components+/combobox+/demos/combobox-states-demo"
import {ComboboxStringsReactiveFormsDemo} from "@qualcomm-ui/angular-docs/components+/combobox+/demos/combobox-strings-reactive-forms-demo"
import {ComboboxStringsTemplateFormsDemo} from "@qualcomm-ui/angular-docs/components+/combobox+/demos/combobox-strings-template-forms-demo"
import {ComboboxTemplateFormStateDemo} from "@qualcomm-ui/angular-docs/components+/combobox+/demos/combobox-template-form-state-demo"
import {ComboboxVirtualDemo} from "@qualcomm-ui/angular-docs/components+/combobox+/demos/combobox-virtual-demo"
import {ComboboxVirtualItemCustomizationDemo} from "@qualcomm-ui/angular-docs/components+/combobox+/demos/combobox-virtual-item-customization-demo"
import {ComboboxWithinDialogDemo} from "@qualcomm-ui/angular-docs/components+/combobox+/demos/combobox-within-dialog-demo"
import {ComboboxWithinPopoverDemo} from "@qualcomm-ui/angular-docs/components+/combobox+/demos/combobox-within-popover-demo"

@Component({
  imports: [
    ComboboxAriaLabelDemo,
    ComboboxAsyncDemo,
    ComboboxCompositeDemo,
    ComboboxControlledStateDemo,
    ComboboxErrorDemo,
    ComboboxHighlightDemo,
    ComboboxHintDemo,
    ComboboxIconCustomizationDemo,
    ComboboxIconDemo,
    ComboboxInputBehaviorDemo,
    ComboboxItemCustomizationDemo,
    ComboboxItemsDemo,
    ComboboxMaxHeightDemo,
    ComboboxMultipleDemo,
    ComboboxObjectReactiveFormsDemo,
    ComboboxObjectTemplateFormsDemo,
    ComboboxOpenOnClickDemo,
    ComboboxReactiveFormStatesDemo,
    ComboboxRequiredTemplateFormsDemo,
    ComboboxSameWidthDemo,
    ComboboxSimpleDemo,
    ComboboxSizesDemo,
    ComboboxStatesDemo,
    ComboboxStringsReactiveFormsDemo,
    ComboboxStringsTemplateFormsDemo,
    ComboboxTemplateFormStateDemo,
    ComboboxVirtualDemo,
    ComboboxVirtualItemCustomizationDemo,
    ComboboxWithinDialogDemo,
    ComboboxWithinPopoverDemo,
  ],
  selector: "app-combobox",
  styles: `
    .section {
      margin-bottom: 3rem;
    }

    .section-title {
      font: var(--font-static-heading-md-default);
      margin-bottom: 1rem;
      color: var(--color-text-neutral-primary);
    }

    .demo-container {
      padding: 2rem;
      border: 1px solid var(--color-border-neutral-01);
      border-radius: 8px;
      background-color: var(--color-background-neutral-01);
    }
  `,
  template: `
    <div
      class="container"
      style="max-width: 1200px; margin: 0 auto; padding: 2rem;"
    >
      <div class="section">
        <h2 class="section-title">Aria Label</h2>
        <div class="demo-container">
          <combobox-aria-label-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Async</h2>
        <div class="demo-container">
          <combobox-async-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Composite</h2>
        <div class="demo-container">
          <combobox-composite-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Controlled State</h2>
        <div class="demo-container">
          <combobox-controlled-state-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Error</h2>
        <div class="demo-container">
          <combobox-error-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Highlight</h2>
        <div class="demo-container">
          <combobox-highlight-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Hint</h2>
        <div class="demo-container">
          <combobox-hint-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Icon Customization</h2>
        <div class="demo-container">
          <combobox-icon-customization-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Icon</h2>
        <div class="demo-container">
          <combobox-icon-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Input Behavior</h2>
        <div class="demo-container">
          <combobox-input-behavior-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Item Customization</h2>
        <div class="demo-container">
          <combobox-item-customization-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Items</h2>
        <div class="demo-container">
          <combobox-items-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Max Height</h2>
        <div class="demo-container">
          <combobox-max-height-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Multiple</h2>
        <div class="demo-container">
          <combobox-multiple-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Object Reactive Forms</h2>
        <div class="demo-container">
          <combobox-object-reactive-forms-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Object Template Forms</h2>
        <div class="demo-container">
          <combobox-object-template-forms-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Open On Click</h2>
        <div class="demo-container">
          <combobox-open-on-click-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Reactive Form States</h2>
        <div class="demo-container">
          <combobox-reactive-form-states-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Required Template Forms</h2>
        <div class="demo-container">
          <combobox-required-template-forms-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Same Width</h2>
        <div class="demo-container">
          <combobox-same-width-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Simple</h2>
        <div class="demo-container">
          <combobox-simple-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Sizes</h2>
        <div class="demo-container">
          <combobox-sizes-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">States</h2>
        <div class="demo-container">
          <combobox-states-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Strings Reactive Forms</h2>
        <div class="demo-container">
          <combobox-strings-reactive-forms-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Strings Template Forms</h2>
        <div class="demo-container">
          <combobox-strings-template-forms-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Template Form State</h2>
        <div class="demo-container">
          <combobox-template-form-state-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Virtual</h2>
        <div class="demo-container">
          <combobox-virtual-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Virtual Item Customization</h2>
        <div class="demo-container">
          <combobox-virtual-item-customization-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Within Dialog</h2>
        <div class="demo-container">
          <combobox-within-dialog-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Within Popover</h2>
        <div class="demo-container">
          <combobox-within-popover-demo />
        </div>
      </div>
    </div>
  `,
})
export class ComboboxPage {}

// packages/debug-apps/react-ssr/src/routes/components+/combobox.tsx
import {ComboboxAriaLabelDemo as AriaLabelDemo} from "@qualcomm-ui/react-docs/components+/combobox+/demos/combobox-aria-label-demo"
import {ComboboxAsyncDemo as AsyncDemo} from "@qualcomm-ui/react-docs/components+/combobox+/demos/combobox-async-demo"
import {ComboboxCompositeDemo as CompositeDemo} from "@qualcomm-ui/react-docs/components+/combobox+/demos/combobox-composite-demo"
import {ComboboxControlledStateDemo as ControlledStateDemo} from "@qualcomm-ui/react-docs/components+/combobox+/demos/combobox-controlled-state-demo"
import {ComboboxErrorDemo as ErrorDemo} from "@qualcomm-ui/react-docs/components+/combobox+/demos/combobox-error-demo"
import {ComboboxHighlightDemo as HighlightDemo} from "@qualcomm-ui/react-docs/components+/combobox+/demos/combobox-highlight-demo"
import {ComboboxHintDemo as HintDemo} from "@qualcomm-ui/react-docs/components+/combobox+/demos/combobox-hint-demo"
import {ComboboxHookFormDemo as HookFormDemo} from "@qualcomm-ui/react-docs/components+/combobox+/demos/combobox-hook-form-demo"
import {ComboboxIconCustomizationDemo as IconCustomizationDemo} from "@qualcomm-ui/react-docs/components+/combobox+/demos/combobox-icon-customization-demo"
import {ComboboxIconDemo as IconDemo} from "@qualcomm-ui/react-docs/components+/combobox+/demos/combobox-icon-demo"
import {ComboboxInputBehaviorDemo as InputBehaviorDemo} from "@qualcomm-ui/react-docs/components+/combobox+/demos/combobox-input-behavior-demo"
import {ComboboxItemsDemo as ItemsDemo} from "@qualcomm-ui/react-docs/components+/combobox+/demos/combobox-items-demo"
import {ComboboxMaxHeightDemo as MaxHeightDemo} from "@qualcomm-ui/react-docs/components+/combobox+/demos/combobox-max-height-demo"
import {ComboboxMultiFieldSearchDemo as MultiFieldSearchDemo} from "@qualcomm-ui/react-docs/components+/combobox+/demos/combobox-multi-field-search-demo"
import {ComboboxMultipleDemo as MultipleDemo} from "@qualcomm-ui/react-docs/components+/combobox+/demos/combobox-multiple-demo"
import {ComboboxOpenOnClickDemo as OpenOnClickDemo} from "@qualcomm-ui/react-docs/components+/combobox+/demos/combobox-open-on-click-demo"
import {ComboboxRenderItemDemo as RenderItemDemo} from "@qualcomm-ui/react-docs/components+/combobox+/demos/combobox-render-item-demo"
import {ComboboxSameWidthDemo as SameWidthDemo} from "@qualcomm-ui/react-docs/components+/combobox+/demos/combobox-same-width-demo"
import {ComboboxSimpleDemo as SimpleDemo} from "@qualcomm-ui/react-docs/components+/combobox+/demos/combobox-simple-demo"
import {ComboboxSizesDemo as SizesDemo} from "@qualcomm-ui/react-docs/components+/combobox+/demos/combobox-sizes-demo"
import {ComboboxStatesDemo as StatesDemo} from "@qualcomm-ui/react-docs/components+/combobox+/demos/combobox-states-demo"
import {ComboboxTanstackFormDemo as TanstackFormDemo} from "@qualcomm-ui/react-docs/components+/combobox+/demos/combobox-tanstack-form-demo"
import {ComboboxVirtualDemo as VirtualDemo} from "@qualcomm-ui/react-docs/components+/combobox+/demos/combobox-virtual-demo"
import {ComboboxWithinDialogDemo as WithinDialogDemo} from "@qualcomm-ui/react-docs/components+/combobox+/demos/combobox-within-dialog-demo"
import {ComboboxWithinPopoverDemo as WithinPopoverDemo} from "@qualcomm-ui/react-docs/components+/combobox+/demos/combobox-within-popover-demo"

import {DemoPageLayout} from "~/components/demo-page-layout"

const demos = [
  {component: AriaLabelDemo, title: "Aria Label"},
  {component: AsyncDemo, title: "Async"},
  {component: CompositeDemo, title: "Composite"},
  {component: ControlledStateDemo, title: "Controlled State"},
  {component: ErrorDemo, title: "Error"},
  {component: HighlightDemo, title: "Highlight"},
  {component: HintDemo, title: "Hint"},
  {component: HookFormDemo, title: "Hook Form"},
  {component: IconCustomizationDemo, title: "Icon Customization"},
  {component: IconDemo, title: "Icon"},
  {component: InputBehaviorDemo, title: "Input Behavior"},
  {component: ItemsDemo, title: "Items"},
  {component: MaxHeightDemo, title: "Max Height"},
  {component: MultiFieldSearchDemo, title: "Multi Field Search"},
  {component: MultipleDemo, title: "Multiple"},
  {component: OpenOnClickDemo, title: "Open On Click"},
  {component: RenderItemDemo, title: "Render Item"},
  {component: SameWidthDemo, title: "Same Width"},
  {component: SimpleDemo, title: "Simple"},
  {component: SizesDemo, title: "Sizes"},
  {component: StatesDemo, title: "States"},
  {component: TanstackFormDemo, title: "Tanstack Form"},
  {component: VirtualDemo, title: "Virtual"},
  {component: WithinDialogDemo, title: "Within Dialog"},
  {component: WithinPopoverDemo, title: "Within Popover"},
]

export default function ComboboxDemos() {
  return <DemoPageLayout componentName="combobox" demos={demos} />
}
