// packages/debug-apps/angular-ssr/src/app/components/tag.ts
import {Component} from "@angular/core"

import {TagEmphasisDemo} from "@qualcomm-ui/angular-docs/components+/tag+/demos/tag-emphasis-demo"
import {TagIconsDemo} from "@qualcomm-ui/angular-docs/components+/tag+/demos/tag-icons-demo"
import {TagShapeDemo} from "@qualcomm-ui/angular-docs/components+/tag+/demos/tag-shape-demo"
import {TagSizesDemo} from "@qualcomm-ui/angular-docs/components+/tag+/demos/tag-sizes-demo"
import {TagStatesDemo} from "@qualcomm-ui/angular-docs/components+/tag+/demos/tag-states-demo"
import {TagVariantsDemo} from "@qualcomm-ui/angular-docs/components+/tag+/demos/tag-variants-demo"

@Component({
  imports: [
    TagEmphasisDemo,
    TagIconsDemo,
    TagShapeDemo,
    TagSizesDemo,
    TagStatesDemo,
    TagVariantsDemo,
  ],
  selector: "app-tag",
  template: `
    <div class="container">
      <div class="section">
        <h2 class="section-title">Emphasis</h2>
        <div class="demo-container">
          <tag-emphasis-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Icons</h2>
        <div class="demo-container">
          <tag-icons-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Shape</h2>
        <div class="demo-container">
          <tag-shape-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Sizes</h2>
        <div class="demo-container">
          <tag-sizes-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">States</h2>
        <div class="demo-container">
          <tag-states-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Variants</h2>
        <div class="demo-container">
          <tag-variants-demo />
        </div>
      </div>
    </div>
  `,
})
export class TagPage {}

// packages/debug-apps/react-ssr/src/routes/components+/tag.tsx
import {TagEmphasisDemo as EmphasisDemo} from "@qualcomm-ui/react-docs/components+/tag+/demos/tag-emphasis-demo"
import {TagIconsDemo as IconsDemo} from "@qualcomm-ui/react-docs/components+/tag+/demos/tag-icons-demo"
import {TagShapeDemo as ShapeDemo} from "@qualcomm-ui/react-docs/components+/tag+/demos/tag-shape-demo"
import {TagSizesDemo as SizesDemo} from "@qualcomm-ui/react-docs/components+/tag+/demos/tag-sizes-demo"
import {TagStatesDemo as StatesDemo} from "@qualcomm-ui/react-docs/components+/tag+/demos/tag-states-demo"
import {TagVariantsDemo as VariantsDemo} from "@qualcomm-ui/react-docs/components+/tag+/demos/tag-variants-demo"

import {DemoPageLayout} from "~/components/demo-page-layout"

const demos = [
  {component: EmphasisDemo, title: "Emphasis"},
  {component: IconsDemo, title: "Icons"},
  {component: ShapeDemo, title: "Shape"},
  {component: SizesDemo, title: "Sizes"},
  {component: StatesDemo, title: "States"},
  {component: VariantsDemo, title: "Variants"},
]

export default function TagDemos() {
  return <DemoPageLayout componentName="tag" demos={demos} />
}
