// packages/debug-apps/angular-csr/src/app/components/tag.ts
import {Component} from "@angular/core"

import {TagEmphasisDemo} from "@qualcomm-ui/angular-docs/components+/tag+/demos/tag-emphasis-demo"
import {TagIconsDemo} from "@qualcomm-ui/angular-docs/components+/tag+/demos/tag-icons-demo"
import {TagRadiusDemo} from "@qualcomm-ui/angular-docs/components+/tag+/demos/tag-radius-demo"
import {TagSizesDemo} from "@qualcomm-ui/angular-docs/components+/tag+/demos/tag-sizes-demo"
import {TagStatesDemo} from "@qualcomm-ui/angular-docs/components+/tag+/demos/tag-states-demo"
import {TagVariantsDemo} from "@qualcomm-ui/angular-docs/components+/tag+/demos/tag-variants-demo"

@Component({
  imports: [
    TagEmphasisDemo,
    TagIconsDemo,
    TagRadiusDemo,
    TagSizesDemo,
    TagStatesDemo,
    TagVariantsDemo,
  ],
  selector: "app-tag",
  template: `
    <div class="container">
      <div class="section">
        <h2 class="section-title">Emphasis</h2>
        <div class="demo-container">
          <tag-emphasis-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Icons</h2>
        <div class="demo-container">
          <tag-icons-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Radius</h2>
        <div class="demo-container">
          <tag-radius-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Sizes</h2>
        <div class="demo-container">
          <tag-sizes-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">States</h2>
        <div class="demo-container">
          <tag-states-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Variants</h2>
        <div class="demo-container">
          <tag-variants-demo />
        </div>
      </div>
    </div>
  `,
})
export class TagPage {}

// packages/debug-apps/react-ssr/src/routes/components+/tag+/_tag.tsx
import EmphasisDemo from "@qualcomm-ui/react-docs/components+/tag+/demos/tag-emphasis-demo"
import IconsDemo from "@qualcomm-ui/react-docs/components+/tag+/demos/tag-icons-demo"
import RadiusDemo from "@qualcomm-ui/react-docs/components+/tag+/demos/tag-radius-demo"
import SizesDemo from "@qualcomm-ui/react-docs/components+/tag+/demos/tag-sizes-demo"
import StatesDemo from "@qualcomm-ui/react-docs/components+/tag+/demos/tag-states-demo"
import VariantsDemo from "@qualcomm-ui/react-docs/components+/tag+/demos/tag-variants-demo"

const demos = [
  {component: EmphasisDemo, title: "Emphasis"},
  {component: IconsDemo, title: "Icons"},
  {component: RadiusDemo, title: "Radius"},
  {component: SizesDemo, title: "Sizes"},
  {component: StatesDemo, title: "States"},
  {component: VariantsDemo, title: "Variants"},
]

export default function TagDemos() {
  return (
    <div className="page">
      {demos.map(({component: Demo, title}) => (
        <div className="section" key={title}>
          <h2 className="section-title">{title}</h2>
          <div className="demo-container">
            <Demo />
          </div>
        </div>
      ))}
    </div>
  )
}
