// packages/frameworks/angular/src/date-picker/date-picker-prev-trigger.component.ts
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import {Component, computed} from "@angular/core"
import {LucideChevronLeft} from "@lucide/angular"

import {CoreDatePickerPrevTriggerDirective} from "@qualcomm-ui/angular-core/date-picker"
import {provideIcons} from "@qualcomm-ui/angular-core/lucide"
import {useIconButtonApi} from "@qualcomm-ui/angular/button"
import {mergeProps} from "@qualcomm-ui/utils/merge-props"

import {useQdsDatePickerContext} from "./qds-date-picker-context.service"

/**
 * Moves the calendar to the previous page. Styled as a ghost icon button.
 */
@Component({
  providers: [provideIcons({LucideChevronLeft})],
  selector: "[q-date-picker-prev-trigger]",
  standalone: false,
  template: `
    <ng-content>
      <svg
        qIcon="LucideChevronLeft"
        [q-bind]="iconButtonApi().getIconBindings()"
      ></svg>
    </ng-content>
  `,
})
export class DatePickerPrevTriggerDirective extends CoreDatePickerPrevTriggerDirective {
  protected readonly qdsContext = useQdsDatePickerContext()

  protected readonly iconButtonApi = useIconButtonApi({
    density: "compact",
    disabled: computed(() => !!this.coreBindings().disabled),
    size: "md",
    variant: "ghost",
  })

  constructor() {
    super()
    this.trackBindings.extendWith(
      computed(() =>
        mergeProps(
          this.qdsContext().getPrevTriggerBindings(),
          this.iconButtonApi().getRootBindings(),
        ),
      ),
    )
  }
}

// packages/frameworks/react/src/date-picker/date-picker-prev-trigger.tsx
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import type {ReactElement} from "react"

import {ChevronLeft} from "lucide-react"

import {
  CoreDatePicker,
  type CoreDatePickerPrevTriggerProps,
} from "@qualcomm-ui/react-core/date-picker"
import type {LucideIconOrElement} from "@qualcomm-ui/react-core/lucide"
import {IconButton} from "@qualcomm-ui/react/button"
import {mergeProps} from "@qualcomm-ui/utils/merge-props"

import {useQdsDatePickerContext} from "./qds-date-picker-context.js"

export interface DatePickerPrevTriggerProps extends CoreDatePickerPrevTriggerProps {
  /**
   * Icon to render. Accepts a `LucideIcon` or a `ReactElement`.
   *
   * @default ChevronLeft
   */
  icon?: LucideIconOrElement
}

/**
 * Moves the calendar to the previous page. Styled as a ghost {@link IconButton}.
 */
export function DatePickerPrevTrigger({
  icon = ChevronLeft,
  render,
  ...props
}: DatePickerPrevTriggerProps): ReactElement {
  const qdsContext = useQdsDatePickerContext()
  const mergedProps = mergeProps(qdsContext.getPrevTriggerBindings(), props)

  return (
    <CoreDatePicker.PrevTrigger
      {...mergedProps}
      render={
        <IconButton
          density="compact"
          icon={icon}
          render={render}
          size="md"
          variant="ghost"
        />
      }
    />
  )
}
