// packages/debug-apps/angular-ssr/src/app/components/slider.ts
import {Component} from "@angular/core"

@Component({
  selector: "app-slider",
  styles: `
    .container {
      max-width: 1200px;
      margin: 0 auto;
      padding: 2rem;
    }

    .message {
      font: var(--font-static-body-lg-default);
      color: var(--color-text-neutral-secondary);
      text-align: center;
      padding: 4rem 2rem;
    }
  `,
  template: `
    <div
      class="container"
      style="max-width: 1200px; margin: 0 auto; padding: 2rem;"
    >
      <div class="section">
        <h2 class="section-title">Simple</h2>
        <div class="demo-container">
          <slider-simple-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Variant</h2>
        <div class="demo-container">
          <slider-variant-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Size</h2>
        <div class="demo-container">
          <slider-size-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Hint</h2>
        <div class="demo-container">
          <slider-hint-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Disabled</h2>
        <div class="demo-container">
          <slider-disabled-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Range</h2>
        <div class="demo-container">
          <slider-range-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Min Max Step</h2>
        <div class="demo-container">
          <slider-min-max-step-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Min Steps</h2>
        <div class="demo-container">
          <slider-min-steps-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Origin</h2>
        <div class="demo-container">
          <slider-origin-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Markers</h2>
        <div class="demo-container">
          <slider-markers-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Side Markers</h2>
        <div class="demo-container">
          <slider-side-markers-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Display</h2>
        <div class="demo-container">
          <slider-display-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Tooltip</h2>
        <div class="demo-container">
          <slider-tooltip-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Composite</h2>
        <div class="demo-container">
          <slider-composite-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Template Forms</h2>
        <div class="demo-container">
          <slider-template-forms-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Template Form State</h2>
        <div class="demo-container">
          <slider-template-form-state-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Reactive Form States</h2>
        <div class="demo-container">
          <slider-reactive-form-states-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Value Callback</h2>
        <div class="demo-container">
          <slider-value-callback-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Focus Callback</h2>
        <div class="demo-container">
          <slider-focus-callback-demo />
        </div>
      </div>
    </div>
  `,
})
export class SliderPage {}

// packages/debug-apps/react-ssr/src/routes/components+/slider+/_slider.tsx
import CompositeDemo from "./demos/slider-composite-demo"
import DisabledDemo from "./demos/slider-disabled-demo"
import DisplayDemo from "./demos/slider-display-demo"
import FocusCallbackDemo from "./demos/slider-focus-callback-demo"
import HintDemo from "./demos/slider-hint-demo"
import MarkersDemo from "./demos/slider-markers-demo"
import MinMaxStepDemo from "./demos/slider-min-max-step-demo"
import MinStepsDemo from "./demos/slider-min-steps-demo"
import OriginDemo from "./demos/slider-origin-demo"
import RangeDemo from "./demos/slider-range-demo"
import ReactHookFormDemo from "./demos/slider-react-hook-form-demo"
import SideMarkersDemo from "./demos/slider-side-markers-demo"
import SimpleDemo from "./demos/slider-simple-demo"
import SizeDemo from "./demos/slider-size-demo"
import TanstackFormDemo from "./demos/slider-tanstack-form-demo"
import TooltipDemo from "./demos/slider-tooltip-demo"
import ValueCallbackDemo from "./demos/slider-value-callback-demo"
import VariantDemo from "./demos/slider-variant-demo"
import VerticalDemo from "./demos/slider-vertical-demo"

const demos = [
  {component: CompositeDemo, title: "Composite"},
  {component: DisabledDemo, title: "Disabled"},
  {component: DisplayDemo, title: "Display"},
  {component: FocusCallbackDemo, title: "Focus Callback"},
  {component: HintDemo, title: "Hint"},
  {component: MarkersDemo, title: "Markers"},
  {component: MinMaxStepDemo, title: "Min Max Step"},
  {component: MinStepsDemo, title: "Min Steps"},
  {component: OriginDemo, title: "Origin"},
  {component: RangeDemo, title: "Range"},
  {component: ReactHookFormDemo, title: "React Hook Form"},
  {component: SideMarkersDemo, title: "Side Markers"},
  {component: SimpleDemo, title: "Simple"},
  {component: SizeDemo, title: "Size"},
  {component: TanstackFormDemo, title: "Tanstack Form"},
  {component: TooltipDemo, title: "Tooltip"},
  {component: ValueCallbackDemo, title: "Value Callback"},
  {component: VariantDemo, title: "Variant"},
  {component: VerticalDemo, title: "Vertical"},
]

export default function SliderDemos() {
  return (
    <div className="page">
      {demos.map(({component: Demo, title}) => (
        <div className="section" key={title}>
          <h2 className="section-title">{title}</h2>
          <div className="demo-container">
            <Demo />
          </div>
        </div>
      ))}
    </div>
  )
}
