// packages/docs/angular-docs/src/routes/components+/button+/demos/button-density-demo.ts
import {Component} from "@angular/core"
import {ExternalLink} from "lucide-angular"

import {provideIcons} from "@qualcomm-ui/angular-core/lucide"
import {ButtonModule} from "@qualcomm-ui/angular/button"

@Component({
  imports: [ButtonModule],
  providers: [provideIcons({ExternalLink})],
  selector: "button-density-demo",
  template: `
    <div class="grid justify-items-center gap-4">
      <!-- preview -->
      <button
        density="compact"
        emphasis="primary"
        q-button
        size="sm"
        startIcon="ExternalLink"
        variant="fill"
      >
        Action
      </button>
      <button
        density="compact"
        emphasis="primary"
        q-button
        size="md"
        startIcon="ExternalLink"
        variant="fill"
      >
        Action
      </button>
      <button
        density="compact"
        emphasis="primary"
        q-button
        size="lg"
        startIcon="ExternalLink"
        variant="fill"
      >
        Action
      </button>
      <!-- preview -->
    </div>
  `,
})
export class ButtonDensityDemo {}

// packages/docs/react-docs/src/routes/components+/button+/demos/button-density-demo.tsx
import type {ReactElement} from "react"

import {ExternalLink} from "lucide-react"

import {Button} from "@qualcomm-ui/react/button"

export default function Demo(): ReactElement {
  return (
    <div className="grid justify-items-center gap-4">
      {/* preview */}
      <Button
        density="compact"
        emphasis="primary"
        size="sm"
        startIcon={ExternalLink}
        variant="fill"
      >
        Action
      </Button>
      <Button
        density="compact"
        emphasis="primary"
        size="md"
        startIcon={ExternalLink}
        variant="fill"
      >
        Action
      </Button>
      <Button
        density="compact"
        emphasis="primary"
        size="lg"
        startIcon={ExternalLink}
        variant="fill"
      >
        Action
      </Button>
      {/* preview */}
    </div>
  )
}
