// packages/docs/angular-docs/src/routes/components+/file-upload+/demos/file-upload-sizes-demo.ts
import {Component} from "@angular/core"

import {FileUploadModule} from "@qualcomm-ui/angular/file-upload"

@Component({
  imports: [FileUploadModule],
  selector: "file-upload-sizes-demo",
  standalone: true,
  template: `
    <!-- preview -->
    <div class="flex w-full flex-col items-center gap-8">
      <div class="w-full max-w-md">
        <q-file-upload
          dropzoneHint="Supported file types: .jpg, .jpeg, .png, .pdf"
          label="Upload files (Small)"
          size="sm"
          [accept]="['image/png', 'image/jpg', 'image/jpeg', 'application/pdf']"
          [maxFiles]="5"
        />
      </div>

      <div class="w-full max-w-md">
        <q-file-upload
          dropzoneHint="Supported file types: .jpg, .jpeg, .png, .pdf"
          label="Upload files (Medium)"
          size="md"
          [accept]="['image/png', 'image/jpg', 'image/jpeg', 'application/pdf']"
          [maxFiles]="5"
        />
      </div>

      <div class="w-full max-w-md">
        <q-file-upload
          dropzoneHint="Supported file types: .jpg, .jpeg, .png, .pdf"
          label="Upload files (Large)"
          size="lg"
          [accept]="['image/png', 'image/jpg', 'image/jpeg', 'application/pdf']"
          [maxFiles]="5"
        />
      </div>
    </div>
    <!-- preview -->
  `,
})
export class FileUploadSizesDemo {}

// packages/docs/react-docs/src/routes/components+/file-upload+/demos/file-upload-sizes-demo.tsx
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import {FileUpload} from "@qualcomm-ui/react/file-upload"

export function FileUploadSizesDemo() {
  return (
    // preview
    <div className="flex w-full flex-col items-center gap-8">
      <div className="w-full max-w-md">
        <FileUpload
          accept={["image/png", "image/jpg", "image/jpeg", "application/pdf"]}
          dropzoneHint="Supported file types: .jpg, .jpeg, .png, .pdf"
          label="Upload files (Small)"
          maxFiles={5}
          size="sm"
        />
      </div>

      <div className="w-full max-w-md">
        <FileUpload
          accept={["image/png", "image/jpg", "image/jpeg", "application/pdf"]}
          dropzoneHint="Supported file types: .jpg, .jpeg, .png, .pdf"
          label="Upload files (Medium)"
          maxFiles={5}
          size="md"
        />
      </div>

      <div className="w-full max-w-md">
        <FileUpload
          accept={["image/png", "image/jpg", "image/jpeg", "application/pdf"]}
          dropzoneHint="Supported file types: .jpg, .jpeg, .png, .pdf"
          label="Upload files (Large)"
          maxFiles={5}
          size="lg"
        />
      </div>
    </div>
    // preview
  )
}
