// packages/docs/react-docs/src/routes/theming+/typography+/demos/typography-example-demo.tsx
export default function Demo() {
  return (
    <div className="flex flex-col gap-4">
      {/* preview */}
      <div className="font-body-md text-neutral-primary">
        Body, primary color
      </div>

      {/* Or via CSS variables */}
      <div
        style={{
          color: `var(--color-text-neutral-primary)`,
          font: `var(--font-static-body-md-default)`,
        }}
      >
        Body, primary color (css variables)
      </div>
      {/* preview */}
    </div>
  )
}

// packages/docs/angular-docs/src/routes/theming+/typography+/demos/typography-example-demo.ts
import {Component} from "@angular/core"

@Component({
  selector: "typography-example-demo",
  template: `
    <div class="flex flex-col gap-4">
      <!-- preview -->
      <div class="font-body-lg text-neutral-secondary">
        Body large, primary color
      </div>
      <div
        [style]="{
          color: 'var(--color-text-neutral-secondary)',
          font: 'var(--font-static-body-lg-default)',
        }"
      >
        Body large, secondary color (css variables)
      </div>
      <!-- preview -->
    </div>
  `,
})
export class TypographyExampleDemo {}
