// packages/frameworks/react/src/text-input/text-input.tsx
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import type {ReactElement, ReactNode} from "react"

import type {LucideIconOrElement} from "@qualcomm-ui/react-core/lucide"
import {useOptionalContentId} from "@qualcomm-ui/react-core/machine"
import {useControlledId} from "@qualcomm-ui/react-core/state"

import {
  TextInputClearTrigger,
  type TextInputClearTriggerProps,
} from "./text-input-clear-trigger"
import {
  TextInputErrorIndicator,
  type TextInputErrorIndicatorProps,
} from "./text-input-error-indicator"
import {
  TextInputErrorText,
  type TextInputErrorTextProps,
} from "./text-input-error-text"
import {TextInputHint, type TextInputHintProps} from "./text-input-hint"
import {TextInputInput, type TextInputInputProps} from "./text-input-input"
import {
  TextInputInputGroup,
  type TextInputInputGroupProps,
} from "./text-input-input-group"
import {TextInputLabel, type TextInputLabelProps} from "./text-input-label"
import {TextInputRoot, type TextInputRootProps} from "./text-input-root"

export interface TextInputProps extends TextInputRootProps {
  /**
   * The simple TextInput doesn't support children.
   */
  children?: never

  /**
   * When `true`, renders a clear button that resets the input value on click.
   * The button only appears when the input has a value.
   *
   * @default true
   */
  clearable?: boolean

  clearTriggerProps?: TextInputClearTriggerProps

  /**
   * {@link https://lucide.dev lucide-react} icon, positioned after
   * the input. Can be supplied as a `ReactElement` for additional customization.
   */
  endIcon?: LucideIconOrElement

  /**
   * Props applied to the error indicator element.
   */
  errorIndicatorProps?: TextInputErrorIndicatorProps

  /**
   * Optional error that describes the element when {@link invalid} is true.
   */
  errorText?: string

  /**
   * Props applied to the error text element.
   */
  errorTextProps?: TextInputErrorTextProps

  /**
   * Optional hint describing the element. This element is automatically
   * associated with the component's input element for accessibility.
   */
  hint?: ReactNode

  /**
   * Props applied to the label element.
   */
  hintProps?: TextInputHintProps

  /**
   * Props applied to the input group element.
   *
   * @inheritDoc
   */
  inputGroupProps?: TextInputInputGroupProps

  /**
   * Props applied to the input element.
   */
  inputProps?: TextInputInputProps

  /**
   * Optional label describing the element. Recommended. This element is
   * automatically associated with the component's input element for
   * accessibility.
   */
  label?: ReactNode

  /**
   * Props applied to the label element.
   */
  labelProps?: TextInputLabelProps

  /**
   * HTML {@link https://www.w3schools.com/tags/att_input_placeholder.asp placeholder} attribute,
   * passed to the underlying input element.
   */
  placeholder?: string

  /**
   * {@link https://lucide.dev lucide-react} icon, positioned before
   * the input. Can be supplied as a `ReactElement` for additional customization.
   */
  startIcon?: LucideIconOrElement
}

export function TextInput({
  clearable = true,
  clearTriggerProps,
  errorIndicatorProps,
  errorText,
  errorTextProps,
  hint,
  hintProps,
  inputGroupProps,
  inputProps,
  label,
  labelProps,
  placeholder,
  ...props
}: TextInputProps): ReactElement {
  const labelContent = label || labelProps?.children
  const errorTextContent = errorText || errorTextProps?.children
  const hintContent = hint || hintProps?.children

  const ids = {
    errorText: useOptionalContentId(errorTextContent, errorTextProps),
    hint: useOptionalContentId(hintContent, hintProps),
    input: useControlledId(inputProps?.id),
    label: useOptionalContentId(labelContent, labelProps),
    ...props.ids,
  }

  return (
    <TextInputRoot {...props} ids={ids}>
      {labelContent ? (
        <TextInputLabel {...labelProps} id={ids.label}>
          {labelContent}
        </TextInputLabel>
      ) : null}

      <TextInputInputGroup {...inputGroupProps}>
        <TextInputInput
          placeholder={placeholder}
          {...inputProps}
          id={ids.input}
        />
        {clearable ? <TextInputClearTrigger {...clearTriggerProps} /> : null}
        <TextInputErrorIndicator {...errorIndicatorProps} />
      </TextInputInputGroup>

      {hintContent ? (
        <TextInputHint {...hintProps} id={ids.hint}>
          {hintContent}
        </TextInputHint>
      ) : null}

      {errorTextContent ? (
        <TextInputErrorText {...errorTextProps} id={ids.errorText}>
          {errorTextContent}
        </TextInputErrorText>
      ) : null}
    </TextInputRoot>
  )
}

// packages/frameworks/angular/src/text-input/text-input.component.ts
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import {booleanAttribute, Component, input} from "@angular/core"
import {AlertCircle} from "lucide-angular"

import {provideQdsInputContext} from "@qualcomm-ui/angular/input"
import {provideIcons} from "@qualcomm-ui/angular-core/lucide"
import {provideTextInputContext} from "@qualcomm-ui/angular-core/text-input"
import type {Booleanish} from "@qualcomm-ui/utils/coercion"

import {TextInputRootDirective} from "./text-input-root.directive"

@Component({
  providers: [
    provideTextInputContext(),
    provideQdsInputContext(),
    provideIcons({AlertCircle}),
  ],
  selector: "q-text-input:not([q-text-input-root])",
  standalone: false,
  template: `
    <ng-content select="[q-text-input-label]">
      @if (label()) {
        <label q-text-input-label>{{ label() }}</label>
      }
    </ng-content>
    <div q-text-input-input-group>
      <input q-text-input-input [placeholder]="placeholder()" />

      <ng-content select="[q-text-input-clear-trigger]">
        @if (clearable()) {
          <button q-text-input-clear-trigger></button>
        }
      </ng-content>

      <ng-content select="[q-text-input-error-indicator]">
        <span q-text-input-error-indicator></span>
      </ng-content>
    </div>
    <ng-content select="[q-text-input-hint]">
      @if (hint()) {
        <span q-text-input-hint>
          {{ hint() }}
        </span>
      }
    </ng-content>

    <ng-content select="[q-text-input-error-text]">
      @if (errorText()) {
        <div q-text-input-error-text>
          {{ errorText() }}
        </div>
      }
    </ng-content>
  `,
})
export class TextInputComponent extends TextInputRootDirective {
  /**
   * When `true`, renders a clear button that resets the input value on click.
   * The button only appears when the input has a value.
   *
   * @default true
   */
  readonly clearable = input<boolean | undefined, Booleanish>(true, {
    transform: booleanAttribute,
  })

  /**
   * Optional error that describes the element when {@link invalid} is true.
   *
   * @remarks
   * To customize the element, provide it using the directive instead:
   *
   * ```angular-html
   * <div q-text-input-error-text>...</div>
   * ```
   */
  readonly errorText = input<string | undefined | null>()

  /**
   * Optional hint describing the element. This element is automatically
   * associated with the component's input element for accessibility.
   *
   * @remarks
   * To customize the element, provide it using the directive instead:
   *
   * ```angular-html
   * <div q-text-input-hint>...</div>
   * ```
   */
  readonly hint = input<string | undefined | null>()

  /**
   * Optional label describing the element. Recommended. This element is
   * automatically associated with the component's input element for
   * accessibility.
   *
   * @remarks
   * To customize the element, provide it using the directive instead:
   *
   * ```angular-html
   * <div q-text-input-label>...</div>
   * ```
   */
  readonly label = input<string | undefined>()

  /**
   * HTML {@link https://www.w3schools.com/tags/att_input_placeholder.asp placeholder} attribute,
   * passed to the internal input element.
   */
  readonly placeholder = input<string>("")
}
