// packages/debug-apps/react-ssr/src/routes/components+/progress-ring.tsx
import {ProgressRingCompositeDemo as CompositeDemo} from "@qualcomm-ui/react-docs/components+/progress-ring+/demos/progress-ring-composite-demo"
import {ProgressRingSimpleDemo as SimpleDemo} from "@qualcomm-ui/react-docs/components+/progress-ring+/demos/progress-ring-simple-demo"
import {ProgressRingSizesDemo as SizesDemo} from "@qualcomm-ui/react-docs/components+/progress-ring+/demos/progress-ring-sizes-demo"
import {ProgressRingThicknessDemo as ThicknessDemo} from "@qualcomm-ui/react-docs/components+/progress-ring+/demos/progress-ring-thickness-demo"
import {ProgressRingValueDemo as ValueDemo} from "@qualcomm-ui/react-docs/components+/progress-ring+/demos/progress-ring-value-demo"
import {ProgressRingValueTextDemo as ValueTextDemo} from "@qualcomm-ui/react-docs/components+/progress-ring+/demos/progress-ring-value-text-demo"

import {DemoPageLayout} from "~/components/demo-page-layout"

const demos = [
  {component: CompositeDemo, title: "Composite"},
  {component: SimpleDemo, title: "Simple"},
  {component: SizesDemo, title: "Sizes"},
  {component: ThicknessDemo, title: "Thickness"},
  {component: ValueDemo, title: "Value"},
  {component: ValueTextDemo, title: "Value Text"},
]

export default function ProgressRingDemos() {
  return <DemoPageLayout componentName="progress-ring" demos={demos} />
}

// packages/debug-apps/angular-ssr/src/app/progress-ring.ts
import {Component} from "@angular/core"

import {ProgressRingChildDirectivesDemo} from "@qualcomm-ui/angular-docs/components+/progress-ring+/demos/progress-ring-child-directives-demo"
import {ProgressRingCompositeDemo} from "@qualcomm-ui/angular-docs/components+/progress-ring+/demos/progress-ring-composite-demo"
import {ProgressRingSimpleDemo} from "@qualcomm-ui/angular-docs/components+/progress-ring+/demos/progress-ring-simple-demo"
import {ProgressRingSizesDemo} from "@qualcomm-ui/angular-docs/components+/progress-ring+/demos/progress-ring-sizes-demo"
import {ProgressRingThicknessDemo} from "@qualcomm-ui/angular-docs/components+/progress-ring+/demos/progress-ring-thickness-demo"
import {ProgressRingValueDemo} from "@qualcomm-ui/angular-docs/components+/progress-ring+/demos/progress-ring-value-demo"
import {ProgressRingValueTextDemo} from "@qualcomm-ui/angular-docs/components+/progress-ring+/demos/progress-ring-value-text-demo"

@Component({
  imports: [
    ProgressRingChildDirectivesDemo,
    ProgressRingCompositeDemo,
    ProgressRingSimpleDemo,
    ProgressRingSizesDemo,
    ProgressRingThicknessDemo,
    ProgressRingValueDemo,
    ProgressRingValueTextDemo,
  ],
  selector: "app-progress-ring",
  styles: `
    .section {
      margin-bottom: 3rem;
    }

    .section-title {
      font: var(--font-static-heading-md-default);
      margin-bottom: 1rem;
      color: var(--color-text-neutral-primary);
    }

    .demo-container {
      padding: 2rem;
      border: 1px solid var(--color-border-neutral-01);
      border-radius: 8px;
      background-color: var(--color-background-neutral-01);
    }
  `,
  template: `
    <div
      class="container"
      style="max-width: 1200px; margin: 0 auto; padding: 2rem;"
    >
      <div class="section">
        <h2 class="section-title">Child Directives</h2>
        <div class="demo-container">
          <progress-ring-child-directives-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Composite</h2>
        <div class="demo-container">
          <progress-ring-composite-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Simple</h2>
        <div class="demo-container">
          <progress-ring-simple-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Sizes</h2>
        <div class="demo-container">
          <progress-ring-sizes-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Thickness</h2>
        <div class="demo-container">
          <progress-ring-thickness-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Value</h2>
        <div class="demo-container">
          <progress-ring-value-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Value Text</h2>
        <div class="demo-container">
          <progress-ring-value-text-demo />
        </div>
      </div>
    </div>
  `,
})
export class ProgressRingPage {}
