// packages/debug-apps/react-ssr/src/routes/components+/radio.tsx
import {RadioCompositeDemo as CompositeDemo} from "@qualcomm-ui/react-docs/components+/radio+/demos/radio-composite-demo"
import {RadioCompositeLayoutDemo as CompositeLayoutDemo} from "@qualcomm-ui/react-docs/components+/radio+/demos/radio-composite-layout-demo"
import {RadioControlledDemo as ControlledDemo} from "@qualcomm-ui/react-docs/components+/radio+/demos/radio-controlled-demo"
import {RadioDisabledDemo as DisabledDemo} from "@qualcomm-ui/react-docs/components+/radio+/demos/radio-disabled-demo"
import {RadioOrientationDemo as OrientationDemo} from "@qualcomm-ui/react-docs/components+/radio+/demos/radio-orientation-demo"
import {RadioReactHookFormDemo as ReactHookFormDemo} from "@qualcomm-ui/react-docs/components+/radio+/demos/radio-react-hook-form-demo"
import {RadioSimpleDemo as SimpleDemo} from "@qualcomm-ui/react-docs/components+/radio+/demos/radio-simple-demo"
import {RadioSizesDemo as SizesDemo} from "@qualcomm-ui/react-docs/components+/radio+/demos/radio-sizes-demo"
import {RadioTanstackFormDemo as TanstackFormDemo} from "@qualcomm-ui/react-docs/components+/radio+/demos/radio-tanstack-form-demo"

import {DemoPageLayout} from "~/components/demo-page-layout"

const demos = [
  {component: CompositeDemo, title: "Composite"},
  {component: CompositeLayoutDemo, title: "Composite Layout"},
  {component: ControlledDemo, title: "Controlled"},
  {component: DisabledDemo, title: "Disabled"},
  {component: OrientationDemo, title: "Orientation"},
  {component: ReactHookFormDemo, title: "React Hook Form"},
  {component: SimpleDemo, title: "Simple"},
  {component: SizesDemo, title: "Sizes"},
  {component: TanstackFormDemo, title: "Tanstack Form"},
]

export default function RadioDemos() {
  return <DemoPageLayout componentName="radio" demos={demos} />
}

// packages/debug-apps/angular-ssr/src/app/radio.ts
import {Component} from "@angular/core"

import {RadioChildDirectivesDemo} from "@qualcomm-ui/angular-docs/components/radio/demos/radio-child-directives-demo"
import {RadioCompositeDemo} from "@qualcomm-ui/angular-docs/components/radio/demos/radio-composite-demo"
import {RadioCompositeLayoutDemo} from "@qualcomm-ui/angular-docs/components/radio/demos/radio-composite-layout-demo"
import {RadioDisabledDemo} from "@qualcomm-ui/angular-docs/components/radio/demos/radio-disabled-demo"
import {RadioOrientationDemo} from "@qualcomm-ui/angular-docs/components/radio/demos/radio-orientation-demo"
import {RadioReactiveFormsDemo} from "@qualcomm-ui/angular-docs/components/radio/demos/radio-reactive-forms-demo"
import {RadioSimpleDemo} from "@qualcomm-ui/angular-docs/components/radio/demos/radio-simple-demo"
import {RadioSizesDemo} from "@qualcomm-ui/angular-docs/components/radio/demos/radio-sizes-demo"
import {RadioTemplateFormsDemo} from "@qualcomm-ui/angular-docs/components/radio/demos/radio-template-forms-demo"

@Component({
  imports: [RadioChildDirectivesDemo, RadioCompositeDemo, RadioCompositeLayoutDemo, RadioDisabledDemo, RadioOrientationDemo, RadioReactiveFormsDemo, RadioSimpleDemo, RadioSizesDemo, RadioTemplateFormsDemo],
  selector: "app-radio",
  styles: `
    .section {
      margin-bottom: 3rem;
    }

    .section-title {
      font: var(--font-static-heading-md-default);
      margin-bottom: 1rem;
      color: var(--color-text-neutral-primary);
    }

    .demo-container {
      padding: 2rem;
      border: 1px solid var(--color-border-neutral-01);
      border-radius: 8px;
      background-color: var(--color-background-neutral-01);
    }
  `,
  template: `
    <div
      class="container"
      style="max-width: 1200px; margin: 0 auto; padding: 2rem;"
    >
      <div class="section">
        <h2 class="section-title">Child Directives</h2>
        <div class="demo-container">
          <radio-child-directives-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Composite</h2>
        <div class="demo-container">
          <radio-composite-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Composite Layout</h2>
        <div class="demo-container">
          <radio-composite-layout-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Disabled</h2>
        <div class="demo-container">
          <radio-disabled-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Orientation</h2>
        <div class="demo-container">
          <radio-orientation-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Reactive Forms</h2>
        <div class="demo-container">
          <radio-reactive-forms-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Simple</h2>
        <div class="demo-container">
          <radio-simple-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Sizes</h2>
        <div class="demo-container">
          <radio-sizes-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Template Forms</h2>
        <div class="demo-container">
          <radio-template-forms-demo />
        </div>
      </div>
    </div>
  `,
})
export class RadioPage {}
