// packages/frameworks/react/src/json-viewer/json-viewer-node.tsx
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import type {ReactElement, ReactNode} from "react"

import {Tree} from "@qualcomm-ui/react/tree"
import type {LucideIconOrNode} from "@qualcomm-ui/react-core/lucide"
import {useTreeContext} from "@qualcomm-ui/react-core/tree"
import {
  getAccessibleDescription,
  getPreviewOptions,
  type JsonNode,
  type JsonNodeHastElement,
  jsonNodeToElement,
  keyPathToKey,
} from "@qualcomm-ui/utils/json-tree"

import {useJsonViewerOptions} from "./json-viewer-context"
import {JsonViewerKeyNode} from "./json-viewer-key-node"
import {JsonViewerValueNode} from "./json-viewer-value-node"

export interface JsonViewerNodeBaseProps {
  /**
   * Icon used for the branch expand/collapse trigger.
   */
  arrow?: LucideIconOrNode

  /**
   * Whether to render vertical indent guide lines for nested levels.
   */
  indentGuide?: boolean

  /**
   * Custom render function for value nodes.
   *
   * @inheritDoc
   */
  renderValue?: (node: JsonNodeHastElement) => ReactNode
}

export interface JsonViewerNodeProps extends JsonViewerNodeBaseProps {
  indexPath: number[]
  node: JsonNode
}

export function JsonViewerNode({
  arrow,
  indentGuide,
  indexPath,
  node,
  renderValue,
}: JsonViewerNodeProps): ReactElement {
  const treeContext = useTreeContext()
  const jsonOptions = useJsonViewerOptions() ?? {}
  const previewOptions = getPreviewOptions(jsonOptions)
  const nodeState = treeContext.getNodeState({indexPath, node})

  const key = keyPathToKey(node.keyPath, {excludeRoot: true})
  const hastElement = jsonNodeToElement(node, previewOptions)
  const description = getAccessibleDescription(node, previewOptions)

  if (nodeState.isBranch) {
    return (
      <Tree.NodeProvider indexPath={indexPath} node={node}>
        <Tree.Branch>
          <Tree.BranchNode aria-label={description}>
            {arrow != null && <Tree.BranchTrigger icon={arrow} />}
            <Tree.NodeText>
              {key && (
                <JsonViewerKeyNode
                  node={node}
                  showQuotes={jsonOptions.quotesOnKeys}
                />
              )}
              <JsonViewerValueNode
                node={hastElement}
                renderValue={renderValue}
              />
            </Tree.NodeText>
          </Tree.BranchNode>
          <Tree.BranchContent>
            {indentGuide && <Tree.BranchIndentGuide />}
            {node.children?.map((child, i) => (
              <JsonViewerNode
                key={treeContext.collection.getNodeValue(child)}
                arrow={arrow}
                indentGuide={indentGuide}
                indexPath={[...indexPath, i]}
                node={child}
                renderValue={renderValue}
              />
            ))}
          </Tree.BranchContent>
        </Tree.Branch>
      </Tree.NodeProvider>
    )
  }

  return (
    <Tree.NodeProvider indexPath={indexPath} node={node}>
      <Tree.LeafNode aria-label={description}>
        <Tree.NodeText>
          {key && (
            <JsonViewerKeyNode
              node={node}
              showQuotes={jsonOptions.quotesOnKeys}
            />
          )}
          <JsonViewerValueNode node={hastElement} renderValue={renderValue} />
        </Tree.NodeText>
      </Tree.LeafNode>
    </Tree.NodeProvider>
  )
}

// packages/frameworks/angular/src/json-viewer/json-viewer-node.component.ts
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import {Component, computed, inject, input, type OnInit} from "@angular/core"

import type {LucideIconOrString} from "@qualcomm-ui/angular-core/lucide"
import {
  provideTreeNodePropsContext,
  provideTreeNodeStateContext,
  TreeNodePropsContextService,
  TreeNodeStateContextService,
  useTreeContext,
} from "@qualcomm-ui/angular-core/tree"
import {
  getAccessibleDescription,
  getPreviewOptions,
  type JsonNode,
  jsonNodeToElement,
  keyPathToKey,
} from "@qualcomm-ui/utils/json-tree"

import {useJsonViewerOptionsContext} from "./json-viewer-options-context.service"

@Component({
  providers: [provideTreeNodePropsContext(), provideTreeNodeStateContext()],
  selector: "q-json-viewer-node",
  standalone: false,
  template: `
    @if (isBranch()) {
      <div q-tree-branch>
        <div q-tree-branch-node [attr.aria-label]="description()">
          @if (arrow()) {
            <button q-tree-branch-trigger [icon]="arrow()!"></button>
          }
          <span q-tree-node-text>
            @if (key()) {
              <q-json-viewer-key-node
                [node]="node()"
                [showQuotes]="showQuotes()"
              />
            }
            <q-json-viewer-value-node [node]="hastElement()" />
          </span>
        </div>
        <div q-tree-branch-content>
          @if (indentGuide()) {
            <div q-tree-branch-indent-guide></div>
          }
          @for (
            child of childNodes();
            let i = $index;
            track trackChild(child)
          ) {
            <q-json-viewer-node
              [arrow]="arrow()"
              [indentGuide]="indentGuide()"
              [indexPath]="getChildIndexPath(i)"
              [node]="child"
            />
          }
        </div>
      </div>
    } @else {
      <div q-tree-leaf-node [attr.aria-label]="description()">
        <span q-tree-node-text>
          @if (key()) {
            <q-json-viewer-key-node
              [node]="node()"
              [showQuotes]="showQuotes()"
            />
          }
          <q-json-viewer-value-node [node]="hastElement()" />
        </span>
      </div>
    }
  `,
})
export class JsonViewerNodeComponent implements OnInit {
  readonly indexPath = input.required<number[]>()
  readonly node = input.required<JsonNode>()
  readonly arrow = input<LucideIconOrString>()
  readonly indentGuide = input<boolean>()

  protected readonly treeContext = useTreeContext()
  protected readonly jsonOptions = useJsonViewerOptionsContext()

  protected readonly previewOptions = computed(() =>
    getPreviewOptions(this.jsonOptions() ?? {}),
  )

  private readonly nodeProps = computed(() => ({
    indexPath: this.indexPath(),
    node: this.node(),
  }))

  protected readonly nodeState = computed(() =>
    this.treeContext().getNodeState(this.nodeProps()),
  )

  protected readonly isBranch = computed(() => this.nodeState().isBranch)

  protected readonly key = computed(() =>
    keyPathToKey(this.node().keyPath, {excludeRoot: true}),
  )

  protected readonly hastElement = computed(() =>
    jsonNodeToElement(this.node(), this.previewOptions()),
  )

  protected readonly description = computed(() =>
    getAccessibleDescription(this.node(), this.previewOptions()),
  )

  protected readonly showQuotes = computed(
    () => this.jsonOptions()?.quotesOnKeys,
  )

  protected readonly childNodes = computed(() =>
    this.treeContext().collection.getNodeChildren(this.node()),
  )

  private readonly treeNodePropsContextService = inject(
    TreeNodePropsContextService,
    {self: true},
  )

  private readonly treeNodeStateContextService = inject(
    TreeNodeStateContextService,
    {self: true},
  )

  ngOnInit() {
    this.treeNodePropsContextService.init(this.nodeProps)
    this.treeNodeStateContextService.init(this.nodeState)
  }

  protected trackChild(child: JsonNode): string {
    return this.treeContext().collection.getNodeValue(child)
  }

  protected getChildIndexPath(index: number): number[] {
    return [...this.indexPath(), index]
  }
}
