// packages/docs/react-docs/src/routes/components+/drawer+/demos/drawer-placement-demo.tsx
import type {ReactElement} from "react"

import {LoremIpsum} from "@qualcomm-ui/react-core/lorem-ipsum"
import {Button} from "@qualcomm-ui/react/button"
import {Drawer} from "@qualcomm-ui/react/drawer"

export function DrawerPlacementDemo(): ReactElement {
  return (
    <Drawer.Root>
      <Drawer.Trigger>
        <Button emphasis="primary" variant="fill">
          Open Drawer
        </Button>
      </Drawer.Trigger>
      <Drawer.FloatingPortal>
        <Drawer.Body>
          <Drawer.Heading>Drawer Title</Drawer.Heading>
          <Drawer.CloseButton />
          <Drawer.Description>
            <LoremIpsum />
          </Drawer.Description>
        </Drawer.Body>

        <Drawer.Footer>
          <Drawer.CloseTrigger>
            <Button emphasis="primary" size="sm" variant="fill">
              Confirm
            </Button>
          </Drawer.CloseTrigger>
        </Drawer.Footer>
      </Drawer.FloatingPortal>
    </Drawer.Root>
  )
}

// packages/docs/angular-docs/src/routes/components+/drawer+/demos/drawer-placement-demo.ts
import {Component} from "@angular/core"

import {ButtonModule} from "@qualcomm-ui/angular/button"
import {DrawerModule} from "@qualcomm-ui/angular/drawer"

@Component({
  imports: [DrawerModule, ButtonModule],
  selector: "drawer-placement-demo",
  template: `
    <div q-drawer-root>
      <button emphasis="primary" q-button q-drawer-trigger variant="fill">
        Open Drawer
      </button>
      <q-drawer-floating-portal>
        <div q-drawer-body>
          <button q-drawer-close-button></button>
          <h2 q-drawer-heading>Drawer Title</h2>
          <div q-drawer-description>Drawer Description</div>
        </div>

        <div q-drawer-footer>
          <button q-button q-drawer-close-trigger size="sm" variant="fill">
            Close
          </button>
        </div>
      </q-drawer-floating-portal>
    </div>
  `,
})
export class DrawerPlacementDemo {}
