// packages/docs/angular-docs/src/routes/components+/breadcrumbs+/demos/breadcrumbs-sizes-demo.ts
import {Component} from "@angular/core"
import {Home} from "lucide-angular"

import {BreadcrumbsModule} from "@qualcomm-ui/angular/breadcrumbs"
import {IconDirective} from "@qualcomm-ui/angular/icon"
import {provideIcons} from "@qualcomm-ui/angular-core/lucide"

@Component({
  imports: [BreadcrumbsModule, IconDirective],
  providers: [provideIcons({Home})],
  selector: "breadcrumbs-sizes-demo",
  template: `
    <div class="flex flex-col gap-4">
      <nav aria-label="Breadcrumbs" q-breadcrumbs-root size="sm">
        <ol q-breadcrumbs-list>
          <li q-breadcrumb-item>
            <a q-breadcrumb-item-trigger>
              <svg q-breadcrumb-item-icon qIcon="Home"></svg>
              Home
            </a>
          </li>
          <li q-breadcrumb-item>
            <a q-breadcrumb-item-trigger>Components</a>
          </li>
          <li aria-current="page" q-breadcrumb-item>
            <a q-breadcrumb-item-trigger>Breadcrumbs</a>
          </li>
        </ol>
      </nav>

      <nav aria-label="Breadcrumbs" q-breadcrumbs-root size="md">
        <ol q-breadcrumbs-list>
          <li q-breadcrumb-item>
            <a q-breadcrumb-item-trigger>
              <svg q-breadcrumb-item-icon qIcon="Home"></svg>
              Home
            </a>
          </li>
          <li q-breadcrumb-item>
            <a q-breadcrumb-item-trigger>Components</a>
          </li>
          <li aria-current="page" q-breadcrumb-item>
            <a q-breadcrumb-item-trigger>Breadcrumbs</a>
          </li>
        </ol>
      </nav>

      <!-- preview -->
      <nav aria-label="Breadcrumbs" q-breadcrumbs-root size="lg">
        <ol q-breadcrumbs-list>
          <li q-breadcrumb-item>
            <a q-breadcrumb-item-trigger>
              <svg q-breadcrumb-item-icon qIcon="Home"></svg>
              Home
            </a>
          </li>
          <li q-breadcrumb-item>
            <a q-breadcrumb-item-trigger>Components</a>
          </li>
          <li aria-current="page" q-breadcrumb-item>
            <a q-breadcrumb-item-trigger>Breadcrumbs</a>
          </li>
        </ol>
      </nav>
      <!-- preview -->
    </div>
  `,
})
export class BreadcrumbsSizesDemo {}

// packages/debug-apps/react-ssr/src/routes/components+/breadcrumbs+/demos/breadcrumbs-sizes-demo.tsx
import type {ReactElement} from "react"

import {Home} from "lucide-react"

import {Breadcrumbs} from "@qualcomm-ui/react/breadcrumbs"

export default function BreadcrumbsSizesDemo(): ReactElement {
  return (
    <div className="flex flex-col gap-4">
      {/* preview */}
      <Breadcrumbs.Root aria-label="Breadcrumbs" size="sm">
        <Breadcrumbs.List>
          <Breadcrumbs.Item icon={Home}>Home</Breadcrumbs.Item>
          <Breadcrumbs.Item>Components</Breadcrumbs.Item>
          <Breadcrumbs.Item aria-current="page">Breadcrumbs</Breadcrumbs.Item>
        </Breadcrumbs.List>
      </Breadcrumbs.Root>

      <Breadcrumbs.Root aria-label="Breadcrumbs" size="md">
        <Breadcrumbs.List>
          <Breadcrumbs.Item icon={Home}>Home</Breadcrumbs.Item>
          <Breadcrumbs.Item>Components</Breadcrumbs.Item>
          <Breadcrumbs.Item aria-current="page">Breadcrumbs</Breadcrumbs.Item>
        </Breadcrumbs.List>
      </Breadcrumbs.Root>

      <Breadcrumbs.Root aria-label="Breadcrumbs" size="lg">
        <Breadcrumbs.List>
          <Breadcrumbs.Item icon={Home}>Home</Breadcrumbs.Item>
          <Breadcrumbs.Item>Components</Breadcrumbs.Item>
          <Breadcrumbs.Item aria-current="page">Breadcrumbs</Breadcrumbs.Item>
        </Breadcrumbs.List>
      </Breadcrumbs.Root>
      {/* preview */}
    </div>
  )
}
