// packages/docs/react-docs/src/routes/components+/combobox+/demos/combobox-max-height-demo.tsx
import type {ComboboxInputValueChangeDetails} from "@qualcomm-ui/core/combobox"
import {useListCollection} from "@qualcomm-ui/react-core/collection"
import {useFilter} from "@qualcomm-ui/react-core/locale"
import {Combobox} from "@qualcomm-ui/react/combobox"

import {countries} from "./country-list"

export function ComboboxMaxHeightDemo() {
  const {contains} = useFilter({sensitivity: "base"})

  const {collection, filter} = useListCollection({
    filter: contains,
    initialItems: countries,
  })

  function handleInputChange(details: ComboboxInputValueChangeDetails) {
    filter(details.inputValue)
  }

  return (
    // preview
    <Combobox
      aria-label="Country"
      className="w-48"
      collection={collection}
      contentProps={{style: {maxHeight: 240}}}
      onInputValueChange={handleInputChange}
      placeholder="Select a country"
      positioning={{sameWidth: true}}
    />
    // preview
  )
}

// packages/docs/angular-docs/src/routes/components+/combobox+/demos/combobox-max-height-demo.ts
import {Component} from "@angular/core"

import {useListCollection} from "@qualcomm-ui/angular-core/collection"
import {PortalDirective} from "@qualcomm-ui/angular-core/portal"
import {ComboboxModule} from "@qualcomm-ui/angular/combobox"
import type {ComboboxInputValueChangeDetails} from "@qualcomm-ui/core/combobox"

import {countries} from "./country-list"

@Component({
  imports: [ComboboxModule, PortalDirective],
  selector: "combobox-max-height-demo",
  template: `
    <div
      class="w-56"
      placeholder="Select a country"
      q-combobox-root
      [collection]="listCollection.collection()"
      (inputValueChanged)="onInputChange($event)"
    >
      <label q-combobox-label>Country</label>
      <div q-combobox-control>
        <input q-combobox-input />
        <button q-combobox-clear-trigger></button>
        <div q-combobox-trigger></div>
      </div>

      <ng-template qPortal>
        <div q-combobox-positioner>
          <div q-combobox-content style="max-height: 200px">
            <div q-combobox-empty>No results found</div>
            <q-combobox-items />
          </div>
        </div>
      </ng-template>
    </div>
  `,
})
export class ComboboxMaxHeightDemo {
  readonly listCollection = useListCollection<string>({
    filter: "contains",
    items: countries,
  })

  onInputChange(event: ComboboxInputValueChangeDetails) {
    this.listCollection.filterText.set(event.inputValue)
  }
}
