// packages/docs/react-docs/src/routes/components+/combobox+/demos/combobox-multiple-demo.tsx
import {useState} from "react"

import type {ComboboxInputValueChangeDetails} from "@qualcomm-ui/core/combobox"
import {Combobox} from "@qualcomm-ui/react/combobox"
import {Tag} from "@qualcomm-ui/react/tag"
import {useListCollection} from "@qualcomm-ui/react-core/collection"
import {useFilter} from "@qualcomm-ui/react-core/locale"

import {countries} from "./country-list"

export default function Demo() {
  const {contains} = useFilter({sensitivity: "base"})
  const [value, setValue] = useState<string[]>([])

  const {collection, filter} = useListCollection({
    filter: contains,
    initialItems: countries,
  })

  function handleInputChange(details: ComboboxInputValueChangeDetails) {
    filter(details.inputValue)
  }

  function handleValueDismissed(item: string) {
    setValue(value.filter((v) => v !== item))
  }

  return (
    <div className="flex w-72 flex-col gap-4">
      <div className="flex flex-wrap gap-2">
        {value.map((item) => (
          <Tag
            key={item}
            emphasis="neutral"
            onClick={() => handleValueDismissed(item)}
            variant="dismissable"
          >
            {item}
          </Tag>
        ))}
      </div>
      <Combobox
        className="w-full"
        collection={collection}
        label="Country"
        multiple
        onInputValueChange={handleInputChange}
        onValueChange={(details) => setValue(details.value)}
        placeholder="Select a country"
        value={value}
      />
    </div>
  )
}

// packages/docs/angular-docs/src/routes/components+/combobox+/demos/combobox-multiple-demo.ts
import {Component, signal} from "@angular/core"
import {FormsModule} from "@angular/forms"

import {useListCollection} from "@qualcomm-ui/angular-core/collection"
import {ComboboxModule} from "@qualcomm-ui/angular/combobox"
import {TagDirective} from "@qualcomm-ui/angular/tag"
import type {ComboboxInputValueChangeDetails} from "@qualcomm-ui/core/combobox"

import {countries} from "./country-list"

@Component({
  imports: [ComboboxModule, TagDirective, FormsModule],
  selector: "combobox-multiple-demo",
  template: `
    <div class="flex w-72 flex-col gap-4">
      <div class="flex flex-wrap gap-2">
        @for (item of value(); track item) {
          <button
            emphasis="neutral"
            q-tag
            variant="dismissable"
            (click)="handleValueDismissed(item)"
          >
            {{ item }}
          </button>
        }
      </div>
      <q-combobox
        class="w-full"
        label="Country"
        multiple
        placeholder="Select a country"
        [collection]="listCollection.collection()"
        [(ngModel)]="value"
        (inputValueChanged)="onInputChange($event)"
      />
    </div>
  `,
})
export class ComboboxMultipleDemo {
  readonly value = signal<string[]>([])

  readonly listCollection = useListCollection<string>({
    filter: "contains",
    items: countries,
  })

  onInputChange(event: ComboboxInputValueChangeDetails) {
    this.listCollection.filterText.set(event.inputValue)
  }

  handleValueDismissed(item: string) {
    this.value.set(this.value().filter((v) => v !== item))
  }
}
