// packages/frameworks/angular-core/src/events/use-copy-to-clipboard.ts
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import {DestroyRef, effect, inject, signal} from "@angular/core"

import {NAVIGATOR} from "@qualcomm-ui/angular-core/dom"

export interface UseCopyToClipboardProps {
  valueOrFn: (() => string) | string
}

export interface UseCopyToClipboard {
  copyToClipboard: () => void
  isCopied: () => boolean
}

export function useCopyToClipboard(
  props: UseCopyToClipboardProps,
): UseCopyToClipboard {
  const {valueOrFn} = props
  const destroyRef = inject(DestroyRef)

  const navigator = inject(NAVIGATOR)

  const isCopied = signal<boolean>(false)
  let copyTimeout: ReturnType<typeof setTimeout>

  effect(() => {
    if (isCopied()) {
      copyTimeout = setTimeout(() => {
        isCopied.set(false)
      }, 2000)
    } else {
      if (copyTimeout !== undefined) {
        clearTimeout(copyTimeout)
      }
    }
  })

  destroyRef.onDestroy(() => {
    if (copyTimeout !== undefined) {
      clearTimeout(copyTimeout)
    }
  })

  const copyToClipboard = () => {
    if (!navigator?.clipboard) {
      console.error("Access to clipboard rejected!")
      return
    }

    const value = typeof valueOrFn === "function" ? valueOrFn() : valueOrFn

    navigator.clipboard
      .writeText(value)
      .then(() => {
        isCopied.set(true)
      })
      .catch(() => {
        console.error("Failed to copy!")
      })
  }

  return {
    copyToClipboard,
    isCopied: isCopied.asReadonly(),
  }
}

// packages/frameworks/react-mdx/src/copy-to-clipboard/use-copy-to-clipboard.ts
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import {useCallback, useEffect, useState} from "react"

import {useCopyToClipboardContext} from "./copy-to-clipboard-context"

export interface UseCopyToClipboardProps {
  valueOrFn: (() => string) | string
}

export interface UseCopyToClipboard {
  copyToClipboard: () => void
  isCopied: boolean
}

export function useCopyToClipboard(
  props: UseCopyToClipboardProps,
): UseCopyToClipboard {
  const context = useCopyToClipboardContext(false)
  const {valueOrFn} = props
  const [isCopied, setCopied] = useState(false)

  useEffect(() => {
    if (!isCopied) {
      return () => {}
    }
    const timerId = setTimeout(() => {
      setCopied(false)
    }, 2000)

    return () => {
      clearTimeout(timerId)
    }
  }, [isCopied])

  const copyToClipboard = useCallback(() => {
    if (!navigator?.clipboard) {
      console.error("Access to clipboard rejected!")
    }
    const value = typeof valueOrFn === "function" ? valueOrFn() : valueOrFn
    if (!value) {
      console.error("No value to copy!")
      return
    }
    void navigator.clipboard
      .writeText(value)
      .catch(() => console.error("Failed to copy!"))
      .finally(() => {
        setCopied(true)
      })
  }, [valueOrFn])

  return {
    copyToClipboard: context?.copyToClipboard || copyToClipboard,
    isCopied: context?.isCopied ?? isCopied,
  }
}
