// packages/frameworks/angular/src/dialog/dialog-positioner.component.ts
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import {computed, Directive} from "@angular/core"

import {CoreDialogPositionerDirective} from "@qualcomm-ui/angular-core/dialog"

import {useQdsDialogContext} from "./qds-dialog-context.service"

/**
 * A container for the dialog content that handles positioning.
 */
@Directive({
  selector: "[q-dialog-positioner]",
  standalone: false,
})
export class DialogPositionerComponent extends CoreDialogPositionerDirective {
  protected readonly qdsContext = useQdsDialogContext()

  constructor() {
    super()
    this.trackBindings.extendWith(
      computed(() => this.qdsContext().getPositionerBindings()),
    )
  }
}

// packages/frameworks/react/src/dialog/dialog-positioner.tsx
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import type {ReactNode} from "react"

import {
  CoreDialog,
  type CoreDialogPositionerProps,
} from "@qualcomm-ui/react-core/dialog"
import {mergeProps} from "@qualcomm-ui/utils/merge-props"

import {useQdsDialogContext} from "./qds-dialog-context.js"

export interface DialogPositionerProps extends CoreDialogPositionerProps {}

/**
 * A container that positions the dialog on the screen. Renders a `<div>` element by
 * default.
 */
export function DialogPositioner(props: DialogPositionerProps): ReactNode {
  const qdsDialogContext = useQdsDialogContext()
  const mergedProps = mergeProps(
    qdsDialogContext.getPositionerBindings(),
    props,
  )

  return <CoreDialog.Positioner {...mergedProps} />
}
