// packages/frameworks/angular/src/slider/slider-thumbs.component.ts
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import {booleanAttribute, Component, computed, input} from "@angular/core"

import {useSliderContext} from "@qualcomm-ui/angular-core/slider"
import type {Booleanish} from "@qualcomm-ui/utils/coercion"

@Component({
  selector: "q-slider-thumbs",
  standalone: false,
  template: `
    @for (idx of thumbs(); track idx) {
      <div q-slider-thumb [index]="idx">
        <input q-slider-hidden-input />
        @if (this.tooltip()) {
          <div q-slider-thumb-indicator></div>
        }
      </div>
    }
  `,
})
export class SliderThumbsComponent {
  /**
   * Whether to display the thumb value as a tooltip.
   */
  readonly tooltip = input<boolean | undefined, Booleanish>(undefined, {
    transform: booleanAttribute,
  })

  private readonly sliderContext = useSliderContext()

  readonly thumbs = computed(() =>
    this.sliderContext().value.map((_, idx) => idx),
  )
}

// packages/frameworks/react/src/slider/slider-thumbs.tsx
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import type {ReactElement} from "react"

import {useSliderContext} from "@qualcomm-ui/react-core/slider"

import {
  SliderHiddenInput,
  type SliderHiddenInputProps,
} from "./slider-hidden-input.js"
import {SliderThumbIndicator} from "./slider-thumb-indicator.js"
import {SliderThumb, type SliderThumbProps} from "./slider-thumb.js"

export interface SliderThumbsProps {
  /**
   * Props applied to all hidden input elements.
   *
   * @inheritDoc
   */
  hiddenInputProps?: SliderHiddenInputProps

  /**
   * Props applied to all thumb elements.
   *
   * @inheritDoc
   */
  thumbProps?: Omit<SliderThumbProps, "index" | "tooltip">

  /**
   * Whether to display the thumb value as a tooltip.
   */
  tooltip?: boolean
}

/**
 * A shortcut element for the draggable handle(s) and their associated hidden
 * input(s).
 */
export function SliderThumbs({
  hiddenInputProps,
  thumbProps,
  tooltip,
}: SliderThumbsProps): ReactElement {
  const context = useSliderContext()
  return (
    <>
      {context.value.map((_, idx) => (
        <SliderThumb key={idx} index={idx} {...thumbProps}>
          <SliderHiddenInput {...hiddenInputProps} />
          {tooltip && <SliderThumbIndicator />}
        </SliderThumb>
      ))}
    </>
  )
}
