// packages/docs/react-docs/src/routes/components+/dialog+/demos/dialog-sizes-demo.tsx
import type {ReactElement} from "react"

import {LoremIpsum} from "@qualcomm-ui/react-core/lorem-ipsum"
import {Button} from "@qualcomm-ui/react/button"
import {Dialog, useQdsDialogContext} from "@qualcomm-ui/react/dialog"

export function DialogSizesDemo(): ReactElement {
  return (
    <div className="flex flex-col gap-4">
      <Dialog.Root size="sm">
        <Dialog.Trigger>
          <Button emphasis="primary" variant="fill">
            Open Dialog (sm)
          </Button>
        </Dialog.Trigger>
        <DialogContent />
      </Dialog.Root>

      <Dialog.Root size="md">
        <Dialog.Trigger>
          <Button emphasis="primary" variant="fill">
            Open Dialog (md)
          </Button>
        </Dialog.Trigger>
        <DialogContent />
      </Dialog.Root>
    </div>
  )
}

function DialogContent() {
  const context = useQdsDialogContext()
  return (
    <Dialog.FloatingPortal>
      <Dialog.Body>
        <Dialog.Heading>Dialog Title ({context.size})</Dialog.Heading>
        <Dialog.CloseButton />
        <Dialog.Description>
          <LoremIpsum />
        </Dialog.Description>
      </Dialog.Body>

      <Dialog.Footer>
        <Dialog.CloseTrigger>
          <Button size="sm" variant="outline">
            Cancel
          </Button>
        </Dialog.CloseTrigger>
        <Dialog.CloseTrigger>
          <Button emphasis="primary" size="sm" variant="fill">
            Confirm
          </Button>
        </Dialog.CloseTrigger>
      </Dialog.Footer>
    </Dialog.FloatingPortal>
  )
}

// packages/docs/angular-docs/src/routes/components+/dialog+/demos/dialog-sizes-demo.ts
import {Component} from "@angular/core"

import {LoremIpsumDirective} from "@qualcomm-ui/angular-core/lorem-ipsum"
import {ButtonModule} from "@qualcomm-ui/angular/button"
import {DialogModule, useQdsDialogContext} from "@qualcomm-ui/angular/dialog"

@Component({
  imports: [DialogModule, LoremIpsumDirective, ButtonModule],
  selector: "dialog-content-demo",
  template: `
    <q-dialog-floating-portal>
      <div q-dialog-body>
        <button q-dialog-close-button></button>
        <h2 q-dialog-heading>Dialog Title {{ qdsContext().size }}</h2>
        <div q-dialog-description>
          <div q-lorem-ipsum></div>
        </div>
      </div>

      <div q-dialog-footer>
        <button q-button q-dialog-close-trigger size="sm" variant="outline">
          Close
        </button>
        <button
          emphasis="primary"
          q-button
          q-dialog-close-trigger
          size="sm"
          variant="fill"
        >
          Confirm
        </button>
      </div>
    </q-dialog-floating-portal>
  `,
})
class DialogContent {
  protected readonly qdsContext = useQdsDialogContext()
}

@Component({
  imports: [DialogModule, ButtonModule, DialogContent],
  selector: "dialog-sizes-demo",
  template: `
    <div class="flex flex-col gap-4">
      <!-- preview -->
      <div q-dialog-root size="sm">
        <button emphasis="primary" q-button q-dialog-trigger variant="fill">
          Open Dialog (sm)
        </button>
        <dialog-content-demo />
      </div>
      <!-- preview -->

      <div q-dialog-root size="md">
        <button emphasis="primary" q-button q-dialog-trigger variant="fill">
          Open Dialog (md)
        </button>
        <dialog-content-demo />
      </div>
    </div>
  `,
})
export class DialogSizesDemo {}
