// packages/docs/react-docs/src/routes/components+/dialog+/demos/dialog-outside-scroll-demo.tsx
import type {ReactElement} from "react"

import {Button} from "@qualcomm-ui/react/button"
import {Dialog} from "@qualcomm-ui/react/dialog"
import {LoremIpsum} from "@qualcomm-ui/react-core/lorem-ipsum"

export default function DialogOutsideScrollDemo(): ReactElement {
  return (
    <Dialog.Root>
      <Dialog.Trigger>
        <Button emphasis="primary" variant="fill">
          Open Dialog
        </Button>
      </Dialog.Trigger>
      <Dialog.FloatingPortal>
        <Dialog.Body>
          <Dialog.Heading>Dialog Title</Dialog.Heading>
          <Dialog.CloseButton />
          <Dialog.Description>
            <LoremIpsum numParagraphs={20} />
          </Dialog.Description>
        </Dialog.Body>
        <Dialog.Footer>
          <Dialog.CloseTrigger>
            <Button emphasis="primary" size="sm" variant="fill">
              Confirm
            </Button>
          </Dialog.CloseTrigger>
        </Dialog.Footer>
      </Dialog.FloatingPortal>
    </Dialog.Root>
  )
}

// packages/docs/angular-docs/src/routes/components+/dialog+/demos/dialog-outside-scroll-demo.ts
import {Component} from "@angular/core"

import {LoremIpsumDirective} from "@qualcomm-ui/angular-core/lorem-ipsum"
import {ButtonModule} from "@qualcomm-ui/angular/button"
import {DialogModule} from "@qualcomm-ui/angular/dialog"

@Component({
  imports: [DialogModule, ButtonModule, LoremIpsumDirective],
  selector: "dialog-outside-scroll-demo",
  template: `
    <div q-dialog-root>
      <button emphasis="primary" q-button q-dialog-trigger variant="fill">
        Open Dialog
      </button>
      <q-dialog-floating-portal>
        <div q-dialog-body>
          <button q-dialog-close-button></button>
          <h2 q-dialog-heading>Dialog Title</h2>
          <div q-dialog-description>
            <div numParagraphs="20" q-lorem-ipsum></div>
          </div>
        </div>
        <div q-dialog-footer>
          <button q-button q-dialog-close-trigger size="sm" variant="fill">
            Close
          </button>
        </div>
      </q-dialog-floating-portal>
    </div>
  `,
})
export class DialogOutsideScrollDemo {}
