// packages/docs/angular-docs/src/routes/components+/accordion+/demos/accordion-explorer-demo.ts
import {Component} from "@angular/core"

import {AccordionModule} from "@qualcomm-ui/angular/accordion"

@Component({
  imports: [AccordionModule],
  selector: "accordion-explorer-demo",
  template: `
    <!-- preview -->
    <div class="w-96" q-accordion [defaultValue]="['a']">
      <div
        q-accordion-item
        secondaryText="Secondary text"
        text="Accordion Item 1"
        value="a"
      >
        Content for the first accordion item.
      </div>
      <div
        q-accordion-item
        secondaryText="Secondary text"
        text="Accordion Item 2"
        value="b"
      >
        Content for the second accordion item.
      </div>
    </div>
    <!-- preview -->
  `,
})
export class AccordionExplorerDemo {}

// packages/docs/react-docs/src/routes/components+/accordion+/demos/accordion-explorer-demo.tsx
import type {ReactElement} from "react"

import {Accordion} from "@qualcomm-ui/react/accordion"

export function AccordionExplorerDemo(): ReactElement {
  return (
    <Accordion.Root className="w-96" defaultValue={["a"]}>
      <Accordion.Item
        secondaryText="Secondary text"
        text="Accordion Item 1"
        value="a"
      >
        Content for the first accordion item.
      </Accordion.Item>
      <Accordion.Item
        secondaryText="Secondary text"
        text="Accordion Item 2"
        value="b"
      >
        Content for the second accordion item.
      </Accordion.Item>
    </Accordion.Root>
  )
}
