// packages/docs/angular-docs/src/routes/components+/file-input+/demos/file-input-simple-demo.ts
import {Component} from "@angular/core"
import {Upload} from "lucide-angular"

import {provideIcons} from "@qualcomm-ui/angular-core/lucide"
import {FileInputModule} from "@qualcomm-ui/angular/file-input"

@Component({
  imports: [FileInputModule],
  providers: [provideIcons({Upload})],
  selector: "file-input-simple-demo",
  standalone: true,
  template: `
    <!-- preview -->
    <q-file-input
      class="w-full max-w-sm"
      label="Upload file"
      placeholder="Select a file"
      startIcon="Upload"
    />
    <!-- preview -->
  `,
})
export class FileInputSimpleDemo {}

// packages/docs/react-docs/src/routes/components+/file-input+/demos/file-input-simple-demo.tsx
import type {ReactElement} from "react"

import {Upload} from "lucide-react"

import {FileInput} from "@qualcomm-ui/react/file-input"

export function FileInputSimpleDemo(): ReactElement {
  return (
    // preview
    <FileInput
      className="w-full max-w-sm"
      label="Upload file"
      placeholder="Select a file"
      startIcon={Upload}
    />
    // preview
  )
}
