// packages/docs/react-docs/src/routes/components+/checkbox+/demos/checkbox-sizes-demo.tsx
import type {ReactElement} from "react"

import {Checkbox} from "@qualcomm-ui/react/checkbox"

export function CheckboxSizesDemo(): ReactElement {
  return (
    <div className="flex flex-col items-start gap-4">
      <Checkbox label="Small (sm)" size="sm" />
      <Checkbox label="Medium (md)" size="md" />
      <Checkbox label="Large (lg)" size="lg" />
    </div>
  )
}

// packages/docs/angular-docs/src/routes/components+/checkbox+/demos/checkbox-sizes-demo.ts
import {Component} from "@angular/core"

import {CheckboxModule} from "@qualcomm-ui/angular/checkbox"

@Component({
  imports: [CheckboxModule],
  selector: "checkbox-sizes-demo",
  template: `
    <div class="flex flex-col items-start gap-4">
      <label label="Small (sm)" q-checkbox size="sm"></label>
      <label label="Medium (md)" q-checkbox size="md"></label>
      <label label="Large (lg)" q-checkbox size="lg"></label>
    </div>
  `,
})
export class CheckboxSizesDemo {}
