// packages/docs/react-docs/src/routes/components+/tabs+/demos/tabs-line-sizes-demo.tsx
import type {ReactElement} from "react"

import {Code, Cpu, FileText, Smartphone} from "lucide-react"

import type {QdsTabsSize} from "@qualcomm-ui/qds-core/tabs"
import {Tab, Tabs} from "@qualcomm-ui/react/tabs"

const sizes: QdsTabsSize[] = ["sm", "md", "lg", "xl"]

export default function TabsLineSizesDemo(): ReactElement {
  return (
    <div className="flex flex-col gap-4">
      {sizes.map((size) => (
        <div key={size} className="flex items-center gap-4">
          <div className="font-heading-xs text-neutral-primary w-16">
            {size}
          </div>
          <Tabs.Root defaultValue="documents" size={size}>
            <Tabs.List>
              <Tabs.Indicator />
              <Tab.Root value="documents">
                <Tab.Button endIcon={FileText}>Documents</Tab.Button>
              </Tab.Root>
              <Tab.Root value="products">
                <Tab.Button endIcon={Smartphone}>Products</Tab.Button>
              </Tab.Root>
              <Tab.Root value="software">
                <Tab.Button endIcon={Code}>Software</Tab.Button>
              </Tab.Root>
              <Tab.Root value="hardware">
                <Tab.Button endIcon={Cpu}>Hardware</Tab.Button>
              </Tab.Root>
            </Tabs.List>
          </Tabs.Root>
        </div>
      ))}
    </div>
  )
}

// packages/docs/angular-docs/src/routes/components+/tabs+/demos/tabs-line-sizes-demo.ts
import {Component} from "@angular/core"
import {Code, Cpu, FileText, Smartphone} from "lucide-angular"

import {provideIcons} from "@qualcomm-ui/angular-core/lucide"
import {TabsModule} from "@qualcomm-ui/angular/tabs"
import type {QdsTabsSize} from "@qualcomm-ui/qds-core/tabs"

@Component({
  imports: [TabsModule],
  providers: [provideIcons({Code, Cpu, FileText, Smartphone})],
  selector: "tabs-line-sizes-demo",
  template: `
    <div class="flex flex-col gap-4">
      @for (size of sizes; track size) {
        <div class="flex items-center gap-4">
          <div class="font-heading-xs text-neutral-primary w-16">
            {{ size }}
          </div>
          <div defaultValue="documents" q-tabs-root [size]="size">
            <div q-tabs-list>
              <div q-tabs-indicator></div>
              <div q-tab-root value="documents">
                <button endIcon="FileText" q-tab-button>Documents</button>
              </div>
              <div q-tab-root value="products">
                <button endIcon="Smartphone" q-tab-button>Products</button>
              </div>
              <div q-tab-root value="software">
                <button endIcon="Code" q-tab-button>Software</button>
              </div>
              <div q-tab-root value="hardware">
                <button endIcon="Cpu" q-tab-button>Hardware</button>
              </div>
            </div>
          </div>
        </div>
      }
    </div>
  `,
})
export class TabsLineSizesDemo {
  protected sizes: QdsTabsSize[] = ["sm", "md", "lg", "xl"]
}
