// packages/docs/react-docs/src/routes/components+/file-upload+/demos/file-upload-errors-demo.tsx
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import {type ReactElement, useState} from "react"

import type {FileDetails} from "@qualcomm-ui/core/file-upload"
import {FileUpload} from "@qualcomm-ui/react/file-upload"

export function FileUploadErrorsDemo(): ReactElement {
  const [invalid, setInvalid] = useState(true)
  const [errorText, setErrorText] = useState("At least one file is required")

  const handleFileChange = (details: FileDetails) => {
    if (details.acceptedFiles.length > 0 && !details.rejectedFiles.length) {
      setInvalid(false)
      setErrorText("")
    } else if (details.acceptedFiles.length === 0) {
      setInvalid(true)
      setErrorText("At least one file is required")
    } else {
      setInvalid(true)
      setErrorText(
        "Files must be .jpg, .jpeg, .png, or .pdf. and less than 5MB in size.",
      )
    }
  }

  return (
    // preview
    <FileUpload
      accept={["image/png", "image/jpg", "image/jpeg", "application/pdf"]}
      className="w-full max-w-md"
      dropzoneHint="Supported: .jpg, .jpeg, .png, .pdf (max 5MB each)"
      invalid={invalid}
      label="Upload files"
      maxFileSize={5 * 1024 * 1024}
      maxFiles={3}
      onFileChange={handleFileChange}
      required
    >
      <FileUpload.ErrorText>{errorText}</FileUpload.ErrorText>
    </FileUpload>
    // preview
  )
}

// packages/docs/angular-docs/src/routes/components+/file-upload+/demos/file-upload-errors-demo.ts
import {Component, signal} from "@angular/core"

import {FileUploadModule} from "@qualcomm-ui/angular/file-upload"
import type {FileDetails} from "@qualcomm-ui/core/file-upload"

@Component({
  imports: [FileUploadModule],
  selector: "file-upload-errors-demo",
  standalone: true,
  template: `
    <!-- preview -->
    <q-file-upload
      class="w-full max-w-md"
      dropzoneHint="Supported: .jpg, .jpeg, .png, .pdf (max 5MB each)"
      label="Upload files"
      required
      [accept]="['image/png', 'image/jpg', 'image/jpeg', 'application/pdf']"
      [invalid]="invalid()"
      [maxFileSize]="5 * 1024 * 1024"
      [maxFiles]="3"
      (fileChanged)="handleFileChange($event)"
    >
      <div q-file-upload-error-text>
        {{ errorText() }}
      </div>
    </q-file-upload>
    <!-- preview -->
  `,
})
export class FileUploadErrorsDemo {
  readonly invalid = signal(true)
  readonly errorText = signal("At least one file is required")

  protected handleFileChange = (details: FileDetails) => {
    if (details.acceptedFiles.length > 0 && !details.rejectedFiles.length) {
      this.invalid.set(false)
      this.errorText.set("")
    } else if (details.acceptedFiles.length === 0) {
      this.invalid.set(true)
      this.errorText.set("At least one file is required")
    } else {
      this.invalid.set(true)
      this.errorText.set(
        "Files must be .jpg, .jpeg, .png, or .pdf. and less than 5MB in size.",
      )
    }
  }
}
