// packages/docs/angular-docs/src/routes/components+/slider+/demos/slider-simple-demo.ts
import {Component} from "@angular/core"

import {SliderModule} from "@qualcomm-ui/angular/slider"

@Component({
  imports: [SliderModule],
  selector: "slider-simple",
  template: `
    <!-- preview -->
    <q-slider
      class="sm:w-80"
      hint="Some contextual help here"
      label="Choose a value"
      [defaultValue]="[25]"
    />
    <!-- preview -->
  `,
})
export class SliderSimpleDemo {}

// packages/docs/react-docs/src/routes/components+/slider+/demos/slider-simple-demo.tsx
import type {ReactElement} from "react"

import {Slider} from "@qualcomm-ui/react/slider"

export function SliderSimpleDemo(): ReactElement {
  return (
    // preview
    <Slider
      className="sm:w-80"
      defaultValue={[25]}
      hint="Some contextual help here"
      label="Choose a value"
    />
    // preview
  )
}
