// packages/docs/angular-docs/src/routes/components+/slider+/demos/slider-display-demo.ts
import {Component} from "@angular/core"

import {SliderModule} from "@qualcomm-ui/angular/slider"

@Component({
  imports: [SliderModule],
  selector: "slider-display-demo",
  template: `
    <!-- preview -->
    <q-slider class="sm:w-80" [defaultValue]="[20, 50]" [display]="display" />
    <!-- preview -->
  `,
})
export class SliderDisplayDemo {
  display(values: number[]): string {
    return `from ${values[0]} to ${values[1]}`
  }
}

// packages/docs/react-docs/src/routes/components+/slider+/demos/slider-display-demo.tsx
import type {ReactElement} from "react"

import {Slider} from "@qualcomm-ui/react/slider"

export default function SliderDisplayDemo(): ReactElement {
  return (
    // preview
    <Slider
      className="sm:w-[340px]"
      defaultValue={[20, 50]}
      display={(values) => `from ${values[0]} to ${values[1]}`}
    />
    // preview
  )
}
