// packages/docs/angular-docs/src/routes/components+/slider+/demos/slider-min-steps-demo.ts
import {Component} from "@angular/core"

import {SliderModule} from "@qualcomm-ui/angular/slider"

@Component({
  imports: [SliderModule],
  selector: "slider-min-steps-demo",
  template: `
    <!-- preview -->
    <q-slider
      class="sm:w-80"
      [defaultValue]="[20, 50]"
      [minStepsBetweenThumbs]="10"
    />
    <!-- preview -->
  `,
})
export class SliderMinStepsDemo {}

// packages/docs/react-docs/src/routes/components+/slider+/demos/slider-min-steps-demo.tsx
import type {ReactElement} from "react"

import {Slider} from "@qualcomm-ui/react/slider"

export default function SliderMinStepsDemo(): ReactElement {
  return (
    // preview
    <Slider
      className="sm:w-80"
      defaultValue={[20, 50]}
      minStepsBetweenThumbs={10}
    />
    // preview
  )
}
