// packages/docs/react-docs/src/routes/components+/select+/demos/select-aria-label-demo.tsx
import type {ReactElement} from "react"

import {selectCollection} from "@qualcomm-ui/core/select"
import {Select} from "@qualcomm-ui/react/select"

const cityCollection = selectCollection({
  items: [
    "San Diego",
    "Nashville",
    "Denver",
    "Miami",
    "Las Vegas",
    "New York City",
    "San Francisco",
  ],
})

export function SelectAriaLabelDemo(): ReactElement {
  return (
    // preview
    <Select
      className="w-48"
      collection={cityCollection}
      controlProps={{"aria-label": "City"}}
      placeholder="Select a city"
    />
    // preview
  )
}

// packages/docs/angular-docs/src/routes/components+/select+/demos/select-aria-label-demo.ts
import {Component} from "@angular/core"

import {SelectModule} from "@qualcomm-ui/angular/select"
import {selectCollection} from "@qualcomm-ui/core/select"

@Component({
  imports: [SelectModule],
  selector: "select-aria-label-demo",
  template: `
    <!-- preview -->
    <q-select
      aria-label="City"
      class="w-48"
      placeholder="Select a city"
      [collection]="cityCollection"
    />
    <!-- preview -->
  `,
})
export class SelectAriaLabelDemo {
  cityCollection = selectCollection({
    items: [
      "San Diego",
      "Nashville",
      "Denver",
      "Miami",
      "Las Vegas",
      "New York City",
      "San Francisco",
    ],
  })
}
