// packages/docs/react-docs/src/routes/components+/side-nav+/demos/side-nav-tooltip-demo.tsx
/* eslint-disable perfectionist/sort-objects */
import {
  Bell,
  CreditCard,
  LayoutDashboard,
  ShieldCheck,
  User,
} from "lucide-react"

import {createTreeCollection} from "@qualcomm-ui/core/tree"
import type {LucideIconOrElement} from "@qualcomm-ui/react-core/lucide"
import {SideNav} from "@qualcomm-ui/react/side-nav"
import {Tooltip} from "@qualcomm-ui/react/tooltip"

interface SideNavItem {
  disabled?: boolean
  group?: string
  icon?: LucideIconOrElement
  id: string
  nodes?: SideNavItem[]
  text: string
  tooltip?: string
}

const collection = createTreeCollection<SideNavItem>({
  nodeChildren: "nodes",
  nodeText: (node) => node.text,
  nodeValue: (node) => node.id,
  rootNode: {
    id: "ROOT",
    text: "",
    nodes: [
      {
        icon: Bell,
        id: "notifications",
        text: "Notifications",
      },
      {
        icon: LayoutDashboard,
        id: "dashboard",
        text: "Dashboard",
        disabled: true,
        tooltip: "The dashboard is planned for a future update",
      },
      {
        icon: User,
        id: "profile",
        text: "Profile",
      },
      {
        icon: ShieldCheck,
        id: "security",
        text: "Security",
      },
      {
        icon: CreditCard,
        id: "billing",
        text: "Billing",
      },
    ],
  },
})

export function SideNavTooltipDemo() {
  return (
    <div className="flex justify-center">
      <SideNav.Root collection={collection} open={false}>
        {collection.rootNode.nodes?.map((parentNode, index) => (
          <SideNav.Nodes
            key={collection.getNodeValue(parentNode)}
            indexPath={[index]}
            node={parentNode}
            renderBranch={({node}) => (
              <SideNav.BranchNode>
                {node.icon ? <SideNav.NodeIcon icon={node.icon} /> : null}
                <SideNav.NodeText>{node.text}</SideNav.NodeText>
                <SideNav.BranchTrigger />
              </SideNav.BranchNode>
            )}
            renderLeaf={({node}) => {
              return (
                // preview
                <Tooltip
                  trigger={
                    <span>
                      <SideNav.LeafNode>
                        <SideNav.NodeIndicator />
                        {node.icon ? (
                          <SideNav.NodeIcon icon={node.icon} />
                        ) : null}
                        <SideNav.NodeText>{node.text}</SideNav.NodeText>
                      </SideNav.LeafNode>
                    </span>
                  }
                >
                  {node.tooltip || node.text}
                </Tooltip>
                // preview
              )
            }}
          />
        ))}
      </SideNav.Root>
    </div>
  )
}

// packages/docs/angular-docs/src/routes/components+/side-nav+/demos/side-nav-tooltip-demo.ts
import {Component} from "@angular/core"
import {
  Bell,
  CreditCard,
  LayoutDashboard,
  ShieldCheck,
  User,
} from "lucide-angular"

import {IconDirective} from "@qualcomm-ui/angular/icon"
import {SideNavModule} from "@qualcomm-ui/angular/side-nav"
import {TooltipModule} from "@qualcomm-ui/angular/tooltip"
import {provideIcons} from "@qualcomm-ui/angular-core/lucide"
import {createTreeCollection} from "@qualcomm-ui/core/tree"

interface SideNavItem {
  disabled?: boolean
  icon?: string
  id: string
  nodes?: SideNavItem[]
  text: string
  tooltip?: string
}

const collection = createTreeCollection<SideNavItem>({
  nodeChildren: "nodes",
  nodeText: (node) => node.text,
  nodeValue: (node) => node.id,
  rootNode: {
    id: "ROOT",
    nodes: [
      {
        icon: "Bell",
        id: "notifications",
        text: "Notifications",
      },
      {
        disabled: true,
        icon: "LayoutDashboard",
        id: "dashboard",
        text: "Dashboard",
        tooltip: "The dashboard is planned for a future update",
      },
      {
        icon: "User",
        id: "profile",
        text: "Profile",
      },
      {
        icon: "ShieldCheck",
        id: "security",
        text: "Security",
      },
      {
        icon: "CreditCard",
        id: "billing",
        text: "Billing",
      },
    ],
    text: "",
  },
})

@Component({
  imports: [SideNavModule, IconDirective, TooltipModule],
  providers: [
    provideIcons({Bell, CreditCard, LayoutDashboard, ShieldCheck, User}),
  ],
  selector: "side-nav-tooltip-demo",
  template: `
    <div class="flex justify-center">
      <div q-side-nav-root [collection]="collection" [open]="false">
        @for (
          node of collection.rootNode.nodes;
          let i = $index;
          track collection.getNodeValue(node)
        ) {
          <q-side-nav-nodes [indexPath]="[i]" [node]="node">
            <ng-template
              let-branch
              q-side-nav-branch-template
              [rootNode]="collection.rootNode"
            >
              <div q-side-nav-branch-node>
                @if (branch.node.icon) {
                  <svg q-side-nav-node-icon [qIcon]="branch.node.icon"></svg>
                }
                <span q-side-nav-node-text>{{ branch.node.text }}</span>
                <div q-side-nav-branch-trigger></div>
              </div>
            </ng-template>

            <ng-template
              let-leaf
              q-side-nav-leaf-template
              [rootNode]="collection.rootNode"
            >
              <!-- preview -->
              <div q-tooltip>
                <span q-tooltip-trigger>
                  <div q-side-nav-leaf-node>
                    <div q-side-nav-node-indicator></div>
                    @if (leaf.node.icon) {
                      <svg q-side-nav-node-icon [qIcon]="leaf.node.icon"></svg>
                    }
                    <span q-side-nav-node-text>{{ leaf.node.text }}</span>
                  </div>
                </span>
                {{ leaf.node.tooltip || leaf.node.text }}
              </div>
              <!-- preview -->
            </ng-template>
          </q-side-nav-nodes>
        }
      </div>
    </div>
  `,
})
export class SideNavTooltipDemo {
  collection = collection
}
