// packages/docs/react-docs/src/routes/components+/collapsible+/demos/collapsible-showcase-demo.tsx
import type {ReactElement} from "react"

import {Button} from "@qualcomm-ui/react/button"
import {Collapsible} from "@qualcomm-ui/react/collapsible"

export function CollapsibleShowcaseDemo(): ReactElement {
  return (
    <Collapsible.Root className="flex flex-col items-center">
      <Collapsible.Trigger
        className="my-3"
        render={<Button emphasis="primary" />}
      >
        Toggle
      </Collapsible.Trigger>
      <Collapsible.Content>
        <div className="border-neutral-01 box-border flex h-48 w-72 flex-col rounded-sm border p-4">
          Content
        </div>
      </Collapsible.Content>
    </Collapsible.Root>
  )
}

// packages/docs/angular-docs/src/routes/components+/collapsible+/demos/collapsible-showcase-demo.ts
import {Component} from "@angular/core"

import {ButtonModule} from "@qualcomm-ui/angular/button"
import {CollapsibleModule} from "@qualcomm-ui/angular/collapsible"

@Component({
  imports: [CollapsibleModule, ButtonModule],
  selector: "collapsible-showcase-demo",
  template: `
    <div class="flex flex-col items-center" q-collapsible-root>
      <button
        class="my-3"
        emphasis="primary"
        q-button
        q-collapsible-trigger
        variant="fill"
      >
        Toggle
      </button>
      <div q-collapsible-content>
        <div
          class="border-neutral-01 box-border flex h-48 w-72 flex-col rounded-sm border p-4"
        >
          Content
        </div>
      </div>
    </div>
  `,
})
export class CollapsibleShowcaseDemo {}
