// packages/debug-apps/react-ssr/src/routes/components+/accordion+/_accordion.tsx
import CollapsibleDemo from "@qualcomm-ui/react-docs/components+/accordion+/demos/accordion-collapsible-demo"
import CompositeDemo from "@qualcomm-ui/react-docs/components+/accordion+/demos/accordion-composite-demo"
import CompositeLayoutDemo from "@qualcomm-ui/react-docs/components+/accordion+/demos/accordion-composite-layout-demo"
import ControlledStateDemo from "@qualcomm-ui/react-docs/components+/accordion+/demos/accordion-controlled-state-demo"
import DefaultValueDemo from "@qualcomm-ui/react-docs/components+/accordion+/demos/accordion-default-value-demo"
import DisabledDemo from "@qualcomm-ui/react-docs/components+/accordion+/demos/accordion-disabled-demo"
import FocusCallbackDemo from "@qualcomm-ui/react-docs/components+/accordion+/demos/accordion-focus-callback-demo"
import IconDemo from "@qualcomm-ui/react-docs/components+/accordion+/demos/accordion-icon-demo"
import MultipleDemo from "@qualcomm-ui/react-docs/components+/accordion+/demos/accordion-multiple-demo"
import SecondaryTextDemo from "@qualcomm-ui/react-docs/components+/accordion+/demos/accordion-secondary-text-demo"
import SimpleDemo from "@qualcomm-ui/react-docs/components+/accordion+/demos/accordion-simple-demo"
import SizeDemo from "@qualcomm-ui/react-docs/components+/accordion+/demos/accordion-size-demo"
import UncontainedDemo from "@qualcomm-ui/react-docs/components+/accordion+/demos/accordion-uncontained-demo"

const demos = [
  {component: CollapsibleDemo, title: "Collapsible"},
  {component: CompositeDemo, title: "Composite"},
  {component: CompositeLayoutDemo, title: "Composite Layout"},
  {component: ControlledStateDemo, title: "Controlled State"},
  {component: DefaultValueDemo, title: "Default Value"},
  {component: DisabledDemo, title: "Disabled"},
  {component: FocusCallbackDemo, title: "Focus Callback"},
  {component: IconDemo, title: "Icon"},
  {component: MultipleDemo, title: "Multiple"},
  {component: SecondaryTextDemo, title: "Secondary Text"},
  {component: SimpleDemo, title: "Simple"},
  {component: SizeDemo, title: "Size"},
  {component: UncontainedDemo, title: "Uncontained"},
]

export default function AccordionDemos() {
  return (
    <div className="page">
      {demos.map(({component: Demo, title}) => (
        <div className="section" key={title}>
          <h2 className="section-title">{title}</h2>
          <div className="demo-container">
            <Demo />
          </div>
        </div>
      ))}
    </div>
  )
}

// packages/debug-apps/angular-csr/src/app/components/accordion.ts
import {Component} from "@angular/core"

import {AccordionCollapsibleDemo} from "@qualcomm-ui/angular-docs/components+/accordion+/demos/accordion-collapsible-demo"
import {AccordionCompositeDemo} from "@qualcomm-ui/angular-docs/components+/accordion+/demos/accordion-composite-demo"
import {AccordionCompositeLayoutDemo} from "@qualcomm-ui/angular-docs/components+/accordion+/demos/accordion-composite-layout-demo"
import {AccordionControlledStateDemo} from "@qualcomm-ui/angular-docs/components+/accordion+/demos/accordion-controlled-state-demo"
import {AccordionDefaultValueDemo} from "@qualcomm-ui/angular-docs/components+/accordion+/demos/accordion-default-value-demo"
import {AccordionDisabledDemo} from "@qualcomm-ui/angular-docs/components+/accordion+/demos/accordion-disabled-demo"
import {AccordionFocusCallbackDemo} from "@qualcomm-ui/angular-docs/components+/accordion+/demos/accordion-focus-callback-demo"
import {AccordionIconDemo} from "@qualcomm-ui/angular-docs/components+/accordion+/demos/accordion-icon-demo"
import {AccordionMultipleDemo} from "@qualcomm-ui/angular-docs/components+/accordion+/demos/accordion-multiple-demo"
import {AccordionSecondaryTextDemo} from "@qualcomm-ui/angular-docs/components+/accordion+/demos/accordion-secondary-text-demo"
import {AccordionSimpleDemo} from "@qualcomm-ui/angular-docs/components+/accordion+/demos/accordion-simple-demo"
import {AccordionSimpleDirectivesDemo} from "@qualcomm-ui/angular-docs/components+/accordion+/demos/accordion-simple-directives-demo"
import {AccordionSizeDemo} from "@qualcomm-ui/angular-docs/components+/accordion+/demos/accordion-size-demo"
import {AccordionUncontainedDemo} from "@qualcomm-ui/angular-docs/components+/accordion+/demos/accordion-uncontained-demo"

@Component({
  imports: [
    AccordionCollapsibleDemo,
    AccordionCompositeDemo,
    AccordionCompositeLayoutDemo,
    AccordionControlledStateDemo,
    AccordionDefaultValueDemo,
    AccordionDisabledDemo,
    AccordionFocusCallbackDemo,
    AccordionIconDemo,
    AccordionMultipleDemo,
    AccordionSecondaryTextDemo,
    AccordionSimpleDemo,
    AccordionSimpleDirectivesDemo,
    AccordionSizeDemo,
    AccordionUncontainedDemo,
  ],
  selector: "app-accordion",
  template: `
    <div class="container">
      <div class="section">
        <h2 class="section-title">Collapsible</h2>
        <div class="demo-container">
          <accordion-collapsible-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Composite</h2>
        <div class="demo-container">
          <accordion-composite-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Composite Layout</h2>
        <div class="demo-container">
          <accordion-starting-indicator-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Controlled State</h2>
        <div class="demo-container">
          <accordion-controlled-state-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Default Value</h2>
        <div class="demo-container">
          <accordion-default-value-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Disabled</h2>
        <div class="demo-container">
          <accordion-disabled-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Focus Callback</h2>
        <div class="demo-container">
          <accordion-focus-callback-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Icon</h2>
        <div class="demo-container">
          <accordion-icon-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Multiple</h2>
        <div class="demo-container">
          <accordion-multiple-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Secondary Text</h2>
        <div class="demo-container">
          <accordion-secondary-text-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Simple</h2>
        <div class="demo-container">
          <accordion-simple-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Simple Directives</h2>
        <div class="demo-container">
          <accordion-simple-directives-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Size</h2>
        <div class="demo-container">
          <accordion-size-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Uncontained</h2>
        <div class="demo-container">
          <accordion-uncontained-demo />
        </div>
      </div>
    </div>
  `,
})
export class AccordionPage {}
