// packages/debug-apps/react-ssr/src/routes/components+/dialog+/_dialog.tsx
import AlertDialogDemo from "@qualcomm-ui/react-docs/components+/dialog+/demos/dialog-alert-dialog-demo"
import ControlledStateDemo from "@qualcomm-ui/react-docs/components+/dialog+/demos/dialog-controlled-state-demo"
import EmphasisDemo from "@qualcomm-ui/react-docs/components+/dialog+/demos/dialog-emphasis-demo"
import InsideScrollDemo from "@qualcomm-ui/react-docs/components+/dialog+/demos/dialog-inside-scroll-demo"
import OutsideScrollDemo from "@qualcomm-ui/react-docs/components+/dialog+/demos/dialog-outside-scroll-demo"
import PlacementDemo from "@qualcomm-ui/react-docs/components+/dialog+/demos/dialog-placement-demo"
import SizesDemo from "@qualcomm-ui/react-docs/components+/dialog+/demos/dialog-sizes-demo"

const demos = [
  {component: AlertDialogDemo, title: "Alert Dialog"},
  {component: ControlledStateDemo, title: "Controlled State"},
  {component: EmphasisDemo, title: "Emphasis"},
  {component: InsideScrollDemo, title: "Inside Scroll"},
  {component: OutsideScrollDemo, title: "Outside Scroll"},
  {component: PlacementDemo, title: "Placement"},
  {component: SizesDemo, title: "Sizes"},
]

export default function DialogDemos() {
  return (
    <div className="page">
      {demos.map(({component: Demo, title}) => (
        <div className="section" key={title}>
          <h2 className="section-title">{title}</h2>
          <div className="demo-container">
            <Demo />
          </div>
        </div>
      ))}
    </div>
  )
}

// packages/debug-apps/angular-csr/src/app/components/dialog.ts
import {Component} from "@angular/core"

import {DialogAlertDialogDemo} from "@qualcomm-ui/angular-docs/components+/dialog+/demos/dialog-alert-dialog-demo"
import {DialogControlledStateDemo} from "@qualcomm-ui/angular-docs/components+/dialog+/demos/dialog-controlled-state-demo"
import {DialogEmphasisDemo} from "@qualcomm-ui/angular-docs/components+/dialog+/demos/dialog-emphasis-demo"
import {DialogIndicatorIconDemo} from "@qualcomm-ui/angular-docs/components+/dialog+/demos/dialog-indicator-icon-demo"
import {DialogInsideScrollDemo} from "@qualcomm-ui/angular-docs/components+/dialog+/demos/dialog-inside-scroll-demo"
import {DialogOutsideScrollDemo} from "@qualcomm-ui/angular-docs/components+/dialog+/demos/dialog-outside-scroll-demo"
import {DialogPlacementDemo} from "@qualcomm-ui/angular-docs/components+/dialog+/demos/dialog-placement-demo"
import {DialogSizesDemo} from "@qualcomm-ui/angular-docs/components+/dialog+/demos/dialog-sizes-demo"

@Component({
  imports: [
    DialogAlertDialogDemo,
    DialogControlledStateDemo,
    DialogEmphasisDemo,
    DialogIndicatorIconDemo,
    DialogInsideScrollDemo,
    DialogOutsideScrollDemo,
    DialogPlacementDemo,
    DialogSizesDemo,
  ],
  selector: "app-dialog",
  template: `
    <div class="container">
      <div class="section">
        <h2 class="section-title">Alert Dialog</h2>
        <div class="demo-container">
          <dialog-alert-dialog-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Controlled State</h2>
        <div class="demo-container">
          <dialog-controlled-state-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Emphasis</h2>
        <div class="demo-container">
          <dialog-emphasis-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Indicator Icon</h2>
        <div class="demo-container">
          <dialog-indicator-icon-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Inside Scroll</h2>
        <div class="demo-container">
          <dialog-inside-scroll-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Outside Scroll</h2>
        <div class="demo-container">
          <dialog-outside-scroll-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Placement</h2>
        <div class="demo-container">
          <dialog-placement-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Sizes</h2>
        <div class="demo-container">
          <dialog-sizes-demo />
        </div>
      </div>
    </div>
  `,
})
export class DialogPage {}
