// packages/debug-apps/react-ssr/src/routes/components+/menu.tsx
import {MenuAnchorPointDemo as AnchorPointDemo} from "@qualcomm-ui/react-docs/components+/menu+/demos/menu-anchor-point-demo"
import {MenuAvatarDemo as AvatarDemo} from "@qualcomm-ui/react-docs/components+/menu+/demos/menu-avatar-demo"
import {MenuCheckboxItemsDemo as CheckboxItemsDemo} from "@qualcomm-ui/react-docs/components+/menu+/demos/menu-checkbox-items-demo"
import {MenuCheckboxSelectionStateDemo as CheckboxSelectionStateDemo} from "@qualcomm-ui/react-docs/components+/menu+/demos/menu-checkbox-selection-state-demo"
import {MenuContextMenuDemo as ContextMenuDemo} from "@qualcomm-ui/react-docs/components+/menu+/demos/menu-context-menu-demo"
import {MenuControlledStateDemo as ControlledStateDemo} from "@qualcomm-ui/react-docs/components+/menu+/demos/menu-controlled-state-demo"
import {MenuHideWhenDetachedDemo as HideWhenDetachedDemo} from "@qualcomm-ui/react-docs/components+/menu+/demos/menu-hide-when-detached-demo"
import {MenuItemCustomizationDemo as ItemCustomizationDemo} from "@qualcomm-ui/react-docs/components+/menu+/demos/menu-item-customization-demo"
import {MenuLinksDemo as LinksDemo} from "@qualcomm-ui/react-docs/components+/menu+/demos/menu-links-demo"
import {MenuNestedDemo as NestedDemo} from "@qualcomm-ui/react-docs/components+/menu+/demos/menu-nested-demo"
import {MenuPlacementDemo as PlacementDemo} from "@qualcomm-ui/react-docs/components+/menu+/demos/menu-placement-demo"
import {MenuRadioGroupDemo as RadioGroupDemo} from "@qualcomm-ui/react-docs/components+/menu+/demos/menu-radio-group-demo"
import {MenuSizesDemo as SizesDemo} from "@qualcomm-ui/react-docs/components+/menu+/demos/menu-sizes-demo"
import {MenuWithinDialogDemo as WithinDialogDemo} from "@qualcomm-ui/react-docs/components+/menu+/demos/menu-within-dialog-demo"

import {DemoPageLayout} from "~/components/demo-page-layout"

const demos = [
  {component: AnchorPointDemo, title: "Anchor Point"},
  {component: AvatarDemo, title: "Avatar"},
  {component: CheckboxItemsDemo, title: "Checkbox Items"},
  {component: CheckboxSelectionStateDemo, title: "Checkbox Selection State"},
  {component: ContextMenuDemo, title: "Context Menu"},
  {component: ControlledStateDemo, title: "Controlled State"},
  {component: HideWhenDetachedDemo, title: "Hide When Detached"},
  {component: ItemCustomizationDemo, title: "Item Customization"},
  {component: LinksDemo, title: "Links"},
  {component: NestedDemo, title: "Nested"},
  {component: PlacementDemo, title: "Placement"},
  {component: RadioGroupDemo, title: "Radio Group"},
  {component: SizesDemo, title: "Sizes"},
  {component: WithinDialogDemo, title: "Within Dialog"},
]

export default function MenuDemos() {
  return <DemoPageLayout componentName="menu" demos={demos} />
}

// packages/debug-apps/angular-csr/src/app/components/menu.ts
import {Component} from "@angular/core"

import {MenuAnchorPointDemo} from "@qualcomm-ui/angular-docs/components+/menu+/demos/menu-anchor-point-demo"
import {MenuAvatarDemo} from "@qualcomm-ui/angular-docs/components+/menu+/demos/menu-avatar-demo"
import {MenuCheckboxItemsDemo} from "@qualcomm-ui/angular-docs/components+/menu+/demos/menu-checkbox-items-demo"
import {MenuCheckboxStateDemo} from "@qualcomm-ui/angular-docs/components+/menu+/demos/menu-checkbox-state-demo"
import {MenuContextMenuDemo} from "@qualcomm-ui/angular-docs/components+/menu+/demos/menu-context-menu-demo"
import {MenuControlledStateDemo} from "@qualcomm-ui/angular-docs/components+/menu+/demos/menu-controlled-state-demo"
import {MenuHideWhenDetachedDemo} from "@qualcomm-ui/angular-docs/components+/menu+/demos/menu-hide-when-detached-demo"
import {MenuItemCustomizationDemo} from "@qualcomm-ui/angular-docs/components+/menu+/demos/menu-item-customization-demo"
import {MenuLinksDemo} from "@qualcomm-ui/angular-docs/components+/menu+/demos/menu-links-demo"
import {MenuNestedDemo} from "@qualcomm-ui/angular-docs/components+/menu+/demos/menu-nested-demo"
import {MenuPlacementDemo} from "@qualcomm-ui/angular-docs/components+/menu+/demos/menu-placement-demo"
import {MenuRadioGroupDemo} from "@qualcomm-ui/angular-docs/components+/menu+/demos/menu-radio-group-demo"
import {MenuRadioGroupStateDemo} from "@qualcomm-ui/angular-docs/components+/menu+/demos/menu-radio-group-state-demo"
import {MenuWithinDialogDemo} from "@qualcomm-ui/angular-docs/components+/menu+/demos/menu-within-dialog-demo"

@Component({
  imports: [
    MenuAnchorPointDemo,
    MenuAvatarDemo,
    MenuCheckboxItemsDemo,
    MenuCheckboxStateDemo,
    MenuContextMenuDemo,
    MenuControlledStateDemo,
    MenuHideWhenDetachedDemo,
    MenuItemCustomizationDemo,
    MenuLinksDemo,
    MenuNestedDemo,
    MenuPlacementDemo,
    MenuRadioGroupDemo,
    MenuRadioGroupStateDemo,
    MenuWithinDialogDemo,
  ],
  selector: "app-menu",
  template: `
    <div class="container">
      <div class="section">
        <h2 class="section-title">Anchor Point</h2>
        <div class="demo-container">
          <menu-anchor-point-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Avatar</h2>
        <div class="demo-container">
          <menu-avatar-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Checkbox Items</h2>
        <div class="demo-container">
          <menu-checkbox-items-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Checkbox State</h2>
        <div class="demo-container">
          <menu-checkbox-state-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Context Menu</h2>
        <div class="demo-container">
          <menu-context-menu-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Controlled State</h2>
        <div class="demo-container">
          <menu-controlled-state-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Hide When Detached</h2>
        <div class="demo-container">
          <menu-hide-when-detached-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Item Customization</h2>
        <div class="demo-container">
          <menu-item-customization-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Links</h2>
        <div class="demo-container">
          <menu-links-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Nested</h2>
        <div class="demo-container">
          <menu-nested-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Placement</h2>
        <div class="demo-container">
          <menu-placement-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Radio Group</h2>
        <div class="demo-container">
          <menu-radio-group-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Radio Group State</h2>
        <div class="demo-container">
          <menu-radio-group-state-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Within Dialog</h2>
        <div class="demo-container">
          <menu-within-dialog-demo />
        </div>
      </div>
    </div>
  `,
})
export class MenuPage {}
