// packages/debug-apps/react-ssr/src/routes/components+/pagination.tsx
import {PaginationControlledStateDemo as ControlledStateDemo} from "@qualcomm-ui/react-docs/components+/pagination+/demos/pagination-controlled-state-demo"
import {PaginationMetadataDemo as MetadataDemo} from "@qualcomm-ui/react-docs/components+/pagination+/demos/pagination-metadata-demo"
import {PaginationPageSizeDemo as PageSizeDemo} from "@qualcomm-ui/react-docs/components+/pagination+/demos/pagination-page-size-demo"
import {PaginationRangesDemo as RangesDemo} from "@qualcomm-ui/react-docs/components+/pagination+/demos/pagination-ranges-demo"
import {PaginationShowcaseDemo as ShowcaseDemo} from "@qualcomm-ui/react-docs/components+/pagination+/demos/pagination-showcase-demo"
import {PaginationSizesDemo as SizesDemo} from "@qualcomm-ui/react-docs/components+/pagination+/demos/pagination-sizes-demo"

import {DemoPageLayout} from "~/components/demo-page-layout"

const demos = [
  {component: ControlledStateDemo, title: "Controlled State"},
  {component: MetadataDemo, title: "Metadata"},
  {component: PageSizeDemo, title: "Page Size"},
  {component: RangesDemo, title: "Ranges"},
  {component: ShowcaseDemo, title: "Showcase"},
  {component: SizesDemo, title: "Sizes"},
]

export default function PaginationDemos() {
  return <DemoPageLayout componentName="pagination" demos={demos} />
}

// packages/debug-apps/angular-csr/src/app/components/pagination.ts
import {Component} from "@angular/core"

import {PaginationPageMetadataDemo} from "@qualcomm-ui/angular-docs/components+/pagination+/demos/pagination-page-metadata-demo"
import {PaginationPageSizeDemo} from "@qualcomm-ui/angular-docs/components+/pagination+/demos/pagination-page-size-demo"
import {PaginationRangesDemo} from "@qualcomm-ui/angular-docs/components+/pagination+/demos/pagination-ranges-demo"
import {PaginationShowcaseDemo} from "@qualcomm-ui/angular-docs/components+/pagination+/demos/pagination-showcase-demo"

@Component({
  imports: [
    PaginationPageMetadataDemo,
    PaginationPageSizeDemo,
    PaginationRangesDemo,
    PaginationShowcaseDemo,
  ],
  selector: "app-pagination",
  template: `
    <div class="container">
      <div class="section">
        <h2 class="section-title">Page Metadata</h2>
        <div class="demo-container">
          <pagination-page-metadata-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Page Size</h2>
        <div class="demo-container">
          <pagination-page-size-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Ranges</h2>
        <div class="demo-container">
          <pagination-directive-ranges-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Showcase</h2>
        <div class="demo-container">
          <pagination-directive-showcase-demo />
        </div>
      </div>
    </div>
  `,
})
export class PaginationPage {}
