// packages/debug-apps/react-ssr/src/routes/components+/tabs+/_tabs.tsx
import AddRemoveDemo from "@qualcomm-ui/react-docs/components+/tabs+/demos/tabs-add-remove-demo"
import ContainedSizesDemo from "@qualcomm-ui/react-docs/components+/tabs+/demos/tabs-contained-sizes-demo"
import ContextDemo from "@qualcomm-ui/react-docs/components+/tabs+/demos/tabs-context-demo"
import ControlledValueDemo from "@qualcomm-ui/react-docs/components+/tabs+/demos/tabs-controlled-value-demo"
import DisabledDemo from "@qualcomm-ui/react-docs/components+/tabs+/demos/tabs-disabled-demo"
import HorizontalDemo from "@qualcomm-ui/react-docs/components+/tabs+/demos/tabs-horizontal-demo"
import IconsDemo from "@qualcomm-ui/react-docs/components+/tabs+/demos/tabs-icons-demo"
import LazyMountedDemo from "@qualcomm-ui/react-docs/components+/tabs+/demos/tabs-lazy-mounted-demo"
import LineSizesDemo from "@qualcomm-ui/react-docs/components+/tabs+/demos/tabs-line-sizes-demo"
import LinksDemo from "@qualcomm-ui/react-docs/components+/tabs+/demos/tabs-links-demo"
import VerticalDemo from "@qualcomm-ui/react-docs/components+/tabs+/demos/tabs-vertical-demo"

const demos = [
  {component: AddRemoveDemo, title: "Add Remove"},
  {component: ContainedSizesDemo, title: "Contained Sizes"},
  {component: ContextDemo, title: "Context"},
  {component: ControlledValueDemo, title: "Controlled Value"},
  {component: DisabledDemo, title: "Disabled"},
  {component: HorizontalDemo, title: "Horizontal"},
  {component: IconsDemo, title: "Icons"},
  {component: LazyMountedDemo, title: "Lazy Mounted"},
  {component: LineSizesDemo, title: "Line Sizes"},
  {component: LinksDemo, title: "Links"},
  {component: VerticalDemo, title: "Vertical"},
]

export default function TabsDemos() {
  return (
    <div className="page">
      {demos.map(({component: Demo, title}) => (
        <div className="section" key={title}>
          <h2 className="section-title">{title}</h2>
          <div className="demo-container">
            <Demo />
          </div>
        </div>
      ))}
    </div>
  )
}

// packages/debug-apps/angular-csr/src/app/components/tabs.ts
import {Component} from "@angular/core"

import {TabsAddRemoveDemo} from "@qualcomm-ui/angular-docs/components+/tabs+/demos/tabs-add-remove-demo"
import {TabsContainedSizesDemo} from "@qualcomm-ui/angular-docs/components+/tabs+/demos/tabs-contained-sizes-demo"
import {TabsContextDemo} from "@qualcomm-ui/angular-docs/components+/tabs+/demos/tabs-context-demo"
import {TabsControlledValueDemo} from "@qualcomm-ui/angular-docs/components+/tabs+/demos/tabs-controlled-value-demo"
import {TabsDisabledDemo} from "@qualcomm-ui/angular-docs/components+/tabs+/demos/tabs-disabled-demo"
import {TabsHorizontalDemo} from "@qualcomm-ui/angular-docs/components+/tabs+/demos/tabs-horizontal-demo"
import {TabsIconsDemo} from "@qualcomm-ui/angular-docs/components+/tabs+/demos/tabs-icons-demo"
import {TabsLineSizesDemo} from "@qualcomm-ui/angular-docs/components+/tabs+/demos/tabs-line-sizes-demo"
import {TabsLinksDemo} from "@qualcomm-ui/angular-docs/components+/tabs+/demos/tabs-links-demo"
import {TabsVerticalDemo} from "@qualcomm-ui/angular-docs/components+/tabs+/demos/tabs-vertical-demo"

@Component({
  imports: [
    TabsAddRemoveDemo,
    TabsContainedSizesDemo,
    TabsContextDemo,
    TabsControlledValueDemo,
    TabsDisabledDemo,
    TabsHorizontalDemo,
    TabsIconsDemo,
    TabsLineSizesDemo,
    TabsLinksDemo,
    TabsVerticalDemo,
  ],
  selector: "app-tabs",
  template: `
    <div class="container">
      <div class="section">
        <h2 class="section-title">Add Remove</h2>
        <div class="demo-container">
          <tabs-add-remove-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Contained Sizes</h2>
        <div class="demo-container">
          <tabs-contained-sizes-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Context</h2>
        <div class="demo-container">
          <tabs-context-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Controlled Value</h2>
        <div class="demo-container">
          <tabs-controlled-value-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Disabled</h2>
        <div class="demo-container">
          <tabs-disabled-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Horizontal</h2>
        <div class="demo-container">
          <tabs-horizontal-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Icons</h2>
        <div class="demo-container">
          <tabs-icons-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Line Sizes</h2>
        <div class="demo-container">
          <tabs-line-sizes-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Links</h2>
        <div class="demo-container">
          <tabs-links-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Vertical</h2>
        <div class="demo-container">
          <tabs-vertical-demo />
        </div>
      </div>
    </div>
  `,
})
export class TabsPage {}
