// packages/debug-apps/react-ssr/src/routes/components+/toast+/_toast.tsx
import ActionDemo from "@qualcomm-ui/react-docs/components+/toast+/demos/toast-action-demo"
import DurationDemo from "@qualcomm-ui/react-docs/components+/toast+/demos/toast-duration-demo"
import EmphasisDemo from "@qualcomm-ui/react-docs/components+/toast+/demos/toast-emphasis-demo"
import MaxVisibleDemo from "@qualcomm-ui/react-docs/components+/toast+/demos/toast-max-visible-demo"
import OverlapDemo from "@qualcomm-ui/react-docs/components+/toast+/demos/toast-overlap-demo"
import PauseDemo from "@qualcomm-ui/react-docs/components+/toast+/demos/toast-pause-demo"
import PersistentDemo from "@qualcomm-ui/react-docs/components+/toast+/demos/toast-persistent-demo"
import PlacementDemo from "@qualcomm-ui/react-docs/components+/toast+/demos/toast-placement-demo"

const demos = [
  {component: ActionDemo, title: "Action"},
  {component: DurationDemo, title: "Duration"},
  {component: EmphasisDemo, title: "Emphasis"},
  {component: MaxVisibleDemo, title: "Max Visible"},
  {component: OverlapDemo, title: "Overlap"},
  {component: PauseDemo, title: "Pause"},
  {component: PersistentDemo, title: "Persistent"},
  {component: PlacementDemo, title: "Placement"},
]

export default function ToastDemos() {
  return (
    <div className="page">
      {demos.map(({component: Demo, title}) => (
        <div className="section" key={title}>
          <h2 className="section-title">{title}</h2>
          <div className="demo-container">
            <Demo />
          </div>
        </div>
      ))}
    </div>
  )
}

// packages/debug-apps/angular-csr/src/app/components/toast.ts
import {Component} from "@angular/core"

import {ToastActionDemo} from "@qualcomm-ui/angular-docs/components+/toast+/demos/toast-action-demo"
import {ToastDurationDemo} from "@qualcomm-ui/angular-docs/components+/toast+/demos/toast-duration-demo"
import {ToastEmphasisDemo} from "@qualcomm-ui/angular-docs/components+/toast+/demos/toast-emphasis-demo"
import {ToastMaxVisibleDemo} from "@qualcomm-ui/angular-docs/components+/toast+/demos/toast-max-visible-demo"
import {ToastOverlapDemo} from "@qualcomm-ui/angular-docs/components+/toast+/demos/toast-overlap-demo"
import {ToastPauseDemo} from "@qualcomm-ui/angular-docs/components+/toast+/demos/toast-pause-demo"
import {ToastPersistentDemo} from "@qualcomm-ui/angular-docs/components+/toast+/demos/toast-persistent-demo"
import {ToastPlacementDemo} from "@qualcomm-ui/angular-docs/components+/toast+/demos/toast-placement-demo"

@Component({
  imports: [
    ToastActionDemo,
    ToastDurationDemo,
    ToastEmphasisDemo,
    ToastMaxVisibleDemo,
    ToastOverlapDemo,
    ToastPauseDemo,
    ToastPersistentDemo,
    ToastPlacementDemo,
  ],
  selector: "app-toast",
  template: `
    <div class="container">
      <div class="section">
        <h2 class="section-title">Action</h2>
        <div class="demo-container">
          <toast-action-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Duration</h2>
        <div class="demo-container">
          <toast-duration-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Emphasis</h2>
        <div class="demo-container">
          <toast-emphasis-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Max Visible</h2>
        <div class="demo-container">
          <toast-max-visible-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Overlap</h2>
        <div class="demo-container">
          <toast-overlap-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Pause</h2>
        <div class="demo-container">
          <toast-pause-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Persistent</h2>
        <div class="demo-container">
          <toast-persistent-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Placement</h2>
        <div class="demo-container">
          <toast-placement-demo />
        </div>
      </div>
    </div>
  `,
})
export class ToastPage {}
