// packages/debug-apps/react-ssr/src/routes/components+/tooltip+/_tooltip.tsx
import CloseEventsDemo from "@qualcomm-ui/react-docs/components+/tooltip+/demos/tooltip-close-events-demo"
import CompositeDemo from "@qualcomm-ui/react-docs/components+/tooltip+/demos/tooltip-composite-demo"
import ControlledStateDemo from "@qualcomm-ui/react-docs/components+/tooltip+/demos/tooltip-controlled-state-demo"
import DisabledDemo from "@qualcomm-ui/react-docs/components+/tooltip+/demos/tooltip-disabled-demo"
import PlacementDemo from "@qualcomm-ui/react-docs/components+/tooltip+/demos/tooltip-placement-demo"
import SimpleDemo from "@qualcomm-ui/react-docs/components+/tooltip+/demos/tooltip-simple-demo"

const demos = [
  {component: CloseEventsDemo, title: "Close Events"},
  {component: CompositeDemo, title: "Composite"},
  {component: ControlledStateDemo, title: "Controlled State"},
  {component: DisabledDemo, title: "Disabled"},
  {component: PlacementDemo, title: "Placement"},
  {component: SimpleDemo, title: "Simple"},
]

export default function TooltipDemos() {
  return (
    <div className="page">
      {demos.map(({component: Demo, title}) => (
        <div className="section" key={title}>
          <h2 className="section-title">{title}</h2>
          <div className="demo-container">
            <Demo />
          </div>
        </div>
      ))}
    </div>
  )
}

// packages/debug-apps/angular-csr/src/app/components/tooltip.ts
import {Component} from "@angular/core"

import {TooltipCloseEventsDemo} from "@qualcomm-ui/angular-docs/components+/tooltip+/demos/tooltip-close-events-demo"
import {TooltipCompositeDemo} from "@qualcomm-ui/angular-docs/components+/tooltip+/demos/tooltip-composite-demo"
import {TooltipControlledStateDemo} from "@qualcomm-ui/angular-docs/components+/tooltip+/demos/tooltip-controlled-state-demo"
import {TooltipDisabledDemo} from "@qualcomm-ui/angular-docs/components+/tooltip+/demos/tooltip-disabled-demo"
import {TooltipPlacementDemo} from "@qualcomm-ui/angular-docs/components+/tooltip+/demos/tooltip-placement-demo"
import {TooltipSimpleDemo} from "@qualcomm-ui/angular-docs/components+/tooltip+/demos/tooltip-simple-demo"

@Component({
  imports: [
    TooltipCloseEventsDemo,
    TooltipCompositeDemo,
    TooltipControlledStateDemo,
    TooltipDisabledDemo,
    TooltipPlacementDemo,
    TooltipSimpleDemo,
  ],
  selector: "app-tooltip",
  template: `
    <div class="container">
      <div class="section">
        <h2 class="section-title">Close Events</h2>
        <div class="demo-container">
          <tooltip-close-events-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Composite</h2>
        <div class="demo-container">
          <tooltip-composite-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Controlled State</h2>
        <div class="demo-container">
          <tooltip-controlled-state-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Disabled</h2>
        <div class="demo-container">
          <tooltip-disabled-demo />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Placement</h2>
        <div class="demo-container">
          <tooltip-placement />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Simple</h2>
        <div class="demo-container">
          <tooltip-simple-demo />
        </div>
      </div>
    </div>
  `,
})
export class TooltipPage {}
