// packages/docs/react-docs/src/routes/components+/button-group+/demos/button-group-shared-props-demo.tsx
import type {ReactElement} from "react"

import {AArrowDown} from "lucide-react"

import {Button, ButtonGroup} from "@qualcomm-ui/react/button"

export default function ButtonGroupSharedPropsDemo(): ReactElement {
  return (
    <div className="flex w-full flex-col gap-4">
      {/* preview */}
      <ButtonGroup disabled size="sm">
        <Button startIcon={AArrowDown} variant="ghost">
          Button
        </Button>
        <Button startIcon={AArrowDown} variant="outline">
          Button
        </Button>
        <Button emphasis="primary" startIcon={AArrowDown} variant="fill">
          Button
        </Button>
      </ButtonGroup>
      <ButtonGroup variant="outline">
        <Button startIcon={AArrowDown}>Button</Button>
        <Button startIcon={AArrowDown}>Button</Button>
        <Button emphasis="primary" startIcon={AArrowDown}>
          Button
        </Button>
      </ButtonGroup>
      {/* preview */}
    </div>
  )
}

// packages/docs/angular-docs/src/routes/components+/button-group+/demos/button-group-shared-props-demo.ts
import {Component} from "@angular/core"
import {AArrowDown} from "lucide-angular"

import {provideIcons} from "@qualcomm-ui/angular-core/lucide"
import {ButtonModule} from "@qualcomm-ui/angular/button"

@Component({
  imports: [ButtonModule],
  providers: [provideIcons({AArrowDown})],
  selector: "button-group-shared-props-demo",
  template: `
    <div class="flex w-full flex-col gap-4">
      <div disabled q-button-group size="sm">
        <button q-button startIcon="AArrowDown" variant="ghost">Button</button>
        <button q-button startIcon="AArrowDown" variant="outline">
          Button
        </button>
        <button
          emphasis="primary"
          q-button
          startIcon="AArrowDown"
          variant="fill"
        >
          Button
        </button>
      </div>
      <div q-button-group variant="outline">
        <button q-button startIcon="AArrowDown">Button</button>
        <button q-button startIcon="AArrowDown">Button</button>
        <button emphasis="primary" q-button startIcon="AArrowDown">
          Button
        </button>
      </div>
    </div>
  `,
})
export class ButtonGroupSharedPropsDemo {}
