// packages/docs/react-table-docs/src/routes/features+/column-sizing+/demos/column-sizing-demo.tsx
import {useMemo, useState} from "react"

import {
  type ColumnResizeDirection,
  type ColumnResizeMode,
  getCoreRowModel,
} from "@qualcomm-ui/core/table"
import {CodeHighlight} from "@qualcomm-ui/react-mdx/code-highlight"
import {Button} from "@qualcomm-ui/react/button"
import {Radio, RadioGroup} from "@qualcomm-ui/react/radio"
import {flexRender, Table, useReactTable} from "@qualcomm-ui/react/table"

import {columns, useUserData} from "./use-data"

export default function ColumnSizingDemo() {
  const {data = [], refetch} = useUserData(5)

  const [columnResizeMode, setColumnResizeMode] =
    useState<ColumnResizeMode>("onChange")

  const [columnResizeDirection, setColumnResizeDirection] =
    useState<ColumnResizeDirection>("ltr")

  const table = useReactTable({
    columnResizeDirection,
    columnResizeMode,
    columns,
    data: useMemo(() => data, [data]),
    getCoreRowModel: getCoreRowModel(),
  })

  return (
    <div className="flex w-full flex-col gap-4 p-2">
      <Table.Root showColumnDivider>
        <Table.ActionBar className="gap-8">
          <Button onClick={() => refetch()} variant="outline">
            Regenerate
          </Button>

          <RadioGroup
            label="Resize"
            onValueChange={(value) =>
              setColumnResizeMode(value as ColumnResizeMode)
            }
            orientation="horizontal"
            value={columnResizeMode}
          >
            <Radio label="onChange" value="onChange" />
            <Radio label="onEnd" value="onEnd" />
          </RadioGroup>

          <RadioGroup
            label="Direction"
            onValueChange={(value) =>
              setColumnResizeDirection(value as ColumnResizeDirection)
            }
            orientation="horizontal"
            value={columnResizeDirection}
          >
            <Radio label="ltr" value="ltr" />
            <Radio label="rtl" value="rtl" />
          </RadioGroup>
        </Table.ActionBar>

        <Table.ScrollContainer>
          <Table.Table
            dir={table.options.columnResizeDirection}
            style={{width: table.getCenterTotalSize()}}
          >
            <Table.Header>
              {table.getHeaderGroups().map((headerGroup) => (
                <Table.Row key={headerGroup.id}>
                  {headerGroup.headers.map((header) => (
                    <Table.HeaderCell
                      key={header.id}
                      className="relative text-justify"
                      colSpan={header.colSpan}
                      style={{width: header.getSize()}}
                    >
                      <div className="inline-flex w-full items-center justify-between gap-4">
                        {header.isPlaceholder
                          ? null
                          : flexRender(
                              header.column.columnDef.header,
                              header.getContext(),
                            )}

                        <Table.ColumnResizeHandle header={header} />
                      </div>
                    </Table.HeaderCell>
                  ))}
                </Table.Row>
              ))}
            </Table.Header>
            <Table.Body>
              {table.getRowModel().rows.map((row) => (
                <Table.Row key={row.id}>
                  {row.getVisibleCells().map((cell) => (
                    <Table.Cell
                      key={cell.id}
                      style={{
                        width: cell.column.getSize(),
                      }}
                    >
                      {flexRender(
                        cell.column.columnDef.cell,
                        cell.getContext(),
                      )}
                    </Table.Cell>
                  ))}
                </Table.Row>
              ))}
            </Table.Body>
          </Table.Table>
        </Table.ScrollContainer>
      </Table.Root>

      <CodeHighlight
        className="w-full"
        code={JSON.stringify(
          {
            columnSizing: table.getState().columnSizing,
            columnSizingInfo: table.getState().columnSizingInfo,
          },
          null,
          2,
        )}
        disableCopy
        language="json"
      />
    </div>
  )
}

// packages/docs/angular-table-docs/src/routes/features+/column-sizing+/demos/column-sizing-demo.ts
import {Component, computed, signal} from "@angular/core"
import {FormsModule} from "@angular/forms"

import {ButtonModule} from "@qualcomm-ui/angular/button"
import {ProgressRingModule} from "@qualcomm-ui/angular/progress-ring"
import {RadioModule} from "@qualcomm-ui/angular/radio"
import {
  type AngularTable,
  createAngularTable,
  TableModule,
} from "@qualcomm-ui/angular/table"
import {
  type ColumnResizeDirection,
  type ColumnResizeMode,
  getCoreRowModel,
} from "@qualcomm-ui/core/table"

import {columns, createUserQuery, type User} from "./data"

@Component({
  imports: [
    TableModule,
    ButtonModule,
    ProgressRingModule,
    RadioModule,
    FormsModule,
  ],
  selector: "column-sizing-demo",
  template: `
    <div class="flex w-full flex-col gap-4 p-2">
      <div q-table-root showColumnDivider>
        <div class="gap-8" q-table-action-bar>
          <button q-button variant="outline" (click)="query.refetch()">
            Regenerate
          </button>

          <fieldset
            name="resizeMode"
            orientation="horizontal"
            q-radio-group
            [(ngModel)]="columnResizeMode"
          >
            <div q-radio-group-label>Resize</div>
            <div q-radio-group-items>
              <label label="onChange" q-radio value="onChange"></label>
              <label label="onEnd" q-radio value="onEnd"></label>
            </div>
          </fieldset>

          <fieldset
            name="direction"
            orientation="horizontal"
            q-radio-group
            [(ngModel)]="columnResizeDirection"
          >
            <div q-radio-group-label>Direction</div>
            <div q-radio-group-items>
              <label label="ltr" q-radio value="ltr"></label>
              <label label="rtl" q-radio value="rtl"></label>
            </div>
          </fieldset>
        </div>

        <div q-table-scroll-container>
          <table
            q-table-table
            [attr.dir]="columnResizeDirection()"
            [style.width.px]="table().getCenterTotalSize()"
          >
            <thead q-table-header>
              @for (
                headerGroup of table().getHeaderGroups();
                track headerGroup.id
              ) {
                <tr q-table-row>
                  @for (header of headerGroup.headers; track header.id) {
                    <th
                      class="relative text-justify"
                      q-table-header-cell
                      [colSpan]="header.colSpan"
                      [style.width.px]="header.getSize()"
                    >
                      <div
                        class="inline-flex w-full items-center justify-between gap-4"
                      >
                        @if (!header.isPlaceholder) {
                          <ng-container *renderHeader="header; let value">
                            {{ value }}
                          </ng-container>
                        }

                        <div
                          q-table-column-resize-handle
                          [header]="header"
                        ></div>
                      </div>
                    </th>
                  }
                </tr>
              }
            </thead>
            <tbody q-table-body>
              @for (row of table().getRowModel().rows; track row.id) {
                <tr q-table-row>
                  @for (cell of row.getVisibleCells(); track cell.id) {
                    <td q-table-cell [style.width.px]="cell.column.getSize()">
                      <ng-container *renderCell="cell; let value">
                        {{ value }}
                      </ng-container>
                    </td>
                  }
                </tr>
              }
            </tbody>
          </table>
        </div>
      </div>
    </div>
  `,
})
export class ColumnSizingDemo {
  protected readonly query = createUserQuery(5)

  protected readonly columnResizeMode = signal<ColumnResizeMode>("onChange")

  protected readonly columnResizeDirection =
    signal<ColumnResizeDirection>("ltr")

  protected readonly table = computed<AngularTable<User>>(() =>
    createAngularTable(() => ({
      columnResizeDirection: this.columnResizeDirection(),
      columnResizeMode: this.columnResizeMode(),
      columns,
      data: this.query.data() || [],
      getCoreRowModel: getCoreRowModel(),
    })),
  )
}
