// packages/docs/angular-docs/src/routes/components+/side-nav+/demos/side-nav-collapsed-demo.ts
import {Component, signal} from "@angular/core"
import {PanelLeftClose, PanelLeftOpen} from "lucide-angular"

import {provideIcons} from "@qualcomm-ui/angular-core/lucide"
import {ButtonModule} from "@qualcomm-ui/angular/button"
import {IconDirective} from "@qualcomm-ui/angular/icon"
import {SideNavModule} from "@qualcomm-ui/angular/side-nav"

import {collection, icons} from "./items"
import {QLogoComponent} from "./q-logo.component"

@Component({
  imports: [SideNavModule, IconDirective, ButtonModule, QLogoComponent],
  providers: [provideIcons({...icons, PanelLeftClose, PanelLeftOpen})],
  selector: "side-nav-collapsed-demo",
  template: `
    <div class="flex w-full justify-start">
      <!-- preview -->
      <div
        q-side-nav-root
        [collection]="collection"
        [open]="open()"
        (openChanged)="open.set($event)"
      >
        <div q-side-nav-header>
          <div q-side-nav-header-logo>
            <q-logo />
          </div>
          <div q-side-nav-header-title>Qualcomm</div>
          <button q-side-nav-collapse-trigger></button>
        </div>

        @for (
          node of collection.rootNode.nodes;
          let i = $index;
          track collection.getNodeValue(node)
        ) {
          <q-side-nav-nodes [indexPath]="[i]" [node]="node">
            <ng-template
              let-branch
              q-side-nav-branch-template
              [rootNode]="collection.rootNode"
            >
              <div q-side-nav-branch-node [attr.aria-label]="branch.node.text">
                <div q-side-nav-node-indicator></div>
                @if (branch.node.icon) {
                  <svg q-side-nav-node-icon [qIcon]="branch.node.icon"></svg>
                }
                <span q-side-nav-node-text>{{ branch.node.text }}</span>
                <div q-side-nav-branch-trigger></div>
              </div>
            </ng-template>

            <ng-template
              let-leaf
              q-side-nav-leaf-template
              [rootNode]="collection.rootNode"
            >
              <div q-side-nav-leaf-node [attr.aria-label]="leaf.node.text">
                <div q-side-nav-node-indicator></div>
                @if (leaf.node.icon) {
                  <svg q-side-nav-node-icon [qIcon]="leaf.node.icon"></svg>
                }
                <span q-side-nav-node-text>{{ leaf.node.text }}</span>
              </div>
            </ng-template>
          </q-side-nav-nodes>
        }
      </div>
      <!-- preview -->
    </div>
  `,
})
export class SideNavCollapsedDemo {
  collection = collection
  readonly open = signal(false)
}

// packages/docs/react-docs/src/routes/components+/side-nav+/demos/side-nav-collapsed-demo.tsx
import {useState} from "react"

import {SideNav} from "@qualcomm-ui/react/side-nav"

import {collection} from "./grouped-items"
import {QLogo} from "./q-logo"

export function SideNavCollapsedDemo() {
  const [open, setOpen] = useState<boolean>(false)

  return (
    <div className="flex w-full justify-start">
      <SideNav.Root collection={collection} onOpenChange={setOpen} open={open}>
        <SideNav.Header>
          <SideNav.HeaderLogo>
            <QLogo />
          </SideNav.HeaderLogo>
          <SideNav.HeaderTitle>Qualcomm</SideNav.HeaderTitle>
          <SideNav.CollapseTrigger />
        </SideNav.Header>

        {collection
          .groupChildren([], (node) => node.group ?? "ungrouped", [
            "ungrouped",
            "Main menu",
          ])
          .map((group) => (
            <SideNav.Group key={group.key}>
              <SideNav.Divider />

              {group.key === "ungrouped" ? null : (
                <SideNav.GroupLabel>{group.key}</SideNav.GroupLabel>
              )}
              {group.items.map(({indexPath, node}) => (
                <SideNav.Nodes
                  key={collection.getNodeValue(node)}
                  indexPath={indexPath}
                  node={node}
                  renderBranch={({node}) => (
                    <SideNav.BranchNode aria-label={node.text}>
                      <SideNav.NodeIndicator />
                      {node.icon ? <SideNav.NodeIcon icon={node.icon} /> : null}
                      <SideNav.NodeText>{node.text}</SideNav.NodeText>
                      <SideNav.BranchTrigger />
                    </SideNav.BranchNode>
                  )}
                  renderLeaf={({node}) => (
                    <SideNav.LeafNode aria-label={node.text}>
                      <SideNav.NodeIndicator />
                      {node.icon ? <SideNav.NodeIcon icon={node.icon} /> : null}
                      <SideNav.NodeText>{node.text}</SideNav.NodeText>
                    </SideNav.LeafNode>
                  )}
                />
              ))}
            </SideNav.Group>
          ))}
      </SideNav.Root>
    </div>
  )
}
