// packages/docs/angular-docs/src/routes/components+/switch-group+/demos/switch-group-simple-demo.ts
import {Component} from "@angular/core"

import {SwitchModule} from "@qualcomm-ui/angular/switch"
import {SwitchGroupModule} from "@qualcomm-ui/angular/switch-group"

@Component({
  imports: [SwitchGroupModule, SwitchModule],
  selector: "switch-group-simple-demo",
  template: `
    <!-- preview -->
    <fieldset hint="Select at least one" label="Notifications" q-switch-group>
      <label label="Email" q-switch></label>
      <label label="SMS" q-switch></label>
      <label label="Push" q-switch></label>
    </fieldset>
    <!-- preview -->
  `,
})
export class SwitchGroupSimpleDemo {}

// packages/docs/react-docs/src/routes/components+/switch-group+/demos/switch-group-simple-demo.tsx
import type {ReactElement} from "react"

import {Switch} from "@qualcomm-ui/react/switch"
import {SwitchGroup} from "@qualcomm-ui/react/switch-group"

export function SwitchGroupSimpleDemo(): ReactElement {
  return (
    // preview
    <SwitchGroup hint="Select at least one" label="Notifications">
      <Switch label="Email" />
      <Switch label="SMS" />
      <Switch label="Push" />
    </SwitchGroup>
    // preview
  )
}
