// packages/docs/angular-docs/src/routes/components+/switch-group+/demos/switch-group-composite-demo.ts
import {Component} from "@angular/core"

import {FieldGroupModule} from "@qualcomm-ui/angular/field-group"
import {SwitchModule} from "@qualcomm-ui/angular/switch"

@Component({
  imports: [FieldGroupModule, SwitchModule],
  selector: "switch-group-composite-demo",
  template: `
    <!-- preview -->
    <fieldset q-field-group-root>
      <legend q-field-group-label>Notifications</legend>
      <div q-field-group-items>
        <label label="Email" q-switch></label>
        <label label="SMS" q-switch></label>
        <label label="Push" q-switch></label>
      </div>
      <div q-field-group-hint>Select at least one</div>
    </fieldset>
    <!-- preview -->
  `,
})
export class SwitchGroupCompositeDemo {}

// packages/docs/react-docs/src/routes/components+/switch-group+/demos/switch-group-composite-demo.tsx
import type {ReactElement} from "react"

import {Switch} from "@qualcomm-ui/react/switch"
import {SwitchGroup} from "@qualcomm-ui/react/switch-group"

export function SwitchGroupCompositeDemo(): ReactElement {
  return (
    // preview
    <SwitchGroup.Root>
      <SwitchGroup.Label>Notifications</SwitchGroup.Label>
      <SwitchGroup.Items>
        <Switch label="Email" />
        <Switch label="SMS" />
        <Switch label="Push" />
      </SwitchGroup.Items>
      <SwitchGroup.Hint>Select at least one</SwitchGroup.Hint>
    </SwitchGroup.Root>
    // preview
  )
}
