// packages/debug-apps/react-ssr/src/routes/components+/progress-ring+/demos/progress-ring-value-demo.tsx
import {type ReactElement, useState} from "react"

import {Minus, Plus} from "lucide-react"

import {IconButton} from "@qualcomm-ui/react/button"
import {ProgressRing} from "@qualcomm-ui/react/progress-ring"

export default function ProgressRingValueDemo(): ReactElement {
  const [value, setValue] = useState<number>(0)

  const increment = () => setValue((prevValue) => Math.min(100, prevValue + 10))
  const decrement = () => setValue((prevValue) => Math.max(0, prevValue - 10))

  return (
    <div className="flex flex-col gap-4">
      {/* preview */}
      <ProgressRing
        size="lg"
        value={value}
        valueText={(api) => `${api.valuePercent}%`}
      />
      {/* preview */}
      <div className="flex gap-2">
        <IconButton
          aria-label="Decrement by 10"
          icon={Minus}
          onClick={decrement}
          size="sm"
          variant="outline"
        />
        <IconButton
          aria-label="Increment by 10"
          icon={Plus}
          onClick={increment}
          size="sm"
          variant="outline"
        />
      </div>
    </div>
  )
}

// packages/docs/angular-docs/src/routes/components+/progress-ring+/demos/progress-ring-value-demo.ts
import {Component, signal} from "@angular/core"
import {Minus, Plus} from "lucide-angular"

import {ButtonModule} from "@qualcomm-ui/angular/button"
import {ProgressRingModule} from "@qualcomm-ui/angular/progress-ring"
import {provideIcons} from "@qualcomm-ui/angular-core/lucide"

@Component({
  imports: [ProgressRingModule, ButtonModule],
  providers: [provideIcons({Minus, Plus})],
  selector: "progress-ring-value-demo",
  template: `
    <div class="flex flex-col gap-4">
      <!-- preview -->
      <div q-progress-ring size="lg" [value]="value()">
        <svg aria-label="Loading" q-progress-ring-circle></svg>
        <div *progressRingContext="let context" q-progress-ring-value-text>
          {{ context.valuePercent }}%
        </div>
      </div>
      <!-- preview -->
      <div class="flex gap-2">
        <button
          icon="Minus"
          q-icon-button
          size="sm"
          variant="outline"
          (click)="decrement()"
        ></button>
        <button
          icon="Plus"
          q-icon-button
          size="sm"
          variant="outline"
          (click)="increment()"
        ></button>
      </div>
    </div>
  `,
})
export class ProgressRingValueDemo {
  readonly value = signal(0)

  increment() {
    this.value.update((prev) => Math.min(prev + 10, 100))
  }

  decrement() {
    this.value.update((prev) => Math.max(prev - 10, 0))
  }
}
