// packages/docs/react-docs/src/routes/components+/progress-ring+/demos/progress-ring-explorer-demo.tsx
import type {ReactElement} from "react"

import {ProgressRing} from "@qualcomm-ui/react/progress-ring"

export function ProgressRingExplorerDemo(): ReactElement {
  return (
    <ProgressRing
      label="Uploading"
      size="lg"
      value={64}
      valueText={(api) => `${api.valuePercent}%`}
    />
  )
}

// packages/docs/angular-docs/src/routes/components+/progress-ring+/demos/progress-ring-explorer-demo.ts
import {Component} from "@angular/core"

import {ProgressRingModule} from "@qualcomm-ui/angular/progress-ring"

@Component({
  imports: [ProgressRingModule],
  selector: "progress-ring-explorer-demo",
  template: `
    <div label="Uploading" q-progress-ring size="lg" value="64">
      <div *progressRingContext="let context" q-progress-ring-value-text>
        {{ context.valuePercent }}%
      </div>
    </div>
  `,
})
export class ProgressRingExplorerDemo {}
