// packages/docs/react-docs/src/routes/components+/progress-ring+/demos/progress-ring-value-text-demo.tsx
import {type ReactElement, useEffect, useState} from "react"

import {ProgressRing} from "@qualcomm-ui/react/progress-ring"

export function ProgressRingValueTextDemo(): ReactElement {
  const [value, setValue] = useState<number>(0)

  useEffect(() => {
    function increment() {
      setValue((prevValue) => {
        if (prevValue === 100) {
          return 0
        }
        return prevValue + 10
      })
    }
    const timer = setInterval(increment, 1000)
    return () => clearInterval(timer)
  }, [])

  return (
    // preview
    <ProgressRing
      size="lg"
      value={value}
      valueText={(api) => `${api.valuePercent}%`}
    />
    // preview
  )
}

// packages/docs/angular-docs/src/routes/components+/progress-ring+/demos/progress-ring-value-text-demo.ts
import {Component, type OnInit, signal} from "@angular/core"

import {useOnDestroy} from "@qualcomm-ui/angular-core/common"
import {ProgressRingModule} from "@qualcomm-ui/angular/progress-ring"

@Component({
  imports: [ProgressRingModule],
  selector: "progress-ring-value-text-demo",
  template: `
    <div label="Loading..." q-progress-ring size="lg" [value]="value()">
      <div *progressRingContext="let context" q-progress-ring-value-text>
        {{ context.valuePercent }}%
      </div>
    </div>
  `,
})
export class ProgressRingValueTextDemo implements OnInit {
  protected readonly onDestroy = useOnDestroy()
  protected readonly value = signal(0)

  ngOnInit() {
    const timer = setInterval(() => {
      this.value.update((prevValue) => {
        if (prevValue === 100) {
          return 0
        }
        return prevValue + 10
      })
    }, 1000)

    this.onDestroy(() => {
      clearInterval(timer)
    })
  }
}
