// packages/frameworks/angular/src/checkbox/checkbox-error-text.component.ts
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import {Component, computed, input} from "@angular/core"
import {LucideCircleAlert} from "@lucide/angular"

import {CoreCheckboxErrorTextDirective} from "@qualcomm-ui/angular-core/checkbox"
import type {LucideIconOrString} from "@qualcomm-ui/angular-core/lucide"

import {useQdsCheckboxContext} from "./qds-checkbox-context.service"

/**
 * Error message displayed when the checkbox is invalid.
 */
@Component({
  selector: "[q-checkbox-error-text]",
  standalone: false,
  template: `
    <svg [qIcon]="icon()!" />
    <ng-content />
  `,
})
export class CheckboxErrorTextComponent extends CoreCheckboxErrorTextDirective {
  /**
   * Error indicator icon.
   *
   * @default LucideCircleAlert
   */
  readonly icon = input<LucideIconOrString>(LucideCircleAlert)

  protected readonly qdsCheckboxContext = useQdsCheckboxContext()

  constructor() {
    super()
    this.trackBindings.extendWith(
      computed(() => this.qdsCheckboxContext().getErrorTextBindings()),
    )
  }
}

// packages/frameworks/react/src/checkbox/checkbox-error-text.tsx
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import type {ReactElement, ReactNode} from "react"

import {AlertCircle} from "lucide-react"

import {
  InputErrorText,
  type InputErrorTextProps,
} from "@qualcomm-ui/react/input"
import {useCheckboxErrorText} from "@qualcomm-ui/react-core/checkbox"
import type {LucideIconOrElement} from "@qualcomm-ui/react-core/lucide"
import type {IdProp} from "@qualcomm-ui/react-core/system"
import {mergeProps} from "@qualcomm-ui/utils/merge-props"

import {useQdsCheckboxContext} from "./qds-checkbox-context"

export interface CheckboxErrorTextProps extends IdProp, InputErrorTextProps {
  /**
   * React {@link https://react.dev/learn/passing-props-to-a-component#passing-jsx-as-children children} prop.
   */
  children?: ReactNode

  /**
   * An icon to display next to the error text.
   *
   * @default `<AlertCircle />`
   */
  icon?: LucideIconOrElement
}

/**
 * Error message displayed when the checkbox is invalid. Renders a `<div>` element
 * by default.
 */
export function CheckboxErrorText({
  children,
  id,
  ...props
}: CheckboxErrorTextProps): ReactElement {
  const contextProps = useCheckboxErrorText({id})
  const qdsContext = useQdsCheckboxContext()
  const mergedProps = mergeProps(
    contextProps,
    qdsContext.getErrorTextBindings(),
    props,
  )

  return (
    <InputErrorText icon={AlertCircle} {...mergedProps}>
      {children}
    </InputErrorText>
  )
}
